
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    
    const start_date = searchParams.get('start_date');
    const end_date = searchParams.get('end_date');
    const min_mood_rating = searchParams.get('min_mood_rating') ? parseInt(searchParams.get('min_mood_rating')) : null;
    const max_mood_rating = searchParams.get('max_mood_rating') ? parseInt(searchParams.get('max_mood_rating')) : null;
    const min_energy_level = searchParams.get('min_energy_level') ? parseInt(searchParams.get('min_energy_level')) : null;
    const max_energy_level = searchParams.get('max_energy_level') ? parseInt(searchParams.get('max_energy_level')) : null;
    const page = parseInt(searchParams.get('page')) || 1;
    const limit = parseInt(searchParams.get('limit')) || 10;
    
    // Validate pagination parameters
    if (page < 1) {
      return NextResponse.json({ error: 'Vitalisona: Page number must be greater than 0' }, { status: 400 });
    }
    if (limit < 1 || limit > 100) {
      return NextResponse.json({ error: 'Vitalisona: Limit must be between 1 and 100' }, { status: 400 });
    }
    
    // Validate rating parameters
    if (min_mood_rating !== null && (min_mood_rating < 1 || min_mood_rating > 10)) {
      return NextResponse.json({ error: 'Vitalisona: Minimum mood rating must be between 1 and 10' }, { status: 400 });
    }
    if (max_mood_rating !== null && (max_mood_rating < 1 || max_mood_rating > 10)) {
      return NextResponse.json({ error: 'Vitalisona: Maximum mood rating must be between 1 and 10' }, { status: 400 });
    }
    if (min_energy_level !== null && (min_energy_level < 1 || min_energy_level > 10)) {
      return NextResponse.json({ error: 'Vitalisona: Minimum energy level must be between 1 and 10' }, { status: 400 });
    }
    if (max_energy_level !== null && (max_energy_level < 1 || max_energy_level > 10)) {
      return NextResponse.json({ error: 'Vitalisona: Maximum energy level must be between 1 and 10' }, { status: 400 });
    }
    
    // Validate date format if provided
    if (start_date && !/^\d{4}-\d{2}-\d{2}$/.test(start_date)) {
      return NextResponse.json({ error: 'Vitalisona: Start date must be in YYYY-MM-DD format' }, { status: 400 });
    }
    if (end_date && !/^\d{4}-\d{2}-\d{2}$/.test(end_date)) {
      return NextResponse.json({ error: 'Vitalisona: End date must be in YYYY-MM-DD format' }, { status: 400 });
    }
    
    // Build WHERE conditions with proper parameter tracking
    let queryParams = [];
    let whereConditions = ['userid = ?'];
    queryParams.push(user_id);
    
    // Date range filters
    if (start_date) {
      whereConditions.push('entry_date >= ?');
      queryParams.push(start_date);
    }
    if (end_date) {
      whereConditions.push('entry_date <= ?');
      queryParams.push(end_date);
    }
    
    // Mood rating filters
    if (min_mood_rating !== null) {
      whereConditions.push('mood_rating >= ?');
      queryParams.push(min_mood_rating);
    }
    if (max_mood_rating !== null) {
      whereConditions.push('mood_rating <= ?');
      queryParams.push(max_mood_rating);
    }
    
    // Energy level filters
    if (min_energy_level !== null) {
      whereConditions.push('energy_level >= ?');
      queryParams.push(min_energy_level);
    }
    if (max_energy_level !== null) {
      whereConditions.push('energy_level <= ?');
      queryParams.push(max_energy_level);
    }
    
    const whereClause = whereConditions.join(' AND ');
    
    // Get total count
    const countQuery = `SELECT COUNT(*) as total FROM wellnessjournal WHERE ${whereClause}`;
    const countResult = await db_query(db, countQuery, queryParams);
    const total = countResult[0].total;
    
    // Calculate pagination
    const offset = (page - 1) * limit;
    const totalpages = Math.ceil(total / limit);
    
    // Get paginated data
    const dataQuery = `
      SELECT id, entry_date, mood_rating, energy_level, stress_level, sleep_quality, 
             notes, session_feedback, goals, created_at
      FROM wellnessjournal 
      WHERE ${whereClause}
      ORDER BY entry_date DESC, created_at DESC
      LIMIT ? OFFSET ?
    `;
    
    const finalParams = [...queryParams, limit, offset];
    const journalEntries = await db_query(db, dataQuery, finalParams);
    
    // Format response data
    const data = journalEntries.map(entry => ({
      id: entry.id,
      entry_date: entry.entry_date,
      mood_rating: entry.mood_rating,
      energy_level: entry.energy_level,
      stress_level: entry.stress_level,
      sleep_quality: entry.sleep_quality,
      notes: entry.notes,
      session_feedback: entry.session_feedback,
      goals: entry.goals,
      created_at: entry.created_at
    }));
    
    const result = {
      data: data,
      total: total,
      page: page,
      limit: limit,
      totalpages: totalpages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona WellnessJournalList API error:', error);
    return NextResponse.json({ error: 'Vitalisona: Failed to retrieve wellness journal entries' }, { status: 500 });
  }
}

