
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const category = searchParams.get('category');
    const availableParam = searchParams.get('available');
    const minPriceParam = searchParams.get('min_price');
    const maxPriceParam = searchParams.get('max_price');
    const pageParam = searchParams.get('page');
    const limitParam = searchParams.get('limit');
    
    // Convert and validate parameters
    const available = availableParam !== null ? availableParam === 'true' : null;
    const minPrice = minPriceParam ? parseFloat(minPriceParam) : null;
    const maxPrice = maxPriceParam ? parseFloat(maxPriceParam) : null;
    const page = pageParam ? parseInt(pageParam) : 1;
    const limit = limitParam ? parseInt(limitParam) : 20;
    
    // Validate pagination parameters
    if (page < 1) {
      return NextResponse.json({ 
        error: 'Invalid page number. Page must be 1 or greater.' 
      }, { status: 400 });
    }
    
    if (limit < 1 || limit > 100) {
      return NextResponse.json({ 
        error: 'Invalid limit. Limit must be between 1 and 100.' 
      }, { status: 400 });
    }
    
    // Validate price range
    if (minPrice !== null && minPrice < 0) {
      return NextResponse.json({ 
        error: 'Minimum price cannot be negative.' 
      }, { status: 400 });
    }
    
    if (maxPrice !== null && maxPrice < 0) {
      return NextResponse.json({ 
        error: 'Maximum price cannot be negative.' 
      }, { status: 400 });
    }
    
    if (minPrice !== null && maxPrice !== null && minPrice > maxPrice) {
      return NextResponse.json({ 
        error: 'Minimum price cannot be greater than maximum price.' 
      }, { status: 400 });
    }
    
    // Build WHERE clause
    let whereConditions = [];
    let queryParams = [];
    let paramIndex = 1;
    
    if (category) {
      whereConditions.push("category = ?");
      queryParams.push(category);
      paramIndex++;
    }
    
    if (available !== null) {
      whereConditions.push("available = ?");
      queryParams.push(available);
      paramIndex++;
    }
    
    if (minPrice !== null) {
      whereConditions.push("price >= ?");
      queryParams.push(minPrice);
      paramIndex++;
    }
    
    if (maxPrice !== null) {
      whereConditions.push("price <= ?");
      queryParams.push(maxPrice);
      paramIndex++;
    }
    
    const whereClause = whereConditions.length > 0 ? 'WHERE ' + whereConditions.join(' AND ') : '';
    
    // Get total count
    const countQuery = `SELECT COUNT(*) as total FROM services ${whereClause}`;
    const countResult = await db_query(db, countQuery, queryParams);
    const total = countResult[0].total;
    
    // Calculate offset and total pages
    const offset = (page - 1) * limit;
    const totalPages = Math.ceil(total / limit);
    
    // Get paginated results
    const dataQuery = `
      SELECT id, name, description, duration, price, category, benefits, 
             service_image, available, display_order 
      FROM services 
      ${whereClause} 
      ORDER BY display_order ASC, name ASC 
      LIMIT ? OFFSET ?
    `;
    
    const finalParams = [...queryParams, limit, offset];
    const services = await db_query(db, dataQuery, finalParams);
    
    // Format response data
    const data = services.map(service => ({
      id: service.id,
      name: service.name,
      description: service.description,
      duration: service.duration,
      price: parseFloat(service.price),
      category: service.category,
      benefits: service.benefits,
      service_image: service.service_image,
      available: Boolean(service.available),
      display_order: service.display_order
    }));
    
    const result = {
      data: data,
      total: total,
      page: page,
      limit: limit,
      totalpages: totalPages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona Services List Error:', error);
    return NextResponse.json({ 
      error: 'Failed to retrieve Vitalisona sound healing services. Please try again.' 
    }, { status: 500 });
  }
}

