
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse request body to get id
    const body = await request.json();
    
    // Validate required fields
    if (!body.id) {
      const result = {
        success: false,
        message: "Wellness resource ID is required for Vitalisona system"
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Check if wellness resource exists
    const existingResource = await db_query(db, 
      "SELECT * FROM wellnessresources WHERE id = ?", 
      [body.id]
    );
    
    if (!existingResource || existingResource.length === 0) {
      const result = {
        success: false,
        message: "Wellness resource not found in Vitalisona system"
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    const resource = existingResource[0];
    
    // Check for references in other parts of the application to maintain content integrity
    // Check if the resource title is referenced in session notes
    const sessionReferences = await db_query(db,
      "SELECT COUNT(*) as count FROM sessions WHERE notes LIKE ?",
      [`%${resource.title}%`]
    );
    
    // Check if referenced in wellness journal entries
    const journalReferences = await db_query(db,
      "SELECT COUNT(*) as count FROM wellnessjournal WHERE notes LIKE ? OR session_feedback LIKE ? OR goals LIKE ?",
      [`%${resource.title}%`, `%${resource.title}%`, `%${resource.title}%`]
    );
    
    // Check if referenced in testimonials
    const testimonialReferences = await db_query(db,
      "SELECT COUNT(*) as count FROM testimonials WHERE content LIKE ?",
      [`%${resource.title}%`]
    );
    
    const totalReferences = (sessionReferences[0].count || 0) + (journalReferences[0].count || 0) + (testimonialReferences[0].count || 0);
    
    if (totalReferences > 0) {
      const result = {
        success: false,
        message: "Cannot delete wellness resource as it is currently referenced in other parts of the Vitalisona system. Please remove all references first to maintain content integrity."
      };
      return NextResponse.json(result, { status: 409 });
    }
    
    // Delete the wellness resource
    await db_query(db, 
      "DELETE FROM wellnessresources WHERE id = ?", 
      [body.id]
    );
    
    const result = {
      success: true,
      message: "Wellness resource successfully deleted from Vitalisona system"
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    const result = {
      success: false,
      message: "Error deleting wellness resource from Vitalisona system"
    };
    return NextResponse.json(result, { status: 500 });
  }
}

