
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required input
    if (!id) {
      return NextResponse.json({ error: 'Session ID is required for Vitalisona session retrieval' }, { status: 400 });
    }
    
    // Query session from database with user access control
    const sessionQuery = `
      SELECT id, servicesid, practitionersid, session_date, session_time, 
             duration, status, notes, price, created_at, completed_at
      FROM sessions 
      WHERE id = ? AND userid = ?
    `;
    
    const sessions = await db_query(db, sessionQuery, [id, user_id]);
    
    // Check if session exists and belongs to user
    if (!sessions || sessions.length === 0) {
      return NextResponse.json({ error: 'Session not found or access denied for Vitalisona user' }, { status: 404 });
    }
    
    const session = sessions[0];
    
    // Format response according to output interface
    const result = {
      id: session.id,
      servicesid: session.servicesid,
      practitionersid: session.practitionersid,
      session_date: session.session_date,
      session_time: session.session_time,
      duration: parseInt(session.duration),
      status: session.status,
      notes: session.notes || null,
      price: parseFloat(session.price),
      created_at: session.created_at,
      completed_at: session.completed_at || null
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona SessionsGet API error:', error);
    return NextResponse.json({ error: 'Internal server error retrieving Vitalisona session data' }, { status: 500 });
  }
}

