
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.name || !body.email || !body.subject || !body.message) {
      return NextResponse.json({
        success: false,
        message: "All fields are required"
      }, { status: 400 });
    }
    
    // Validate field types
    if (typeof body.name !== 'string' || typeof body.email !== 'string' || 
        typeof body.subject !== 'string' || typeof body.message !== 'string') {
      return NextResponse.json({
        success: false,
        message: "Invalid field types"
      }, { status: 400 });
    }
    
    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(body.email.trim())) {
      return NextResponse.json({
        success: false,
        message: "Invalid email format"
      }, { status: 400 });
    }
    
    // Basic spam protection - length limits
    if (body.name.trim().length > 100) {
      return NextResponse.json({
        success: false,
        message: "Name is too long (maximum 100 characters)"
      }, { status: 400 });
    }
    
    if (body.subject.trim().length > 200) {
      return NextResponse.json({
        success: false,
        message: "Subject is too long (maximum 200 characters)"
      }, { status: 400 });
    }
    
    if (body.message.trim().length > 2000) {
      return NextResponse.json({
        success: false,
        message: "Message is too long (maximum 2000 characters)"
      }, { status: 400 });
    }
    
    if (body.name.trim().length < 2 || body.subject.trim().length < 5 || body.message.trim().length < 10) {
      return NextResponse.json({
        success: false,
        message: "Fields are too short"
      }, { status: 400 });
    }
    
    // Advanced spam protection - check for excessive repetition
    const messageWords = body.message.toLowerCase().split(/\s+/);
    const wordCount = {};
    for (const word of messageWords) {
      if (word.length > 3) {
        wordCount[word] = (wordCount[word] || 0) + 1;
        if (wordCount[word] > 8) {
          return NextResponse.json({
            success: false,
            message: "Message contains suspicious repetitive content"
          }, { status: 400 });
        }
      }
    }
    
    // Check for suspicious patterns
    const suspiciousPatterns = [
      /(.)\1{10,}/g, // Repeated characters
      /\b(viagra|cialis|pharmacy|casino|lottery|winner|congratulations)\b/gi,
      /\$\d+.*\$\d+/g // Multiple dollar amounts
    ];
    
    const fullText = `${body.name} ${body.subject} ${body.message}`.toLowerCase();
    for (const pattern of suspiciousPatterns) {
      if (pattern.test(fullText)) {
        return NextResponse.json({
          success: false,
          message: "Message contains suspicious content"
        }, { status: 400 });
      }
    }
    
    // Store inquiry in database for follow-up
    const contactId = crypto.randomUUID();
    const currentTime = new Date().toISOString();
    
    await db_query(db, 
      "INSERT INTO contacts (id, name, email, subject, message, status, ip_address, user_agent, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
      [
        contactId, 
        body.name.trim(), 
        body.email.trim().toLowerCase(), 
        body.subject.trim(), 
        body.message.trim(), 
        'new',
        request.headers.get('x-forwarded-for') || 'unknown',
        request.headers.get('user-agent') || 'unknown',
        currentTime, 
        currentTime
      ]
    );
    
    // Send email notification
    const emailApiKey = await window.getKey('SENDGRID_API_KEY');
    if (emailApiKey) {
      try {
        const emailResponse = await fetch('https://api.sendgrid.com/v3/mail/send', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${emailApiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            personalizations: [{
              to: [{ email: 'admin@yoursite.com' }]
            }],
            from: { email: 'noreply@yoursite.com', name: 'Website Contact Form' },
            subject: `New Contact Form Submission: ${body.subject.trim()}`,
            content: [{
              type: 'text/html',
              value: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                  <h2 style="color: #333;">New Contact Form Submission</h2>
                  <div style="background: #f9f9f9; padding: 20px; border-radius: 5px;">
                    <p><strong>Name:</strong> ${body.name.trim()}</p>
                    <p><strong>Email:</strong> ${body.email.trim()}</p>
                    <p><strong>Subject:</strong> ${body.subject.trim()}</p>
                    <p><strong>Message:</strong></p>
                    <div style="background: white; padding: 15px; border-left: 4px solid #007cba;">
                      ${body.message.trim().replace(/\n/g, '<br>')}
                    </div>
                    <p style="margin-top: 20px; color: #666; font-size: 12px;">
                      <strong>Submitted:</strong> ${new Date().toLocaleString()}<br>
                      <strong>Contact ID:</strong> ${contactId}
                    </p>
                  </div>
                </div>
              `
            }]
          })
        });
        
        if (!emailResponse.ok) {
          const errorData = await emailResponse.text();
          console.error('Email notification failed:', errorData);
        }
      } catch (emailError) {
        console.error('Error sending email notification:', emailError);
        // Continue - don't fail the request if email fails, contact was still stored
      }
    }
    
    // Send confirmation email to customer
    if (emailApiKey) {
      try {
        await fetch('https://api.sendgrid.com/v3/mail/send', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${emailApiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            personalizations: [{
              to: [{ email: body.email.trim() }]
            }],
            from: { email: 'noreply@yoursite.com', name: 'Customer Service' },
            subject: 'Thank you for contacting us',
            content: [{
              type: 'text/html',
              value: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                  <h2 style="color: #333;">Thank you for your message!</h2>
                  <p>Dear ${body.name.trim()},</p>
                  <p>We have received your message and will get back to you as soon as possible.</p>
                  <div style="background: #f9f9f9; padding: 15px; border-radius: 5px; margin: 20px 0;">
                    <p><strong>Your message:</strong></p>
                    <p style="font-style: italic;">"${body.message.trim()}"</p>
                  </div>
                  <p>Best regards,<br>Customer Service Team</p>
                </div>
              `
            }]
          })
        });
      } catch (confirmationError) {
        console.error('Error sending confirmation email:', confirmationError);
      }
    }
    
    const result = {
      success: true,
      message: "Thank you for your message. We'll get back to you soon!"
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Contact form submission error:', error);
    
    // Check if it's a database error
    if (error.message && error.message.includes('no such table')) {
      const result = {
        success: false,
        message: "Contact form is currently unavailable. Please try again later."
      };
      return NextResponse.json(result, { status: 500 });
    }
    
    const result = {
      success: false,
      message: "An error occurred while processing your message. Please try again."
    };
    return NextResponse.json(result, { status: 500 });
  }
}

