/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    const body = await request.json();
    
    if (!body.id) {
      return NextResponse.json({ error: 'Image ID is required' }, { status: 400 });
    }
    
    const checkQuery = "SELECT * FROM productimages WHERE id = $1";
    const existingImage = await db_query(db, checkQuery, [body.id]);
    
    if (!existingImage || existingImage.length === 0) {
      return NextResponse.json({ error: 'Product image not found' }, { status: 404 });
    }
    
    const currentImage = existingImage[0];
    
    if (body.is_primary === true && !currentImage.is_primary) {
      const updateOthersQuery = "UPDATE productimages SET is_primary = false WHERE productsid = $1 AND id != $2";
      await db_query(db, updateOthersQuery, [currentImage.productsid, body.id]);
    }
    
    const updateFields = [];
    const queryParams = [];
    let paramIndex = 1;
    
    if (body.image_url !== undefined) {
      updateFields.push("image_url = $" + paramIndex);
      queryParams.push(body.image_url);
      paramIndex++;
    }
    
    if (body.display_order !== undefined) {
      updateFields.push("display_order = $" + paramIndex);
      queryParams.push(body.display_order);
      paramIndex++;
    }
    
    if (body.is_primary !== undefined) {
      updateFields.push("is_primary = $" + paramIndex);
      queryParams.push(body.is_primary);
      paramIndex++;
    }
    
    if (body.caption !== undefined) {
      updateFields.push("caption = $" + paramIndex);
      queryParams.push(body.caption);
      paramIndex++;
    }
    
    if (updateFields.length === 0) {
      const result = {
        id: currentImage.id,
        productsid: currentImage.productsid,
        image_url: currentImage.image_url,
        display_order: currentImage.display_order,
        is_primary: currentImage.is_primary,
        caption: currentImage.caption
      };
      return NextResponse.json(result);
    }
    
    queryParams.push(body.id);
    const updateQuery = "UPDATE productimages SET " + updateFields.join(", ") + " WHERE id = $" + paramIndex;
    
    await db_query(db, updateQuery, queryParams);
    
    const selectQuery = "SELECT * FROM productimages WHERE id = $1";
    const updatedImage = await db_query(db, selectQuery, [body.id]);
    
    const result = {
      id: updatedImage[0].id,
      productsid: updatedImage[0].productsid,
      image_url: updatedImage[0].image_url,
      display_order: updatedImage[0].display_order,
      is_primary: updatedImage[0].is_primary,
      caption: updatedImage[0].caption
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json({ error: 'Failed to update product image', details: error.message }, { status: 500 });
  }
}
