
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.id) {
      return NextResponse.json({ error: 'Vitalisona testimonial ID is required' }, { status: 400 });
    }
    
    // Check if testimonial exists
    const existingTestimonial = await db_query(db, "SELECT * FROM testimonials WHERE id = ?", [body.id]);
    
    if (!existingTestimonial || existingTestimonial.length === 0) {
      return NextResponse.json({ error: 'Vitalisona testimonial not found' }, { status: 404 });
    }
    
    // Prepare update fields
    const updateFields = [];
    const updateParams = [];
    
    if (body.client_name !== undefined) {
      updateFields.push("client_name = ?");
      updateParams.push(body.client_name);
    }
    
    if (body.content !== undefined) {
      updateFields.push("content = ?");
      updateParams.push(body.content);
    }
    
    if (body.rating !== undefined) {
      if (typeof body.rating !== 'number' || body.rating < 1 || body.rating > 5) {
        return NextResponse.json({ error: 'Vitalisona testimonial rating must be a number between 1 and 5' }, { status: 400 });
      }
      updateFields.push("rating = ?");
      updateParams.push(body.rating);
    }
    
    if (body.service_name !== undefined) {
      updateFields.push("service_name = ?");
      updateParams.push(body.service_name);
    }
    
    if (body.date_given !== undefined) {
      updateFields.push("date_given = ?");
      updateParams.push(body.date_given);
    }
    
    if (body.featured !== undefined) {
      updateFields.push("featured = ?");
      updateParams.push(body.featured);
    }
    
    if (body.approved !== undefined) {
      updateFields.push("approved = ?");
      updateParams.push(body.approved);
    }
    
    if (body.client_photo !== undefined) {
      if (body.client_photo) {
        // Store the image file
        const imageRef = await store_file('client_photo.jpg', body.client_photo, true);
        updateFields.push("client_photo = ?");
        updateParams.push(imageRef);
      } else {
        // Clear the photo
        updateFields.push("client_photo = ?");
        updateParams.push(null);
      }
    }
    
    if (body.display_order !== undefined) {
      if (typeof body.display_order !== 'number') {
        return NextResponse.json({ error: 'Vitalisona testimonial display order must be a number' }, { status: 400 });
      }
      updateFields.push("display_order = ?");
      updateParams.push(body.display_order);
    }
    
    // If no fields to update, return current testimonial
    if (updateFields.length === 0) {
      const result = {
        id: existingTestimonial[0].id,
        client_name: existingTestimonial[0].client_name,
        content: existingTestimonial[0].content,
        rating: existingTestimonial[0].rating,
        service_name: existingTestimonial[0].service_name,
        date_given: existingTestimonial[0].date_given,
        featured: existingTestimonial[0].featured,
        approved: existingTestimonial[0].approved,
        client_photo: existingTestimonial[0].client_photo,
        display_order: existingTestimonial[0].display_order
      };
      return NextResponse.json(result);
    }
    
    // Build and execute update query
    const updateQuery = `UPDATE testimonials SET ${updateFields.join(', ')} WHERE id = ?`;
    updateParams.push(body.id);
    
    await db_query(db, updateQuery, updateParams);
    
    // Get the updated testimonial
    const updatedTestimonial = await db_query(db, "SELECT * FROM testimonials WHERE id = ?", [body.id]);
    
    const result = {
      id: updatedTestimonial[0].id,
      client_name: updatedTestimonial[0].client_name,
      content: updatedTestimonial[0].content,
      rating: updatedTestimonial[0].rating,
      service_name: updatedTestimonial[0].service_name,
      date_given: updatedTestimonial[0].date_given,
      featured: updatedTestimonial[0].featured,
      approved: updatedTestimonial[0].approved,
      client_photo: updatedTestimonial[0].client_photo,
      display_order: updatedTestimonial[0].display_order
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona testimonial update error:', error);
    return NextResponse.json({ error: 'Failed to update Vitalisona testimonial' }, { status: 500 });
  }
}

