
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import HeaderView from '@/views/Header';
import CheckoutProcessView from '@/views/Checkout_Process';
import FooterView from '@/views/Footer';

export const metadata: Metadata = {
    title: 'Checkout',
    description: 'Complete purchase with shipping and payment information',
    openGraph: {
        title: 'Checkout',
        description: 'Complete purchase with shipping and payment information',
        url: '/checkout',
        siteName: 'Eloise Co'
    },
};

export default  function checkout() {
    
    return (
        <div className="page" style={{ minHeight: '75vh' }}>
            <main>
                
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ paddingLeft: '5px', paddingRight: '10px', paddingTop: '2px', maxHeight: '100px', display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <HeaderView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <CheckoutProcessView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ paddingLeft: '5px', paddingRight: '10px', paddingTop: '25px', paddingBottom: '2px', display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <FooterView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
            </main>
        </div>
    );
}