/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    const body = await request.json();
    
    // Validate required input
    if (!body.id) {
      const result = {
        success: false,
        message: 'Category ID is required'
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    const categoryId = body.id;
    
    // Check if category exists
    const categoryCheck = await db_query(
      db,
      'SELECT id, name FROM categories WHERE id = $1',
      [categoryId]
    );
    
    if (!categoryCheck || categoryCheck.length === 0) {
      const result = {
        success: false,
        message: 'Category not found in Victorian Era catalog'
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    const categoryName = categoryCheck[0].name;
    
    // Check if category has associated products
    const productCheck = await db_query(
      db,
      'SELECT COUNT(*) as count FROM products WHERE categoriesid = $1',
      [categoryId]
    );
    
    const productCount = parseInt(productCheck[0].count);
    
    if (productCount > 0) {
      const result = {
        success: false,
        message: `Cannot delete category "${categoryName}". This Victorian Era category has ${productCount} associated product${productCount > 1 ? 's' : ''}. Please remove or reassign the products before deleting the category.`
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Delete the category
    await db_query(
      db,
      'DELETE FROM categories WHERE id = $1',
      [categoryId]
    );
    
    const result = {
      success: true,
      message: `Category "${categoryName}" has been successfully deleted from Victorian Era catalog`
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    const result = {
      success: false,
      message: 'An error occurred while deleting the category from Victorian Era catalog'
    };
    return NextResponse.json(result, { status: 500 });
  }
}
