
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse request to get category ID
    const { searchParams } = new URL(request.url);
    let categoryId = searchParams.get('id');
    
    // If not in query params, try request body
    if (!categoryId) {
      try {
        const body = await request.json();
        categoryId = body.id;
      } catch (e) {
        // If no JSON body, that's fine, we'll check for missing ID below
      }
    }
    
    // Validate required fields
    if (!categoryId) {
      const result = {
        success: false,
        message: 'Category ID is required'
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Check if category exists
    const categoryCheck = await db_query(db, 
      "SELECT id FROM categories WHERE id = ?", 
      [categoryId]
    );
    
    if (categoryCheck.length === 0) {
      const result = {
        success: false,
        message: 'Category not found'
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    // Check if any dresses are associated with this category
    const associatedDresses = await db_query(db, 
      "SELECT id FROM dresses WHERE categoriesid = ?", 
      [categoryId]
    );
    
    if (associatedDresses.length > 0) {
      const result = {
        success: false,
        message: 'Cannot delete category. There are dresses associated with this category.'
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Delete the category
    await db_query(db, 
      "DELETE FROM categories WHERE id = ?", 
      [categoryId]
    );
    
    const result = {
      success: true,
      message: 'Category deleted successfully'
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    const result = {
      success: false,
      message: 'Internal server error'
    };
    return NextResponse.json(result, { status: 500 });
  }
}

