
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import List from '@/components/list';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Employer Profiles',
    description: 'List of EmployerProfile',
    openGraph: {
        title: 'Employer Profiles',
        description: 'List of EmployerProfile',
        url: '/employerprofile_list',
        siteName: 'Job Board'
    },
};

export default  function employerprofile_list() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Employer Profiles","link":"/employerprofile_list"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <List
                                modelName="EmployerProfile"
                                showAdminFeatures={true}
                                nameField="company_name"
                                 
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}