/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    const body = await request.json();
    
    if (!body.id) {
      return NextResponse.json({ error: 'Order ID is required' }, { status: 400 });
    }
    
    const currentOrderResult = await db_query(db, 
      "SELECT * FROM orders WHERE id = $1",
      [body.id]
    );
    
    if (!currentOrderResult || currentOrderResult.length === 0) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }
    
    const currentOrder = currentOrderResult[0];
    
    if (body.status && body.status !== currentOrder.status) {
      const validTransitions = {
        'pending': ['processing'],
        'processing': ['shipped'],
        'shipped': ['delivered'],
        'delivered': []
      };
      
      const currentStatus = currentOrder.status.toLowerCase();
      const newStatus = body.status.toLowerCase();
      const allowedNextStatuses = validTransitions[currentStatus] || [];
      
      if (!allowedNextStatuses.includes(newStatus)) {
        return NextResponse.json({ 
          error: `Invalid status transition from ${currentStatus} to ${newStatus}. Valid transitions: ${allowedNextStatuses.join(', ') || 'none'}` 
        }, { status: 400 });
      }
    }
    
    const updateFields = [];
    const updateParams = [];
    let paramIndex = 1;
    
    if (body.status !== undefined) {
      updateFields.push("status = $" + paramIndex);
      updateParams.push(body.status);
      paramIndex++;
    }
    
    if (body.payment_status !== undefined) {
      updateFields.push("payment_status = $" + paramIndex);
      updateParams.push(body.payment_status);
      paramIndex++;
    }
    
    if (body.tracking_number !== undefined) {
      updateFields.push("tracking_number = $" + paramIndex);
      updateParams.push(body.tracking_number);
      paramIndex++;
    }
    
    if (body.notes !== undefined) {
      updateFields.push("notes = $" + paramIndex);
      updateParams.push(body.notes);
      paramIndex++;
    }
    
    if (updateFields.length === 0) {
      return NextResponse.json({ error: 'No fields to update' }, { status: 400 });
    }
    
    updateParams.push(body.id);
    const updateQuery = "UPDATE orders SET " + updateFields.join(', ') + " WHERE id = $" + paramIndex;
    await db_query(db, updateQuery, updateParams);
    
    if (body.status && body.status !== currentOrder.status) {
      try {
        const emailApiKey = process.env.EMAIL_API_KEY;
        const emailApiUrl = process.env.EMAIL_API_URL;
        
        if (emailApiKey && emailApiUrl) {
          let emailSubject = '';
          let emailMessage = '';
          
          if (body.status.toLowerCase() === 'shipped') {
            emailSubject = `Order ${currentOrder.order_number} has been shipped`;
            emailMessage = `Your order ${currentOrder.order_number} has been shipped`;
            if (body.tracking_number) {
              emailMessage += ` with tracking number: ${body.tracking_number}`;
            }
          } else if (body.status.toLowerCase() === 'delivered') {
            emailSubject = `Order ${currentOrder.order_number} has been delivered`;
            emailMessage = `Your order ${currentOrder.order_number} has been delivered. Thank you for your purchase!`;
          } else if (body.status.toLowerCase() === 'processing') {
            emailSubject = `Order ${currentOrder.order_number} is being processed`;
            emailMessage = `Your order ${currentOrder.order_number} is now being processed and will be shipped soon.`;
          }
          
          const userResult = await db_query(db, 
            "SELECT email, name FROM users WHERE id = $1",
            [currentOrder.userid]
          );
          
          if (userResult && userResult.length > 0 && emailSubject) {
            const user = userResult[0];
            
            await fetch(emailApiUrl, {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${emailApiKey}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                to: user.email,
                subject: emailSubject,
                text: emailMessage,
                html: `<p>${emailMessage}</p>`
              })
            });
          }
        }
      } catch (emailError) {
        console.error('Email notification failed:', emailError);
      }
    }
    
    const orderResult = await db_query(db,
      "SELECT * FROM orders WHERE id = $1",
      [body.id]
    );
    
    const order = orderResult[0];
    
    const itemsQuery = `
      SELECT 
        oi.id,
        oi.productsid,
        oi.product_name,
        oi.quantity,
        oi.unit_price,
        oi.total_price,
        oi.size,
        oi.color,
        pi.image_url as product_image_url
      FROM orderitems oi
      LEFT JOIN products p ON oi.productsid = p.id
      LEFT JOIN productimages pi ON p.id = pi.productsid AND pi.is_primary = true
      WHERE oi.ordersid = $1
      ORDER BY oi.id
    `;
    
    const itemsResult = await db_query(db, itemsQuery, [body.id]);
    
    const items = itemsResult.map(item => ({
      id: item.id,
      productsid: item.productsid,
      product_name: item.product_name,
      quantity: item.quantity,
      unit_price: item.unit_price,
      total_price: item.total_price,
      size: item.size || null,
      color: item.color || null,
      product_image_url: item.product_image_url || null
    }));
    
    const result = {
      id: order.id,
      order_number: order.order_number,
      order_date: order.order_date,
      status: order.status,
      subtotal: order.subtotal,
      tax: order.tax,
      shipping_cost: order.shipping_cost,
      total: order.total,
      payment_method: order.payment_method || null,
      payment_status: order.payment_status,
      transaction_id: order.transaction_id || null,
      shipping_name: order.shipping_name,
      shipping_address_line1: order.shipping_address_line1,
      shipping_address_line2: order.shipping_address_line2 || null,
      shipping_city: order.shipping_city,
      shipping_state: order.shipping_state,
      shipping_postal_code: order.shipping_postal_code,
      shipping_country: order.shipping_country,
      tracking_number: order.tracking_number || null,
      notes: order.notes || null,
      items: items
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Order update error:', error);
    return NextResponse.json({ error: 'Failed to update order' }, { status: 500 });
  }
}
