
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    if (!body.id) {
      return NextResponse.json({ error: 'Order ID is required' }, { status: 400 });
    }
    
    // Check if order exists
    const existingOrder = await db_query(db, "SELECT * FROM orders WHERE id = ?", [body.id]);
    
    if (!existingOrder || existingOrder.length === 0) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }
    
    // Build dynamic update query
    const updateFields = [];
    const updateParams = [];
    
    if (body.status !== undefined) {
      updateFields.push("status = ?");
      updateParams.push(body.status);
      
      // Handle automatic timestamps based on status
      if (body.status === 'shipped' && !existingOrder[0].shipped_at) {
        updateFields.push("shipped_at = ?");
        updateParams.push(new Date().toISOString());
      }
      
      if (body.status === 'delivered' && !existingOrder[0].delivered_at) {
        updateFields.push("delivered_at = ?");
        updateParams.push(new Date().toISOString());
      }
    }
    
    if (body.payment_status !== undefined) {
      updateFields.push("payment_status = ?");
      updateParams.push(body.payment_status);
    }
    
    if (body.tracking_number !== undefined) {
      updateFields.push("tracking_number = ?");
      updateParams.push(body.tracking_number);
    }
    
    if (body.notes !== undefined) {
      updateFields.push("notes = ?");
      updateParams.push(body.notes);
    }
    
    // Always update the updated_at timestamp
    updateFields.push("updated_at = ?");
    updateParams.push(new Date().toISOString());
    
    if (updateFields.length > 1) { // More than just updated_at
      // Update the order
      const updateQuery = `UPDATE orders SET ${updateFields.join(', ')} WHERE id = ?`;
      updateParams.push(body.id);
      
      await db_query(db, updateQuery, updateParams);
    }
    
    // Fetch the updated order
    const updatedOrder = await db_query(db, "SELECT * FROM orders WHERE id = ?", [body.id]);
    
    if (!updatedOrder || updatedOrder.length === 0) {
      return NextResponse.json({ error: 'Failed to fetch updated order' }, { status: 500 });
    }
    
    const order = updatedOrder[0];
    
    // Fetch order items with dress information
    const orderItemsQuery = `
      SELECT 
        oi.*,
        d.name as dress_name,
        di.image_url as dress_image
      FROM orderitems oi
      LEFT JOIN dresses d ON oi.dressesid = d.id
      LEFT JOIN dressimages di ON d.id = di.dressesid AND di.is_primary = 1
      WHERE oi.ordersid = ?
      ORDER BY oi.created_at ASC
    `;
    
    const orderItems = await db_query(db, orderItemsQuery, [body.id]);
    
    // Format the order items
    const formattedOrderItems = orderItems.map(item => ({
      id: item.id,
      ordersid: item.ordersid,
      dressesid: item.dressesid,
      quantity: item.quantity,
      size: item.size,
      color: item.color,
      price_at_time: parseFloat(item.price_at_time),
      line_total: parseFloat(item.line_total),
      dress_name: item.dress_name,
      dress_image: item.dress_image,
      created_at: item.created_at
    }));
    
    // Parse JSON fields
    let shippingAddress = {};
    let billingAddress = {};
    
    try {
      shippingAddress = JSON.parse(order.shipping_address || '{}');
    } catch (e) {
      shippingAddress = {};
    }
    
    try {
      billingAddress = JSON.parse(order.billing_address || '{}');
    } catch (e) {
      billingAddress = {};
    }
    
    // Format the complete response
    const result = {
      id: order.id,
      order_number: order.order_number,
      status: order.status,
      subtotal: parseFloat(order.subtotal),
      tax_amount: parseFloat(order.tax_amount),
      shipping_amount: parseFloat(order.shipping_amount),
      total_amount: parseFloat(order.total_amount),
      currency: order.currency,
      payment_status: order.payment_status,
      payment_method: order.payment_method,
      shipping_address: shippingAddress,
      billing_address: billingAddress,
      notes: order.notes,
      tracking_number: order.tracking_number,
      shipped_at: order.shipped_at,
      delivered_at: order.delivered_at,
      order_items: formattedOrderItems,
      created_at: order.created_at,
      updated_at: order.updated_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error updating order:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

