
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  // Parse query parameters
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');
  
  // Validate required fields
  if (!id) {
    return NextResponse.json({ error: 'Order item ID is required' }, { status: 400 });
  }
  
  try {
    // Query orderitem with join to orders to ensure user owns the order
    const query = `
      SELECT oi.id, oi.ordersid, oi.dressesid, oi.quantity, oi.size, oi.color, 
             oi.price_at_time, oi.line_total, oi.created_at
      FROM orderitems oi
      INNER JOIN orders o ON oi.ordersid = o.id
      WHERE oi.id = ? AND o.userid = ?
    `;
    
    const results = await db_query(db, query, [id, user_id]);
    
    if (results.length === 0) {
      return NextResponse.json({ error: 'Order item not found or access denied' }, { status: 404 });
    }
    
    const orderItem = results[0];
    
    const result = {
      id: orderItem.id,
      ordersid: orderItem.ordersid,
      dressesid: orderItem.dressesid,
      quantity: orderItem.quantity,
      size: orderItem.size,
      color: orderItem.color,
      price_at_time: orderItem.price_at_time,
      line_total: orderItem.line_total,
      created_at: orderItem.created_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json({ error: 'Failed to retrieve order item' }, { status: 500 });
  }
}

