
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import MemberDetails from '@/custom/Member_Details';
import MemberEventRegistrations from '@/custom/Member_Event_Registrations';
import MemberBoardPositions from '@/custom/Member_Board_Positions';
import MemberOwnedLocations from '@/custom/Member_Owned_Locations';

export const metadata: Metadata = {
    title: 'Member  Details',
    description: 'Page for Member Details',
    openGraph: {
        title: 'Member  Details',
        description: 'Page for Member Details',
        url: '/member_details',
        siteName: 'Maryland Christmas'
    },
};

export default  function member_details() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><section className="card">
                            <ErrorBoundary fallback={<Error />}>
                                <MemberDetails />
                            </ErrorBoundary>
                        </section>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><section className="card">
                            <ErrorBoundary fallback={<Error />}>
                                <MemberEventRegistrations />
                            </ErrorBoundary>
                        </section>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><section className="card">
                            <ErrorBoundary fallback={<Error />}>
                                <MemberBoardPositions />
                            </ErrorBoundary>
                        </section>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><section className="card">
                            <ErrorBoundary fallback={<Error />}>
                                <MemberOwnedLocations />
                            </ErrorBoundary>
                        </section>
                        </div>
                    </div>
            </main>
        </div>
    );
}