
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    const { searchParams } = new URL(request.url);
    
    // Parse query parameters
    const search = searchParams.get('search');
    const category_id = searchParams.get('category_id');
    const min_price = searchParams.get('min_price') ? parseFloat(searchParams.get('min_price')) : null;
    const max_price = searchParams.get('max_price') ? parseFloat(searchParams.get('max_price')) : null;
    const sizesParam = searchParams.get('sizes');
    const sizes = sizesParam ? sizesParam.split(',').map(s => s.trim()) : [];
    const colorsParam = searchParams.get('colors');
    const colors = colorsParam ? colorsParam.split(',').map(c => c.trim()) : [];
    const featured = searchParams.get('featured') ? searchParams.get('featured') === 'true' : null;
    const published = searchParams.get('published') ? searchParams.get('published') === 'true' : null;
    const sort = searchParams.get('sort') || 'created_at';
    const page = parseInt(searchParams.get('page')) || 1;
    const limit = parseInt(searchParams.get('limit')) || 20;
    
    // Calculate offset
    const offset = (page - 1) * limit;
    
    // Build WHERE conditions
    let whereConditions = [];
    let queryParams = [];
    let paramIndex = 1;
    
    // Search filter
    if (search) {
      whereConditions.push("(d.name LIKE ? OR d.description LIKE ?)");
      queryParams.push(`%${search}%`);
      queryParams.push(`%${search}%`);
      paramIndex += 2;
    }
    
    // Category filter
    if (category_id) {
      whereConditions.push("d.categoriesid = ?");
      queryParams.push(category_id);
      paramIndex += 1;
    }
    
    // Price range filters
    if (min_price !== null) {
      whereConditions.push("d.price >= ?");
      queryParams.push(min_price);
      paramIndex += 1;
    }
    
    if (max_price !== null) {
      whereConditions.push("d.price <= ?");
      queryParams.push(max_price);
      paramIndex += 1;
    }
    
    // Sizes filter
    if (sizes && sizes.length > 0) {
      const sizeConditions = sizes.map((size) => {
        queryParams.push(`%"${size}"%`);
        return "d.available_sizes LIKE ?";
      });
      whereConditions.push(`(${sizeConditions.join(' OR ')})`);
      paramIndex += sizes.length;
    }
    
    // Colors filter
    if (colors && colors.length > 0) {
      const colorConditions = colors.map((color) => {
        queryParams.push(`%"${color}"%`);
        return "d.available_colors LIKE ?";
      });
      whereConditions.push(`(${colorConditions.join(' OR ')})`);
      paramIndex += colors.length;
    }
    
    // Featured filter
    if (featured !== null) {
      whereConditions.push("d.featured = ?");
      queryParams.push(featured);
      paramIndex += 1;
    }
    
    // Published filter
    if (published !== null) {
      whereConditions.push("d.published = ?");
      queryParams.push(published);
      paramIndex += 1;
    }
    
    // Stock availability filter (only show in-stock items)
    whereConditions.push("d.stock_quantity > 0");
    
    // Build WHERE clause
    const whereClause = whereConditions.length > 0 ? `WHERE ${whereConditions.join(' AND ')}` : '';
    
    // Determine sort order
    let orderBy = 'ORDER BY d.created_at DESC';
    switch (sort) {
      case 'name':
        orderBy = 'ORDER BY d.name ASC';
        break;
      case 'price_low':
        orderBy = 'ORDER BY d.price ASC';
        break;
      case 'price_high':
        orderBy = 'ORDER BY d.price DESC';
        break;
      case 'featured':
        orderBy = 'ORDER BY d.featured DESC, d.created_at DESC';
        break;
      case 'updated_at':
        orderBy = 'ORDER BY d.updated_at DESC';
        break;
    }
    
    // Build main query with JOIN to get primary image
    const query = `
      SELECT 
        d.id,
        d.categoriesid,
        d.name,
        d.slug,
        d.description,
        d.price,
        d.compare_at_price,
        d.sku,
        d.stock_quantity,
        d.available_sizes,
        d.available_colors,
        d.material,
        d.care_instructions,
        d.featured,
        d.published,
        d.created_at,
        d.updated_at,
        di.image_url as primary_image
      FROM dresses d
      LEFT JOIN dressimages di ON d.id = di.dressesid AND di.is_primary = 1
      ${whereClause}
      ${orderBy}
      LIMIT ? OFFSET ?
    `;
    
    // Execute main query
    const finalParams = [...queryParams, limit, offset];
    const dresses = await db_query(db, query, finalParams);
    
    // Get total count for pagination
    const countQuery = `
      SELECT COUNT(*) as total
      FROM dresses d
      ${whereClause}
    `;
    
    const countResult = await db_query(db, countQuery, queryParams);
    const total = countResult[0].total;
    const totalpages = Math.ceil(total / limit);
    
    // Format response data
    const data = dresses.map(dress => ({
      id: dress.id,
      categoriesid: dress.categoriesid,
      name: dress.name,
      slug: dress.slug,
      description: dress.description,
      price: dress.price,
      compare_at_price: dress.compare_at_price,
      sku: dress.sku,
      stock_quantity: dress.stock_quantity,
      available_sizes: JSON.parse(dress.available_sizes || '[]'),
      available_colors: JSON.parse(dress.available_colors || '[]'),
      material: dress.material,
      care_instructions: dress.care_instructions,
      featured: dress.featured,
      published: dress.published,
      primary_image: dress.primary_image,
      created_at: dress.created_at,
      updated_at: dress.updated_at
    }));
    
    const result = {
      data: data,
      total: total,
      page: page,
      limit: limit,
      totalpages: totalpages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error fetching dresses:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve dresses' },
      { status: 500 }
    );
  }
}

