/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse request parameters
    const url = new URL(request.url);
    const searchParams = url.searchParams;
    const id = searchParams.get('id');
    
    // Validate required fields
    if (!id) {
      const result = {
        success: false,
        message: 'Testimonial ID is required for deletion'
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Check if testimonial exists
    const existingTestimonial = await db_query(db, 
      "SELECT id, client_name FROM testimonials WHERE id = ?", 
      [id]
    );
    
    if (!existingTestimonial || existingTestimonial.length === 0) {
      const result = {
        success: false,
        message: 'Testimonial not found in Vitalisona system'
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    // Delete the testimonial from the system
    await db_query(db, "DELETE FROM testimonials WHERE id = ?", [id]);
    
    const result = {
      success: true,
      message: `Testimonial from ${existingTestimonial[0].client_name} has been successfully deleted from Vitalisona system`
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    const result = {
      success: false,
      message: 'An error occurred while deleting the testimonial from Vitalisona system'
    };
    
    return NextResponse.json(result, { status: 500 });
  }
}
