/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse and validate request parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required field
    if (!id) {
      return NextResponse.json(
        { error: 'Product ID is required' },
        { status: 400 }
      );
    }
    
    // Query product with category information
    const productQuery = `
      SELECT 
        p.id,
        p.categoriesid,
        p.name,
        p.description,
        p.price,
        p.sku,
        p.stock_quantity,
        p.size,
        p.color,
        p.material,
        p.era_period,
        p.care_instructions,
        p.available,
        p.featured,
        c.name as category_name
      FROM products p
      LEFT JOIN categories c ON p.categoriesid = c.id
      WHERE p.id = $1
    `;
    
    const productResult = await db_query(db, productQuery, [id]);
    
    // Check if product exists
    if (!productResult || productResult.length === 0) {
      return NextResponse.json(
        { error: 'Product not found in Victorian Era catalog' },
        { status: 404 }
      );
    }
    
    const product = productResult[0];
    
    // Query product images
    const imagesQuery = `
      SELECT 
        id,
        image_url,
        display_order,
        is_primary,
        caption
      FROM productimages
      WHERE productsid = $1
      ORDER BY display_order
    `;
    
    const imagesResult = await db_query(db, imagesQuery, [id]);
    
    // Format images array according to output interface
    const images = imagesResult.map(img => ({
      id: img.id,
      image_url: img.image_url,
      display_order: img.display_order,
      is_primary: img.is_primary,
      caption: img.caption
    }));
    
    // Format result according to output interface
    const result = {
      id: product.id,
      categoriesid: product.categoriesid,
      category_name: product.category_name,
      name: product.name,
      description: product.description,
      price: parseFloat(product.price),
      sku: product.sku,
      stock_quantity: product.stock_quantity,
      size: product.size,
      color: product.color,
      material: product.material,
      era_period: product.era_period,
      care_instructions: product.care_instructions,
      available: product.available,
      featured: product.featured,
      images: images
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Victorian Era ProductsGet API Error:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve product information' },
      { status: 500 }
    );
  }
}
