
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  let result;
  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.type) {
      return NextResponse.json({ error: 'Missing required field: type' }, { status: 400 });
    }
    if (!body.first_name) {
      return NextResponse.json({ error: 'Missing required field: first_name' }, { status: 400 });
    }
    if (!body.last_name) {
      return NextResponse.json({ error: 'Missing required field: last_name' }, { status: 400 });
    }
    if (!body.address_line_1) {
      return NextResponse.json({ error: 'Missing required field: address_line_1' }, { status: 400 });
    }
    if (!body.city) {
      return NextResponse.json({ error: 'Missing required field: city' }, { status: 400 });
    }
    if (!body.state_province) {
      return NextResponse.json({ error: 'Missing required field: state_province' }, { status: 400 });
    }
    if (!body.postal_code) {
      return NextResponse.json({ error: 'Missing required field: postal_code' }, { status: 400 });
    }
    if (!body.country) {
      return NextResponse.json({ error: 'Missing required field: country' }, { status: 400 });
    }
    if (typeof body.is_default !== 'boolean') {
      return NextResponse.json({ error: 'Missing or invalid required field: is_default' }, { status: 400 });
    }
    
    // Generate ID and timestamps
    const addressId = crypto.randomUUID();
    const now = new Date().toISOString();
    
    // Handle default address management
    if (body.is_default) {
      // Set all existing addresses for this user to non-default
      await db_query(db, 
        "UPDATE addresses SET is_default = false WHERE userid = ?", 
        [user_id]
      );
    }
    
    // Insert new address
    await db_query(db, 
      "INSERT INTO addresses (id, userid, type, first_name, last_name, company, address_line_1, address_line_2, city, state_province, postal_code, country, phone, is_default, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
      [
        addressId,
        user_id,
        body.type,
        body.first_name,
        body.last_name,
        body.company || null,
        body.address_line_1,
        body.address_line_2 || null,
        body.city,
        body.state_province,
        body.postal_code,
        body.country,
        body.phone || null,
        body.is_default,
        now,
        now
      ]
    );
    
    // Prepare result matching output interface
    result = {
      id: addressId,
      type: body.type,
      first_name: body.first_name,
      last_name: body.last_name,
      company: body.company || null,
      address_line_1: body.address_line_1,
      address_line_2: body.address_line_2 || null,
      city: body.city,
      state_province: body.state_province,
      postal_code: body.postal_code,
      country: body.country,
      phone: body.phone || null,
      is_default: body.is_default,
      created_at: now,
      updated_at: now
    };
    
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create address' }, { status: 500 });
  }
  
  return NextResponse.json(result);
}

