
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import List from '@/components/list';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Job Locations',
    description: 'List of JobLocation',
    openGraph: {
        title: 'Job Locations',
        description: 'List of JobLocation',
        url: '/joblocation_list',
        siteName: 'Job Board'
    },
};

export default  function joblocation_list() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Job Locations","link":"/joblocation_list"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <List
                                modelName="JobLocation"
                                showAdminFeatures={true}
                                nameField="location_name"
                                 
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}