
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { db_add, db_update, db_select, db_delete, db_init } from '../../../database/supabase';
export async function GET(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const ids = searchParams.get('ids')?.split(',') || [];
  const eventId = searchParams.get('eventId');
  const memberId = searchParams.get('memberId');
  const status = searchParams.get('status');
  
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

  
  if (!user_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  
  const whereConditions = [
    { field: 'UserID', op: '=', value: user_id }
  ];
  
  if (eventId) {
    whereConditions.push({ field: 'EventsID', op: '=', value: eventId });
  }
  
  if (memberId) {
    whereConditions.push({ field: 'MembersID', op: '=', value: memberId });
  }
  
  if (status) {
    whereConditions.push({ field: 'status', op: '=', value: status });
  }
  
  const result = await db_select(
    db,
    'EventRegistrations',
    ['ID', 'EventsID', 'MembersID', 'registration_date', 'status', 'UserID'],
    ids.length > 0 ? ids : undefined,
    whereConditions
  );
  
  return NextResponse.json(result);
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

  
  if (!user_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  
  try {
    const requestData = await request.json();
    
    // Validate required fields
    if (!requestData.EventsID || !requestData.MembersID || !requestData.registration_date || !requestData.status) {
      return NextResponse.json(
        { error: 'Missing required fields. EventsID, MembersID, registration_date, and status are required.' },
        { status: 400 }
      );
    }
    
    // Create new registration with UUID and user ID
    const newRegistration = {
      ID: crypto.randomUUID(),
      EventsID: requestData.EventsID,
      MembersID: requestData.MembersID,
      registration_date: requestData.registration_date,
      status: requestData.status,
      UserID: user_id
    };
    
    const result = await db_add(db, 'EventRegistrations', newRegistration);
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create registration' }, { status: 500 });
  }
}

export async function PUT(request: NextRequest): Promise<NextResponse> {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

  
  if (!user_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  
  try {
    const requestData = await request.json();
    
    // Validate required fields
    if (!requestData.ID || !requestData.EventsID || !requestData.MembersID || 
        !requestData.registration_date || !requestData.status) {
      return NextResponse.json(
        { error: 'Missing required fields. ID, EventsID, MembersID, registration_date, and status are required.' },
        { status: 400 }
      );
    }
    
    // Check if the registration belongs to the user
    const existingRegistration = await db_select(
      db,
      'EventRegistrations',
      ['ID'],
      [requestData.ID],
      [{ field: 'UserID', op: '=', value: user_id }]
    );
    
    if (!existingRegistration || existingRegistration.length === 0) {
      return NextResponse.json({ error: 'Registration not found or access denied' }, { status: 404 });
    }
    
    // Update the registration
    const updateData = {
      EventsID: requestData.EventsID,
      MembersID: requestData.MembersID,
      registration_date: requestData.registration_date,
      status: requestData.status,
      UserID: user_id
    };
    
    const result = await db_update(
      db,
      'EventRegistrations',
      updateData,
      [requestData.ID],
      [{ field: 'UserID', op: '=', value: user_id }]
    );
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to update registration' }, { status: 500 });
  }
}

export async function DELETE(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');
  
  if (!id) {
    return NextResponse.json({ error: 'Registration ID is required' }, { status: 400 });
  }
  
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  if (!user_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  
  try {
    // Check if the registration belongs to the user
    const existingRegistration = await db_select(
      db,
      'EventRegistrations',
      ['ID'],
      [id],
      [{ field: 'UserID', op: '=', value: user_id }]
    );
    
    if (!existingRegistration || existingRegistration.length === 0) {
      return NextResponse.json({ error: 'Registration not found or access denied' }, { status: 404 });
    }
    
    // Delete the registration
    const result = await db_delete(db, 'EventRegistrations', [id]);
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to delete registration' }, { status: 500 });
  }
}

