
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  // Initialize database connection
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    
    const dress_id = searchParams.get('dress_id');
    const sort = searchParams.get('sort') || 'display_order';
    const page = parseInt(searchParams.get('page')) || 1;
    const limit = parseInt(searchParams.get('limit')) || 50;
    
    // Validate inputs
    if (page < 1) {
      return NextResponse.json({ error: 'Page must be greater than 0' }, { status: 400 });
    }
    
    if (limit < 1 || limit > 100) {
      return NextResponse.json({ error: 'Limit must be between 1 and 100' }, { status: 400 });
    }
    
    // Build base query - using lowercase table and field names
    let query = "SELECT id, dressesid, image_url, alt_text, display_order, is_primary, created_at FROM dressimages";
    let countQuery = "SELECT COUNT(*) as total FROM dressimages";
    let whereConditions = [];
    let queryParams = [];
    
    // Add dress_id filter if provided
    if (dress_id) {
      whereConditions.push("dressesid = ?");
      queryParams.push(dress_id);
    }
    
    // Add WHERE clause if conditions exist
    if (whereConditions.length > 0) {
      const whereClause = " WHERE " + whereConditions.join(' AND ');
      query += whereClause;
      countQuery += whereClause;
    }
    
    // Add ORDER BY clause
    let orderBy = " ORDER BY ";
    switch(sort) {
      case 'display_order_desc':
        orderBy += "display_order DESC";
        break;
      case 'is_primary':
        orderBy += "is_primary DESC, display_order ASC";
        break;
      case 'created_at':
        orderBy += "created_at DESC";
        break;
      case 'created_at_desc':
        orderBy += "created_at ASC";
        break;
      case 'display_order':
      default:
        orderBy += "display_order ASC";
        break;
    }
    query += orderBy;
    
    // Add pagination
    const offset = (page - 1) * limit;
    query += " LIMIT ? OFFSET ?";
    
    // Execute queries
    const finalParams = [...queryParams, limit, offset];
    const finalCountParams = [...queryParams];
    
    const images = await db_query(db, query, finalParams);
    const countResult = await db_query(db, countQuery, finalCountParams);
    
    const total = countResult[0].total;
    const totalpages = Math.ceil(total / limit);
    
    // Format results
    const data = images.map(image => ({
      id: image.id,
      dressesid: image.dressesid,
      image_url: image.image_url,
      alt_text: image.alt_text,
      display_order: image.display_order,
      is_primary: Boolean(image.is_primary),
      created_at: image.created_at
    }));
    
    const result = {
      data: data,
      total: total,
      page: page,
      limit: limit,
      totalpages: totalpages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error fetching dress images:', error);
    return NextResponse.json({ error: 'Failed to fetch dress images' }, { status: 500 });
  }
}

