/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required input
    if (!id) {
      return NextResponse.json(
        { error: 'Victorian Era: Category ID is required' }, 
        { status: 400 }
      );
    }
    
    // Query database for the category
    const query = "SELECT id, name, description, image_url, display_order, visible FROM categories WHERE id = $1";
    const rows = await db_query(db, query, [id]);
    
    // Check if category exists
    if (rows.length === 0) {
      return NextResponse.json(
        { error: 'Victorian Era: Category not found' }, 
        { status: 404 }
      );
    }
    
    // Format the result
    const category = rows[0];
    const result = {
      id: category.id,
      name: category.name,
      description: category.description || null,
      image_url: category.image_url || null,
      display_order: category.display_order || null,
      visible: category.visible
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Victorian Era: Failed to retrieve category', details: error.message }, 
      { status: 500 }
    );
  }
}
