
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required fields
    if (!id) {
      return NextResponse.json(
        { error: 'Category ID is required' }, 
        { status: 400 }
      );
    }
    
    // Query the database for the category
    const categories = await db_query(
      db, 
      "SELECT * FROM categories WHERE id = ?", 
      [id]
    );
    
    // Check if category exists
    if (!categories || categories.length === 0) {
      return NextResponse.json(
        { error: 'Category not found' }, 
        { status: 404 }
      );
    }
    
    const category = categories[0];
    
    // Format the response according to output interface
    const result = {
      id: category.id,
      name: category.name,
      slug: category.slug,
      description: category.description,
      image_url: category.image_url,
      display_order: category.display_order,
      published: category.published,
      created_at: category.created_at,
      updated_at: category.updated_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error fetching category:', error);
    return NextResponse.json(
      { error: 'Internal server error' }, 
      { status: 500 }
    );
  }
}

