
/*
SysArchitect v1.0.0
WARNING: This file is automatically generated and should not be modified.
*/


import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface AuthState {
  nonce: string | null;
  provider: string | null;
  setNonce: (nonce: string) => void;
  setProvider: (provider: string) => void;
  clearAuth: () => void;
}

export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      nonce: null,
      provider: null,
      setNonce: (nonce) => set({ nonce }),
      setProvider: (provider) => set({ provider }),
      clearAuth: () => set({ nonce: null, provider: null }),
    }),
    {
      name: 'auth-storage',
    }
  )
);
