
/*
SysArchitect v1.0.0
WARNING: This file is automatically generated and should not be modified.
*/


import { create } from 'zustand';

interface UserState {
  userName: string;
  avatarURL: string;
  isAuthenticated: boolean;
  userLevel: string;
  setUserName: (userName: string) => void;
  setAvatarURL: (avatarURL: string) => void;
  setIsAuthenticated: (isAuthenticated: boolean) => void;
  setUserLevel: (level: string) => void;
  clearUser: () => void;
}

export const useUserStore = create<UserState>()((set) => ({
  userName: '',
  avatarURL: '',
  isAuthenticated: false,
  userLevel: '',
  setUserName: (userName: string) => set({ userName: userName }),
  setAvatarURL: (avatarURL: string) => set({ avatarURL: avatarURL }),
  setIsAuthenticated: (isAuthenticated: boolean) => set({ isAuthenticated: isAuthenticated }),
  setUserLevel: (level: string) => set({ userLevel: level }),
  clearUser: () => set({ isAuthenticated: false, userLevel: '0' }),
}));