
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const status = searchParams.get('status');
    const payment_status = searchParams.get('payment_status');
    const start_date = searchParams.get('start_date');
    const end_date = searchParams.get('end_date');
    const sort = searchParams.get('sort') || 'created_at_desc';
    const page = parseInt(searchParams.get('page')) || 1;
    const limit = parseInt(searchParams.get('limit')) || 20;
    
    // Validate page and limit
    if (page < 1) {
      return NextResponse.json(
        { error: 'Page must be greater than 0' },
        { status: 400 }
      );
    }
    
    if (limit < 1 || limit > 100) {
      return NextResponse.json(
        { error: 'Limit must be between 1 and 100' },
        { status: 400 }
      );
    }
    
    // Calculate offset for pagination
    const offset = (page - 1) * limit;
    
    // Build WHERE conditions
    let whereConditions = ['userid = ?'];
    let queryParams = [user_id];
    
    if (status) {
      whereConditions.push('status = ?');
      queryParams.push(status);
    }
    
    if (payment_status) {
      whereConditions.push('payment_status = ?');
      queryParams.push(payment_status);
    }
    
    if (start_date) {
      whereConditions.push('created_at >= ?');
      queryParams.push(start_date);
    }
    
    if (end_date) {
      whereConditions.push('created_at <= ?');
      queryParams.push(end_date);
    }
    
    // Build ORDER BY clause
    let orderBy = 'ORDER BY created_at DESC';
    if (sort === 'created_at_asc') {
      orderBy = 'ORDER BY created_at ASC';
    } else if (sort === 'total_amount_desc') {
      orderBy = 'ORDER BY total_amount DESC';
    } else if (sort === 'total_amount_asc') {
      orderBy = 'ORDER BY total_amount ASC';
    } else if (sort === 'status') {
      orderBy = 'ORDER BY status ASC';
    } else if (sort === 'order_number') {
      orderBy = 'ORDER BY order_number ASC';
    }
    
    // Get total count for pagination
    const countQuery = `SELECT COUNT(*) as count FROM orders WHERE ${whereConditions.join(' AND ')}`;
    const countResult = await db_query(db, countQuery, queryParams);
    const total = countResult[0].count;
    
    // Get orders with pagination
    const ordersQuery = `
      SELECT 
        id, order_number, status, subtotal, tax_amount, shipping_amount, 
        total_amount, currency, payment_status, payment_method, tracking_number,
        shipped_at, delivered_at, created_at, updated_at
      FROM orders 
      WHERE ${whereConditions.join(' AND ')} 
      ${orderBy}
      LIMIT ? OFFSET ?
    `;
    
    const finalParams = [...queryParams, limit, offset];
    const orders = await db_query(db, ordersQuery, finalParams);
    
    // Calculate total pages
    const totalpages = Math.ceil(total / limit);
    
    const result = {
      data: orders,
      total: total,
      page: page,
      limit: limit,
      totalpages: totalpages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error retrieving orders:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve orders' },
      { status: 500 }
    );
  }
}

