/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  const { searchParams } = new URL(request.url);
  
  // Parse query parameters
  const page = parseInt(searchParams.get('page')) || 1;
  const limit = parseInt(searchParams.get('limit')) || 10;
  const status = searchParams.get('status');
  const payment_status = searchParams.get('payment_status');
  const startdate = searchParams.get('startdate');
  const enddate = searchParams.get('enddate');
  const search = searchParams.get('search');
  const sortby = searchParams.get('sortby') || 'order_date';
  const sortorder = searchParams.get('sortorder') || 'DESC';
  
  // Validate pagination
  if (page < 1 || limit < 1) {
    return NextResponse.json(
      { error: 'Invalid pagination parameters' },
      { status: 400 }
    );
  }
  
  // Validate sort parameters
  const validSortFields = ['order_date', 'total', 'status'];
  const validSortOrders = ['ASC', 'DESC'];
  
  if (!validSortFields.includes(sortby)) {
    return NextResponse.json(
      { error: 'Invalid sort field' },
      { status: 400 }
    );
  }
  
  if (!validSortOrders.includes(sortorder.toUpperCase())) {
    return NextResponse.json(
      { error: 'Invalid sort order' },
      { status: 400 }
    );
  }
  
  const offset = (page - 1) * limit;
  
  try {
    // Build WHERE conditions
    const whereConditions = [];
    const queryParams = [];
    let paramIndex = 1;
    
    // User access control - regular users see only their orders
    if (!is_admin && user_id) {
      whereConditions.push("o.userid = $" + paramIndex);
      queryParams.push(user_id);
      paramIndex++;
    }
    
    // Status filter
    if (status) {
      whereConditions.push("o.status = $" + paramIndex);
      queryParams.push(status);
      paramIndex++;
    }
    
    // Payment status filter
    if (payment_status) {
      whereConditions.push("o.payment_status = $" + paramIndex);
      queryParams.push(payment_status);
      paramIndex++;
    }
    
    // Date range filter
    if (startdate) {
      whereConditions.push("o.order_date >= $" + paramIndex);
      queryParams.push(startdate);
      paramIndex++;
    }
    
    if (enddate) {
      whereConditions.push("o.order_date <= $" + paramIndex);
      queryParams.push(enddate);
      paramIndex++;
    }
    
    // Search filter (order_number or shipping_name)
    if (search) {
      whereConditions.push(
        "(o.order_number ILIKE $" + paramIndex + 
        " OR o.shipping_name ILIKE $" + (paramIndex + 1) + ")"
      );
      queryParams.push(`%${search}%`);
      queryParams.push(`%${search}%`);
      paramIndex += 2;
    }
    
    const whereClause = whereConditions.length > 0 
      ? "WHERE " + whereConditions.join(" AND ")
      : "";
    
    // Count total records
    const countQuery = `
      SELECT COUNT(DISTINCT o.id) as total
      FROM orders o
      ${whereClause}
    `;
    
    const countResult = await db_query(db, countQuery, queryParams);
    const totalRecords = parseInt(countResult.rows[0].total);
    const totalPages = Math.ceil(totalRecords / limit);
    
    // Build main query with item count
    const dataQuery = `
      SELECT 
        o.id,
        o.order_number,
        o.order_date,
        o.status,
        o.total,
        o.payment_status,
        o.shipping_name,
        COUNT(oi.id) as item_count
      FROM orders o
      LEFT JOIN orderitems oi ON o.id = oi.ordersid
      ${whereClause}
      GROUP BY o.id, o.order_number, o.order_date, o.status, o.total, o.payment_status, o.shipping_name
      ORDER BY o.${sortby} ${sortorder.toUpperCase()}
      LIMIT $${paramIndex} OFFSET $${paramIndex + 1}
    `;
    
    const finalParams = [...queryParams, limit, offset];
    const dataResult = await db_query(db, dataQuery, finalParams);
    
    // Format response data
    const data = dataResult.rows.map(order => ({
      id: order.id,
      order_number: order.order_number,
      order_date: order.order_date,
      status: order.status,
      total: parseFloat(order.total),
      payment_status: order.payment_status,
      shipping_name: order.shipping_name,
      item_count: parseInt(order.item_count)
    }));
    
    const result = {
      data: data,
      total: totalRecords,
      page: page,
      limit: limit,
      totalpages: totalPages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error fetching orders:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve orders' },
      { status: 500 }
    );
  }
}
