
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Employer Profile  Edit',
    description: 'Edit a EmployerProfile',
    openGraph: {
        title: 'Employer Profile  Edit',
        description: 'Edit a EmployerProfile',
        url: '/employerprofile_edit',
        siteName: 'TechCorp'
    },
};

export default async function employerprofile_edit({ params }:  { params: Promise<{ id: string }>}) {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Company Profile","link":"/companyprofile_list"},{"title":"Company Profile  Details","link":"/companyprofile_details/[id]"},{"title":"Employer Profile  Edit","link":"/employerprofile_edit/[id]"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="EmployerProfile"
                                fields={[{"name":"full_name","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":"null","children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"},{"name":"CompanyProfileID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"}]}
                                mode="edit"
                                id={(await params).id}
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}