/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  // Parse request body
  const body = await request.json();
  
  // Validate required fields
  if (!body.recipient_name || !body.address_line1 || !body.city || !body.state || !body.postal_code || !body.country) {
    return NextResponse.json(
      { error: 'Victorian Era requires recipient name, address line 1, city, state, postal code, and country for shipping addresses' },
      { status: 400 }
    );
  }
  
  try {
    // If is_default is true, set all other user addresses to is_default false
    if (body.is_default === true) {
      await db_query(
        db,
        "UPDATE shippingaddresses SET is_default = false WHERE userid = $1",
        [user_id]
      );
    }
    
    // Generate UUID for new address
    const addressId = crypto.randomUUID();
    
    // Insert new shipping address
    await db_query(
      db,
      `INSERT INTO shippingaddresses 
       (id, userid, address_name, recipient_name, address_line1, address_line2, city, state, postal_code, country, phone, is_default) 
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
      [
        addressId,
        user_id,
        body.address_name || null,
        body.recipient_name,
        body.address_line1,
        body.address_line2 || null,
        body.city,
        body.state,
        body.postal_code,
        body.country,
        body.phone || null,
        body.is_default || false
      ]
    );
    
    // Retrieve the created address
    const addressResult = await db_query(
      db,
      "SELECT id, address_name, recipient_name, address_line1, address_line2, city, state, postal_code, country, phone, is_default FROM shippingaddresses WHERE id = $1",
      [addressId]
    );
    
    const result = {
      id: addressResult[0].id,
      address_name: addressResult[0].address_name,
      recipient_name: addressResult[0].recipient_name,
      address_line1: addressResult[0].address_line1,
      address_line2: addressResult[0].address_line2,
      city: addressResult[0].city,
      state: addressResult[0].state,
      postal_code: addressResult[0].postal_code,
      country: addressResult[0].country,
      phone: addressResult[0].phone,
      is_default: addressResult[0].is_default
    };
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json(
      { error: 'Victorian Era could not create shipping address. Please try again.' },
      { status: 500 }
    );
  }
}
