/*
SysArchitect API v1.0.0
WARNING: This file is automatically generated and should not be modified.
*/

import { check_auth } from "@/auth/auth";
import { NextResponse } from "next/server";
import { paymentSystem, completeSubscription } from "@/payments/stripe";

/* Payment Pricing Route */
import { db_init, db_select } from '../../../database/supabase';
const  UserTiers: any = [];
/* End Payment Pricing Route */

export async function GET(request: Request) {
    try {
      // Get session ID from URL params
      const { searchParams } = new URL(request.url);
      const sessionId = searchParams.get('session_id')??'';

      if (sessionId.length == 0) {
        return NextResponse.json(
          { error: 'Missing session ID' },
          { status: 400 }
        );
      }

      // Get session ID from URL params
      const db = await db_init();
 
      const UserInfo = await check_auth(db, db_select);
      if (UserInfo.UserID.length == 0) {
        return NextResponse.json(
          { error: 'Not logged in' },
          { status: 403 }
        );
      }
  
      // Complete the subscription
      await completeSubscription(db, sessionId);
  
      // Return success response
      return NextResponse.json({ 
        success: true,
        message: 'Subscription completed successfully'
      });
  
    } catch (error) {
      console.error('Error completing subscription:', error);
      return NextResponse.json(
        { 
          success: false,
          error: 'Failed to complete subscription' 
        },
        { status: 500 }
      );
    }
  }
  
  

export async function POST(request: Request) {
  
    const db = await db_init();
 
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length == 0) {
      return NextResponse.json(
        { error: 'Not logged in' },
        { status: 403 }
      );
    }

    // Get plan type from request body
    const { planType, subscriptionType } = await request.json();
  
    // Create Checkout session
    const stripeUrl = await paymentSystem(
        db,
        planType,
        UserTiers,
        subscriptionType,
        UserInfo.UserID
    );
  
    if (!stripeUrl) {
        return NextResponse.json(
          { error: 'Failed to create checkout session' },
          { status: 500 }
        );
    }
  
    return NextResponse.json({ url: stripeUrl });  
}