
/* 
This file is generated by Sitepaige. 
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import HeaderView from '@/views/Header';
import OurStory2View from '@/views/Our_Story_2';
import MissionValuesView from '@/views/Mission___Values';
import FooterView from '@/views/Footer';

export const metadata: Metadata = {
    title: 'About  Us',
    description: 'Story of the taco truck and team',
    openGraph: {
        title: 'About  Us',
        description: 'Story of the taco truck and team',
        url: '/about_us',
        siteName: 'Zizzle'
    },
};

export default  function about_us() {
    
    return (
        <div className="page" style={{ minHeight: '75vh' }}>
            <main>
                
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ paddingLeft: '5px', paddingRight: '10px', paddingTop: '2px', maxHeight: '100px', display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <HeaderView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <OurStory2View />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <MissionValuesView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ paddingLeft: '5px', paddingRight: '10px', paddingTop: '25px', paddingBottom: '2px', display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <FooterView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
            </main>
        </div>
    );
}