
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    
    const category = searchParams.get('category');
    const publishedParam = searchParams.get('published');
    const featuredParam = searchParams.get('featured');
    const tagsParam = searchParams.get('tags');
    const author = searchParams.get('author');
    const pageParam = searchParams.get('page');
    const limitParam = searchParams.get('limit');
    
    // Parse and validate parameters
    const published = publishedParam !== null ? publishedParam === 'true' : null;
    const featured = featuredParam !== null ? featuredParam === 'true' : null;
    const tags = tagsParam ? tagsParam.split(',').map(tag => tag.trim()) : [];
    const page = pageParam ? parseInt(pageParam, 10) : 1;
    const limit = limitParam ? parseInt(limitParam, 10) : 20;
    
    // Validate pagination parameters
    if (page < 1) {
      return NextResponse.json({ error: 'Vitalisona: Page number must be greater than 0' }, { status: 400 });
    }
    
    if (limit < 1 || limit > 100) {
      return NextResponse.json({ error: 'Vitalisona: Limit must be between 1 and 100' }, { status: 400 });
    }
    
    // Build dynamic WHERE conditions
    let whereConditions = [];
    let queryParams = [];
    let paramIndex = 1;
    
    if (category) {
      whereConditions.push(`category = ?`);
      queryParams.push(category);
      paramIndex++;
    }
    
    if (published !== null) {
      whereConditions.push(`published = ?`);
      queryParams.push(published);
      paramIndex++;
    }
    
    if (featured !== null) {
      whereConditions.push(`featured = ?`);
      queryParams.push(featured);
      paramIndex++;
    }
    
    if (author) {
      whereConditions.push(`author LIKE ?`);
      queryParams.push(`%${author}%`);
      paramIndex++;
    }
    
    if (tags && tags.length > 0) {
      const tagConditions = tags.map(() => {
        const condition = `tags LIKE ?`;
        queryParams.push(`%${tags[queryParams.filter(p => typeof p === 'string' && p.includes('%')).length - tags.filter((_, index) => index < queryParams.filter(p => typeof p === 'string' && p.includes('%')).length).length]}%`);
        return condition;
      });
      
      // Reset and rebuild tag conditions properly
      const currentParamCount = queryParams.length;
      for (let i = 0; i < tags.length; i++) {
        if (queryParams.length === currentParamCount + i) {
          queryParams.push(`%${tags[i]}%`);
        }
      }
      
      const tagConditionsArray = [];
      for (let i = 0; i < tags.length; i++) {
        tagConditionsArray.push(`tags LIKE ?`);
      }
      
      whereConditions.push(`(${tagConditionsArray.join(' OR ')})`);
    }
    
    // Rebuild tags filtering properly
    if (tags && tags.length > 0) {
      // Remove the previous tag conditions and params
      const nonTagParams = [];
      const nonTagConditions = [];
      
      if (category) {
        nonTagConditions.push(`category = ?`);
        nonTagParams.push(category);
      }
      
      if (published !== null) {
        nonTagConditions.push(`published = ?`);
        nonTagParams.push(published);
      }
      
      if (featured !== null) {
        nonTagConditions.push(`featured = ?`);
        nonTagParams.push(featured);
      }
      
      if (author) {
        nonTagConditions.push(`author LIKE ?`);
        nonTagParams.push(`%${author}%`);
      }
      
      // Add tag conditions
      const tagConditions = tags.map(() => `tags LIKE ?`);
      if (tagConditions.length > 0) {
        nonTagConditions.push(`(${tagConditions.join(' OR ')})`);
        tags.forEach(tag => {
          nonTagParams.push(`%${tag}%`);
        });
      }
      
      whereConditions = nonTagConditions;
      queryParams = nonTagParams;
    }
    
    const whereClause = whereConditions.length > 0 ? `WHERE ${whereConditions.join(' AND ')}` : '';
    
    // Get total count
    const countQuery = `SELECT COUNT(*) as total FROM wellnessresources ${whereClause}`;
    const countResult = await db_query(db, countQuery, queryParams);
    const total = countResult[0].total;
    
    // Calculate pagination
    const offset = (page - 1) * limit;
    const totalPages = Math.ceil(total / limit);
    
    // Get paginated data
    const dataQuery = `
      SELECT 
        id, title, content, category, author, published_date, tags, 
        featured_image, published, featured, display_order
      FROM wellnessresources 
      ${whereClause}
      ORDER BY display_order ASC, published_date DESC
      LIMIT ? OFFSET ?
    `;
    
    const finalParams = [...queryParams, limit, offset];
    const resources = await db_query(db, dataQuery, finalParams);
    
    // Format the response data
    const data = resources.map(resource => ({
      id: resource.id,
      title: resource.title,
      content: resource.content,
      category: resource.category,
      author: resource.author,
      published_date: resource.published_date,
      tags: resource.tags,
      featured_image: resource.featured_image,
      published: Boolean(resource.published),
      featured: Boolean(resource.featured),
      display_order: resource.display_order
    }));
    
    const result = {
      data: data,
      total: total,
      page: page,
      limit: limit,
      totalpages: totalPages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona WellnessResourcesList API Error:', error);
    return NextResponse.json({ 
      error: 'Vitalisona: Failed to retrieve wellness resources. Please try again later.' 
    }, { status: 500 });
  }
}

