
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import List from '@/components/list';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Resume Databases',
    description: 'List of ResumeDatabase',
    openGraph: {
        title: 'Resume Databases',
        description: 'List of ResumeDatabase',
        url: '/resumedatabase_list',
        siteName: 'TechCorp'
    },
};

export default  function resumedatabase_list() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Resume Databases","link":"/resumedatabase_list"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <List
                                modelName="ResumeDatabase"
                                showAdminFeatures={true}
                                nameField="candidate_name"
                                 
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}