
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse service ID from URL or query parameters
    const url = new URL(request.url);
    const serviceId = url.searchParams.get('id');
    
    // Validate required input
    if (!serviceId) {
      const result = {
        success: false,
        message: 'Service ID is required for Vitalisona service deletion'
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Check if service exists
    const serviceExists = await db_query(db, 
      "SELECT id FROM services WHERE id = ?", 
      [serviceId]
    );
    
    if (!serviceExists || serviceExists.length === 0) {
      const result = {
        success: false,
        message: 'Vitalisona service not found'
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    // Check for active sessions associated with this service
    // Active sessions are those not completed or cancelled
    const activeSessions = await db_query(db, 
      "SELECT id FROM sessions WHERE servicesid = ? AND status NOT IN ('completed', 'cancelled')", 
      [serviceId]
    );
    
    if (activeSessions && activeSessions.length > 0) {
      const result = {
        success: false,
        message: 'Cannot delete Vitalisona service: active sessions are still associated with this service. Please complete or cancel all active sessions before deletion.'
      };
      return NextResponse.json(result, { status: 409 });
    }
    
    // Delete the service
    const deleteResult = await db_query(db, 
      "DELETE FROM services WHERE id = ?", 
      [serviceId]
    );
    
    if (deleteResult.changes === 0) {
      const result = {
        success: false,
        message: 'Failed to delete Vitalisona service'
      };
      return NextResponse.json(result, { status: 500 });
    }
    
    const result = {
      success: true,
      message: 'Vitalisona sound healing service has been successfully deleted'
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona service deletion error:', error);
    const result = {
      success: false,
      message: 'Internal server error occurred while deleting Vitalisona service'
    };
    return NextResponse.json(result, { status: 500 });
  }
}

