/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required input
    if (!id) {
      const result = { success: false, message: 'Shipping address ID is required' };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Verify the address exists and belongs to the authenticated user
    const addressCheck = await db_query(
      db,
      "SELECT id, is_default FROM shippingaddresses WHERE id = $1 AND userid = $2",
      [id, user_id]
    );
    
    if (!addressCheck || addressCheck.length === 0) {
      const result = { 
        success: false, 
        message: 'Shipping address not found or you do not have permission to delete this address' 
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    const isDefaultAddress = addressCheck[0].is_default;
    
    // Delete the shipping address
    await db_query(
      db,
      "DELETE FROM shippingaddresses WHERE id = $1 AND userid = $2",
      [id, user_id]
    );
    
    // If we deleted the default address, set another address as default if any exist
    if (isDefaultAddress) {
      const remainingAddresses = await db_query(
        db,
        "SELECT id FROM shippingaddresses WHERE userid = $1 ORDER BY id LIMIT 1",
        [user_id]
      );
      
      if (remainingAddresses && remainingAddresses.length > 0) {
        await db_query(
          db,
          "UPDATE shippingaddresses SET is_default = $1 WHERE id = $2",
          [true, remainingAddresses[0].id]
        );
      }
    }
    
    const result = {
      success: true,
      message: 'Shipping address deleted successfully from Victorian Era account'
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    const result = {
      success: false,
      message: 'Victorian Era: Failed to delete shipping address. Please try again later.'
    };
    return NextResponse.json(result, { status: 500 });
  }
}
