/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    
    // Pagination parameters
    const page = parseInt(searchParams.get('page')) || 1;
    const limit = parseInt(searchParams.get('limit')) || 10;
    const offset = (page - 1) * limit;
    
    // Filter parameters
    const respondedParam = searchParams.get('responded');
    const responded = respondedParam ? respondedParam === 'true' : null;
    const startdate = searchParams.get('startdate');
    const enddate = searchParams.get('enddate');
    const search = searchParams.get('search');
    
    // Sort parameters
    const sortby = searchParams.get('sortby') || 'submitted_date';
    const sortorder = searchParams.get('sortorder') || 'DESC';
    
    // Build WHERE conditions
    const whereConditions = [];
    const queryParams = [];
    let paramIndex = 1;
    
    // Filter by responded status
    if (responded !== null) {
      whereConditions.push("responded = $" + paramIndex);
      queryParams.push(responded);
      paramIndex++;
    }
    
    // Filter by date range
    if (startdate) {
      whereConditions.push("submitted_date >= $" + paramIndex);
      queryParams.push(startdate);
      paramIndex++;
    }
    
    if (enddate) {
      whereConditions.push("submitted_date <= $" + paramIndex);
      queryParams.push(enddate);
      paramIndex++;
    }
    
    // Search by name, email, or subject
    if (search) {
      whereConditions.push("(name ILIKE $" + paramIndex + " OR email ILIKE $" + (paramIndex + 1) + " OR subject ILIKE $" + (paramIndex + 2) + ")");
      queryParams.push(`%${search}%`);
      queryParams.push(`%${search}%`);
      queryParams.push(`%${search}%`);
      paramIndex += 3;
    }
    
    // Build WHERE clause
    const whereClause = whereConditions.length > 0 ? " WHERE " + whereConditions.join(" AND ") : "";
    
    // Validate sort field to prevent SQL injection
    const allowedSortFields = ['id', 'name', 'email', 'subject', 'submitted_date', 'responded'];
    const sortField = allowedSortFields.includes(sortby) ? sortby : 'submitted_date';
    const sortDirection = sortorder.toUpperCase() === 'ASC' ? 'ASC' : 'DESC';
    
    // Get total count
    const countQuery = "SELECT COUNT(*) as count FROM contactmessages" + whereClause;
    const countResult = await db_query(db, countQuery, queryParams);
    const total = parseInt(countResult[0].count);
    
    // Get paginated data
    const dataQuery = "SELECT id, name, email, subject, submitted_date, responded FROM contactmessages" + whereClause + " ORDER BY " + sortField + " " + sortDirection + " LIMIT $" + paramIndex + " OFFSET $" + (paramIndex + 1);
    const finalParams = [...queryParams, limit, offset];
    const messages = await db_query(db, dataQuery, finalParams);
    
    // Calculate total pages
    const totalpages = Math.ceil(total / limit);
    
    // Format response
    const result = {
      data: messages.map(msg => ({
        id: msg.id,
        name: msg.name,
        email: msg.email,
        subject: msg.subject,
        submitted_date: msg.submitted_date,
        responded: msg.responded
      })),
      total: total,
      page: page,
      limit: limit,
      totalpages: totalpages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to retrieve contact messages: ' + error.message },
      { status: 500 }
    );
  }
}
