
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const limitParam = searchParams.get('limit');
    
    // Set default limit if not provided, or parse the provided limit
    let limit = 10; // Default limit for homepage featured items
    if (limitParam) {
      const parsedLimit = parseInt(limitParam);
      if (isNaN(parsedLimit) || parsedLimit < 1) {
        return NextResponse.json({ error: 'Invalid limit parameter' }, { status: 400 });
      }
      limit = parsedLimit;
    }
    
    // Query featured and available menu items
    const query = `
      SELECT 
        id,
        categoriesid,
        name,
        description,
        price,
        image_url,
        ingredients,
        spice_level,
        calories,
        available,
        featured,
        preparation_time
      FROM menuitems 
      WHERE featured = ? AND available = ? 
      ORDER BY name 
      LIMIT ?
    `;
    
    const items = await db_query(db, query, [true, true, limit]);
    
    // Format the response according to the interface specification
    const result = {
      items: items.map(item => ({
        id: item.id,
        categoriesid: item.categoriesid,
        name: item.name,
        description: item.description,
        price: item.price,
        image_url: item.image_url,
        ingredients: item.ingredients,
        spice_level: item.spice_level,
        calories: item.calories,
        available: item.available,
        featured: item.featured,
        preparation_time: item.preparation_time
      }))
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error fetching featured items:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

