
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import Login from '@/components/login';

export const metadata: Metadata = {
    title: 'Login',
    description: 'User login page',
    openGraph: {
        title: 'Login',
        description: 'User login page',
        url: '/login',
        siteName: 'Maryland Christmas'
    },
};

export default  function login() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><Login providers={["google","facebook"]} />
                        </div>
                    </div>
            </main>
        </div>
    );
}