
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import List from '@/components/list';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Job Postings',
    description: 'List of JobPosting',
    openGraph: {
        title: 'Job Postings',
        description: 'List of JobPosting',
        url: '/jobposting_list',
        siteName: 'Job Board'
    },
};

export default  function jobposting_list() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Job Postings","link":"/jobposting_list"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <List 
                                modelName="JobPosting"
                                showAdminFeatures={false}
                                nameField="job_title"
                                
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}