
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';

import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Contact',
    description: 'Contact page',
    openGraph: {
        title: 'Contact',
        description: 'Contact page',
        url: '/contact',
        siteName: 'TechCorp'
    },
};

export default  function contact() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Contact","link":"/contact"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">
                        </div>
                    </div>
            </main>
        </div>
    );
}