
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import Contact from '@/components/contact';

export const metadata: Metadata = {
    title: 'Contact',
    description: 'Contact page',
    openGraph: {
        title: 'Contact',
        description: 'Contact page',
        url: '/contact',
        siteName: 'Maryland Christmas'
    },
};

export default  function contact() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><Contact 
                        useRecaptcha={false}
                        companyName={"Maryland Christmas"}
                        companyWebsite={"https://www.yourdomain.com"}
                        companyEmail={"info@yourdomain.com"}
                        companyPhone={"123-456-7890"}
                        companyAddress={"123 Your Street"}
                        companyCity={"Anytown"}
                        companyState={"CA"}
                        companyZip={"12345"}
                        companyCountry={"USA"}
                    />
                        </div>
                    </div>
            </main>
        </div>
    );
}