/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse practitioner ID from request body
    const body = await request.json();
    const { id } = body;
    
    // Validate required fields
    if (!id) {
      return NextResponse.json({ 
        success: false, 
        message: 'Vitalisona: Practitioner ID is required' 
      }, { status: 400 });
    }
    
    // Check if practitioner exists
    const practitionerExists = await db_query(db, 
      "SELECT id FROM practitioners WHERE id = ?", 
      [id]
    );
    
    if (!practitionerExists || practitionerExists.length === 0) {
      return NextResponse.json({ 
        success: false, 
        message: 'Vitalisona: Practitioner not found' 
      }, { status: 404 });
    }
    
    // Check for active or future sessions assigned to this practitioner
    const currentDate = new Date().toISOString().split('T')[0]; // Get current date in YYYY-MM-DD format
    
    const activeFutureSessions = await db_query(db, 
      "SELECT id FROM sessions WHERE practitionersid = ? AND status NOT IN ('cancelled', 'completed') AND session_date >= ?", 
      [id, currentDate]
    );
    
    if (activeFutureSessions && activeFutureSessions.length > 0) {
      return NextResponse.json({ 
        success: false, 
        message: 'Vitalisona: Cannot delete practitioner with active or future sessions assigned. Please reassign or cancel sessions first to maintain scheduling integrity.' 
      }, { status: 400 });
    }
    
    // Delete the practitioner
    await db_query(db, 
      "DELETE FROM practitioners WHERE id = ?", 
      [id]
    );
    
    const result = { 
      success: true, 
      message: 'Vitalisona: Practitioner profile successfully deleted from system' 
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    const result = { 
      success: false, 
      message: 'Vitalisona: An error occurred while deleting practitioner profile' 
    };
    return NextResponse.json(result, { status: 500 });
  }
}
