/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  // Parse request body
  const body = await request.json();
  
  // Validate required field
  if (!body.id) {
    return NextResponse.json({
      success: false,
      message: 'Image ID is required'
    }, { status: 400 });
  }
  
  const id = body.id;
  
  try {
    // Check if image exists
    const imageCheck = await db_query(db, 
      "SELECT id, productsid, is_primary FROM productimages WHERE id = $1",
      [id]
    );
    
    if (imageCheck.length === 0) {
      return NextResponse.json({
        success: false,
        message: 'Image not found'
      }, { status: 404 });
    }
    
    const imageToDelete = imageCheck[0];
    const productId = imageToDelete.productsid;
    const wasPrimary = imageToDelete.is_primary;
    
    // Delete the image
    await db_query(db, "DELETE FROM productimages WHERE id = $1", [id]);
    
    // If deleted image was primary, set another image as primary
    if (wasPrimary) {
      const remainingImages = await db_query(db,
        "SELECT id FROM productimages WHERE productsid = $1 ORDER BY display_order, id LIMIT 1",
        [productId]
      );
      
      if (remainingImages.length > 0) {
        await db_query(db,
          "UPDATE productimages SET is_primary = true WHERE id = $1",
          [remainingImages[0].id]
        );
      }
    }
    
    const result = {
      success: true,
      message: 'Product image deleted successfully'
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json({
      success: false,
      message: 'Failed to delete product image'
    }, { status: 500 });
  }
}
