
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Job Posting  Edit',
    description: 'Edit a JobPosting',
    openGraph: {
        title: 'Job Posting  Edit',
        description: 'Edit a JobPosting',
        url: '/jobposting_edit',
        siteName: 'Job Board'
    },
};

export default async function jobposting_edit({ params }:  { params: Promise<{ id: string }>}) {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Employer Profile","link":"/employerprofile_list"},{"title":"Employer Profile  Details","link":"/employerprofile_details/[id]"},{"title":"Job Posting  Edit","link":"/jobposting_edit/[id]"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="JobPosting"
                                fields={[{"name":"job_title","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"job_description","datatype":"TEXT","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"employment_type","datatype":"VARCHAR","datatypesize":"100","key":null,"is_name":"false","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"salary_range","datatype":"VARCHAR","datatypesize":"100","key":null,"is_name":"false","is_searchable":"false","required":"false","untouchable":"false","default":null,"children":[]},{"name":"date_posted","datatype":"DATETIME","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"},{"name":"EmployerProfileID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"},{"name":"JobCategoryID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"},{"name":"JobLocationID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"}]}
                                mode="edit"
                                id={(await params).id}
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}