
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Resume Management  Add',
    description: 'Add a new ResumeManagement',
    openGraph: {
        title: 'Resume Management  Add',
        description: 'Add a new ResumeManagement',
        url: '/resumemanagement_add',
        siteName: 'Job Board'
    },
};

export default  function resumemanagement_add() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Candidate Profile","link":"/candidateprofile_list"},{"title":"Candidate Profile  Details","link":"/candidateprofile_details/[id]"},{"title":"Resume Management  Add","link":"/resumemanagement_add"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="ResumeManagement"
                                fields={[{"name":"resume_title","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"resume_file","datatype":"BINARY","datatypesize":"null","key":null,"is_name":"false","is_searchable":"false","required":"true","untouchable":"false","default":null,"children":[]},{"name":"date_uploaded","datatype":"DATETIME","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"},{"name":"CandidateProfileID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"}]}
                                mode="add"
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}