
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Details from '@/components/details';
import List from '@/components/list';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Category  Details',
    description: 'Details of Category',
    openGraph: {
        title: 'Category  Details',
        description: 'Details of Category',
        url: '/category_details',
        siteName: 'TechCorp'
    },
};

export default async function category_details({ params }:  { params: Promise<{ id: string }>}) {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Category","link":"/category_list"},{"title":"Category  Details","link":"/category_details/[id]"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Details
                                modelName="Category"
                                id={(await params).id}
                            />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col">    
                            <List
                                modelName="JobListing"
                                showAdminFeatures={true}
                                nameField="job_title"
                                 subFieldName="CategoryID" subFieldValue={(await params).id}
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}