
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { db_add, db_update, db_select, db_delete, db_init } from '../../../database/supabase';
export async function GET(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const ids = searchParams.get('ids')?.split(',') || [];
  
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

  
  if (!user_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  
  try {
    let whereConditions = [{ field: 'UserID', op: '=', value: user_id }];
    
    const result = await db_select(
      db,
      'Members',
      ['ID', 'first_name', 'last_name', 'email', 'phone', 'address', 'city', 'state', 'zip', 'membership_type', 'joined_date', 'expiration_date', 'profile_image', 'UserID'],
      ids.length > 0 ? ids : undefined,
      whereConditions
    );
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch members' }, { status: 500 });
  }
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

  
  if (!user_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  
  try {
    const requestData = await request.json();
    
    // Validate required fields
    const requiredFields = ['first_name', 'last_name', 'email', 'membership_type', 'joined_date', 'expiration_date'];
    for (const field of requiredFields) {
      if (!requestData[field]) {
        return NextResponse.json({ error: `${field} is required` }, { status: 400 });
      }
    }
    
    // Create new member with UUID and user ID
    const memberData = {
      ID: crypto.randomUUID(),
      first_name: requestData.first_name,
      last_name: requestData.last_name,
      email: requestData.email,
      phone: requestData.phone || null,
      address: requestData.address || null,
      city: requestData.city || null,
      state: requestData.state || null,
      zip: requestData.zip || null,
      membership_type: requestData.membership_type,
      joined_date: requestData.joined_date,
      expiration_date: requestData.expiration_date,
      profile_image: requestData.profile_image || null,
      UserID: user_id
    };
    
    const result = await db_add(db, 'Members', memberData);
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create member' }, { status: 500 });
  }
}

export async function PUT(request: NextRequest): Promise<NextResponse> {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

  
  if (!user_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  
  try {
    const requestData = await request.json();
    
    // Validate ID is provided
    if (!requestData.ID) {
      return NextResponse.json({ error: 'Member ID is required' }, { status: 400 });
    }
    
    // Validate required fields
    const requiredFields = ['first_name', 'last_name', 'email', 'membership_type', 'joined_date', 'expiration_date'];
    for (const field of requiredFields) {
      if (!requestData[field]) {
        return NextResponse.json({ error: `${field} is required` }, { status: 400 });
      }
    }
    
    // Verify the member belongs to the current user
    const existingMember = await db_select(
      db,
      'Members',
      ['ID'],
      [requestData.ID],
      [{ field: 'UserID', op: '=', value: user_id }]
    );
    
    if (!existingMember || existingMember.length === 0) {
      return NextResponse.json({ error: 'Member not found or access denied' }, { status: 404 });
    }
    
    // Update the member
    const memberData = {
      ID: requestData.ID,
      first_name: requestData.first_name,
      last_name: requestData.last_name,
      email: requestData.email,
      phone: requestData.phone || null,
      address: requestData.address || null,
      city: requestData.city || null,
      state: requestData.state || null,
      zip: requestData.zip || null,
      membership_type: requestData.membership_type,
      joined_date: requestData.joined_date,
      expiration_date: requestData.expiration_date,
      profile_image: requestData.profile_image || null,
      UserID: user_id
    };
    
    const result = await db_update(
      db,
      'Members',
      memberData,
      [requestData.ID],
      [{ field: 'UserID', op: '=', value: user_id }]
    );
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to update member' }, { status: 500 });
  }
}

export async function DELETE(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');
  
  if (!id) {
    return NextResponse.json({ error: 'Member ID is required' }, { status: 400 });
  }
  
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  if (!user_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  
  try {
    // Verify the member belongs to the current user
    const existingMember = await db_select(
      db,
      'Members',
      ['ID'],
      [id],
      [{ field: 'UserID', op: '=', value: user_id }]
    );
    
    if (!existingMember || existingMember.length === 0) {
      return NextResponse.json({ error: 'Member not found or access denied' }, { status: 404 });
    }
    
    // Delete the member
    const result = await db_delete(db, 'Members', [id]);
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to delete member' }, { status: 500 });
  }
}

