
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const limitParam = searchParams.get('limit');
    const limit = limitParam ? parseInt(limitParam) : 20; // Default limit of 20

    // Validate limit parameter
    if (isNaN(limit) || limit <= 0) {
      return NextResponse.json({ error: 'Invalid limit parameter' }, { status: 400 });
    }

    // Query featured and published dresses with primary images
    const query = `
      SELECT 
        d.id, d.categoriesid, d.name, d.slug, d.description, 
        d.price, d.compare_at_price, d.sku, d.stock_quantity,
        d.available_sizes, d.available_colors, d.material, 
        d.care_instructions, d.featured, d.published, 
        d.created_at, d.updated_at,
        di.image_url as primary_image
      FROM dresses d
      LEFT JOIN dressimages di ON d.id = di.dressesid AND di.is_primary = true
      WHERE d.featured = true AND d.published = true
      ORDER BY d.created_at DESC
      LIMIT ?
    `;

    const dresses = await db_query(db, query, [limit]);

    // Format the response data
    const formattedDresses = dresses.map(dress => ({
      id: dress.id,
      categoriesid: dress.categoriesid,
      name: dress.name,
      slug: dress.slug,
      description: dress.description,
      price: dress.price,
      compare_at_price: dress.compare_at_price,
      sku: dress.sku,
      stock_quantity: dress.stock_quantity,
      available_sizes: JSON.parse(dress.available_sizes || '[]'),
      available_colors: JSON.parse(dress.available_colors || '[]'),
      material: dress.material,
      care_instructions: dress.care_instructions,
      featured: dress.featured,
      published: dress.published,
      primary_image: dress.primary_image,
      created_at: dress.created_at,
      updated_at: dress.updated_at
    }));

    const result = {
      data: formattedDresses
    };

    return NextResponse.json(result);

  } catch (error) {
    console.error('Error fetching featured dresses:', error);
    return NextResponse.json(
      { error: 'Failed to fetch featured dresses' }, 
      { status: 500 }
    );
  }
}

