import React from 'react';

interface GeneratedAddOnServicesViewProps {
  isContainer?: boolean;
}

export default function GeneratedAddOnServicesView({ isContainer = false }: GeneratedAddOnServicesViewProps){
  const useCard = false;
  return (
      <div className="rtext-content" dangerouslySetInnerHTML={{__html: "<section style=\"width: 100%; margin: 48px 0; padding: 40px; background-color: #f0f8ff; color: #1a1a1a;\">\n    <h2 style=\"margin-bottom: 32px; font-size: 28px;\">Additional Services at My Video</h2>\n    \n    <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 24px; width: 100%;\">\n        <article style=\"background-color: #ffffff; padding: 32px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\n            <h3 style=\"margin-bottom: 16px;\">Drone Footage</h3>\n            <p style=\"line-height: 1.6;\">Elevate your visual storytelling with our professional drone cinematography, capturing breathtaking aerial perspectives for your project.</p>\n        </article>\n\n        <article style=\"background-color: #ffffff; padding: 32px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\n            <h3 style=\"margin-bottom: 16px;\">Multiple Camera Operators</h3>\n            <p style=\"line-height: 1.6;\">Maximize coverage and capture multiple angles simultaneously with our experienced multi-camera teams.</p>\n        </article>\n\n        <article style=\"background-color: #ffffff; padding: 32px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\n            <h3 style=\"margin-bottom: 16px;\">Rush Delivery</h3>\n            <p style=\"line-height: 1.6;\">Need your footage quickly? Our rush delivery service ensures you receive high-quality edits in the shortest possible timeframe.</p>\n        </article>\n\n        <article style=\"background-color: #ffffff; padding: 32px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\n            <h3 style=\"margin-bottom: 16px;\">Raw Footage Access</h3>\n            <p style=\"line-height: 1.6;\">Complete creative control is yours with our raw footage package, providing uncompressed, unedited video files.</p>\n        </article>\n\n        <article style=\"background-color: #ffffff; padding: 32px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\n            <h3 style=\"margin-bottom: 16px;\">Extended Edits</h3>\n            <p style=\"line-height: 1.6;\">Comprehensive post-production services offering longer, more detailed video narratives tailored to your specific requirements.</p>\n        </article>\n    </div>\n</section>" }} />
  );
}