import React from 'react';

interface GeneratedBookingAvailabilityViewProps {
  isContainer?: boolean;
}

export default function GeneratedBookingAvailabilityView({ isContainer = false }: GeneratedBookingAvailabilityViewProps){
  const useCard = false;
  return (
      <div className="rtext-content" dangerouslySetInnerHTML={{__html: "<section style=\"width: 100%; margin: 48px 0; padding: 48px; background-color: #f0f8ff;\">\n    <h2 style=\"text-align: center; margin-bottom: 32px;\">Frequently Asked Questions - My Video</h2>\n    \n    <div style=\"width: 100%; background-color: #ffffff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 24px;\">\n        <h3 style=\"margin-bottom: 24px;\">Booking Process</h3>\n        <dl style=\"width: 100%;\">\n            <dt style=\"font-weight: bold; margin-bottom: 16px;\">How do I book a videography service with My Video?</dt>\n            <dd style=\"margin-bottom: 24px;\">Contact us through our website or email. We'll schedule a consultation to discuss your project details, timeline, and specific requirements.</dd>\n            \n            <dt style=\"font-weight: bold; margin-bottom: 16px;\">What information do I need to provide when booking?</dt>\n            <dd style=\"margin-bottom: 24px;\">Provide event date, type of video needed, preferred location, estimated duration, and any specific creative vision or requirements.</dd>\n        </dl>\n    </div>\n    \n    <div style=\"width: 100%; background-color: #e8f4f8; padding: 40px; border-radius: 12px; margin-bottom: 24px;\">\n        <h3 style=\"margin-bottom: 24px;\">Booking Timeline</h3>\n        <dl style=\"width: 100%;\">\n            <dt style=\"font-weight: bold; margin-bottom: 16px;\">How far in advance should I book?</dt>\n            <dd style=\"margin-bottom: 24px;\">We recommend booking at least 2-3 months in advance, especially for weddings and major events. Popular dates fill up quickly.</dd>\n            \n            <dt style=\"font-weight: bold; margin-bottom: 16px;\">What is your availability?</dt>\n            <dd style=\"margin-bottom: 24px;\">We service the entire region and are typically available weekends and select weekdays. Check our online calendar for real-time availability.</dd>\n        </dl>\n    </div>\n    \n    <div style=\"width: 100%; background-color: #ffffff; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);\">\n        <h3 style=\"margin-bottom: 24px;\">Deposits and Policies</h3>\n        <dl style=\"width: 100%;\">\n            <dt style=\"font-weight: bold; margin-bottom: 16px;\">What is your deposit policy?</dt>\n            <dd style=\"margin-bottom: 24px;\">A 50% non-refundable deposit is required to secure your booking date. The remaining balance is due 7 days before the event.</dd>\n            \n            <dt style=\"font-weight: bold; margin-bottom: 16px;\">What is your cancellation policy?</dt>\n            <dd style=\"margin-bottom: 24px;\">Cancellations within 30 days of the event forfeit the full deposit. Rescheduling is possible with at least 45 days' notice, subject to availability.</dd>\n        </dl>\n    </div>\n</section>" }} />
  );
}