import React from 'react';

interface GeneratedCorporateVideosViewProps {
  isContainer?: boolean;
}

export default function GeneratedCorporateVideosView({ isContainer = false }: GeneratedCorporateVideosViewProps){
  const useCard = false;
  return (
      <div className="rtext-content" dangerouslySetInnerHTML={{__html: "<main style=\"width: 100%; margin: 48px 0;\">\n    <section style=\"width: 100%; padding: 48px; margin: 48px 0; background-color: #f0f8ff;\">\n        <h1>Corporate Videography Services by My Video</h1>\n        <p style=\"font-size: 18px; line-height: 1.8;\">At My Video, we transform your brand's narrative through professional, high-quality video production tailored to your unique communication needs.</p>\n    </section>\n\n    <section style=\"width: 100%; display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 32px; padding: 40px; margin: 48px 0; background-color: #2c3e50; color: #ffffff;\">\n        <article style=\"padding: 32px; border: 2px solid #34495e; border-radius: 8px;\">\n            <h2>Promotional Videos</h2>\n            <p>Craft compelling brand stories that captivate and convert, showcasing your company's unique value proposition with cinematic precision.</p>\n        </article>\n\n        <article style=\"padding: 32px; border: 2px solid #34495e; border-radius: 8px;\">\n            <h2>Training Content</h2>\n            <p>Develop engaging, professional training videos that simplify complex information and enhance learning retention for your team.</p>\n        </article>\n\n        <article style=\"padding: 32px; border: 2px solid #34495e; border-radius: 8px;\">\n            <h2>Event Coverage</h2>\n            <p>Capture the essence of your corporate events with dynamic, high-quality videography that preserves memorable moments.</p>\n        </article>\n\n        <article style=\"padding: 32px; border: 2px solid #34495e; border-radius: 8px;\">\n            <h2>Testimonial Videos</h2>\n            <p>Create authentic, persuasive testimonial videos that build trust and showcase real client experiences with your brand.</p>\n        </article>\n    </section>\n\n    <section style=\"width: 100%; padding: 48px; margin: 48px 0; background-color: #e8f4f8;\">\n        <h2>Why Choose My Video?</h2>\n        <ul style=\"list-style-type: disc; padding-left: 32px; line-height: 1.8;\">\n            <li>Professional-grade equipment and techniques</li>\n            <li>Customized storytelling approach</li>\n            <li>Seamless brand alignment</li>\n            <li>Collaborative and creative process</li>\n        </ul>\n    </section>\n\n    <blockquote style=\"width: 100%; border-left: 5px solid #3498db; padding: 40px; margin: 48px 0; background-color: #ecf0f1; font-style: italic;\">\n        \"My Video transformed our corporate communication with stunning, impactful videos that truly represent our brand's vision.\" - Corporate Client\n    </blockquote>\n</main>" }} />
  );
}