import React from 'react';

interface GeneratedCorporateRatesViewProps {
  isContainer?: boolean;
}

export default function GeneratedCorporateRatesView({ isContainer = false }: GeneratedCorporateRatesViewProps){
  const useCard = false;
  return (
      <div className="rtext-content" dangerouslySetInnerHTML={{__html: "<section style=\"width: 100%; margin: 48px 0; padding: 48px; background-color: #f0f8ff;\">\n    <h1 style=\"font-size: 32px; margin-bottom: 32px;\">My Video: Corporate Videography Pricing</h1>\n    \n    <article style=\"width: 100%; padding: 40px; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); margin-bottom: 48px;\">\n        <h2 style=\"font-size: 24px; margin-bottom: 24px;\">Our Pricing Structure</h2>\n        \n        <div style=\"width: 100%; display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 32px; margin-bottom: 32px;\">\n            <div style=\"background-color: #2c3e50; color: #ffffff; padding: 32px; border-radius: 8px;\">\n                <h3 style=\"margin-bottom: 16px;\">Day Rates</h3>\n                <p style=\"line-height: 1.6;\">Standard full-day videography: $1,500 - $2,500<br>Half-day rates: $900 - $1,400</p>\n            </div>\n            \n            <div style=\"background-color: #0066cc; color: #ffffff; padding: 32px; border-radius: 8px;\">\n                <h3 style=\"margin-bottom: 16px;\">Project-Based Pricing</h3>\n                <p style=\"line-height: 1.6;\">Corporate video projects: $3,000 - $15,000<br>Complexity and length determine final pricing</p>\n            </div>\n            \n            <div style=\"background-color: #2ecc71; color: #ffffff; padding: 32px; border-radius: 8px;\">\n                <h3 style=\"margin-bottom: 16px;\">Retainer Options</h3>\n                <p style=\"line-height: 1.6;\">Monthly packages: $4,000 - $8,000<br>Includes multiple video productions</p>\n            </div>\n        </div>\n        \n        <div style=\"width: 100%; background-color: #ecf0f1; padding: 32px; border-radius: 8px; margin-top: 32px;\">\n            <h3 style=\"margin-bottom: 24px;\">Pricing Factors</h3>\n            <ul style=\"list-style-type: disc; padding-left: 32px; line-height: 1.6;\">\n                <li>Video length and complexity</li>\n                <li>Number of shooting days</li>\n                <li>Post-production editing requirements</li>\n                <li>Special equipment or locations</li>\n                <li>Number of team members required</li>\n            </ul>\n        </div>\n    </article>\n    \n    <div style=\"width: 100%; background-color: #1a1a1a; color: #ffffff; padding: 40px; border-radius: 12px; margin-top: 48px;\">\n        <h2 style=\"font-size: 24px; margin-bottom: 24px;\">Custom Consultation</h2>\n        <p style=\"line-height: 1.6;\">Every My Video project is unique. We offer personalized pricing consultations to match your specific corporate videography needs.</p>\n    </div>\n</section>" }} />
  );
}