import React from 'react';

interface GeneratedFounderStoryViewProps {
  isContainer?: boolean;
}

export default function GeneratedFounderStoryView({ isContainer = false }: GeneratedFounderStoryViewProps){
  const useCard = false;
  return (
      <div className="rtext-content" dangerouslySetInnerHTML={{__html: "<section class=\"founder-story\">\n    <h1>My Journey into Sound Healing: A Personal Transformation</h1>\n    \n    <h2>From Corporate Burnout to Vibrational Wellness</h2>\n    \n    <p>My name is Elena Rodriguez, founder of Vitalisona, and my path to sound healing began during a profound moment of personal crisis. After years of high-stress corporate work, I experienced complete emotional and physical exhaustion that traditional medical approaches couldn't resolve.</p>\n    \n    <p>During a transformative retreat in Peru, I was introduced to ancient sound healing techniques that fundamentally changed my understanding of holistic wellness. The resonant frequencies of traditional sound instruments—particularly Tibetan singing bowls and indigenous healing chimes—sparked a deep awakening within me.</p>\n    \n    <h2>Professional Training and Certification</h2>\n    \n    <p>Committed to understanding this healing modality scientifically and spiritually, I pursued rigorous training, including:</p>\n    \n    <ul>\n        <li>Advanced Sound Therapy Certification from the International Sound Healing Academy</li>\n        <li>Vibrational Medicine Diploma from the Global Wellness Institute</li>\n        <li>Specialized training in Neuroacoustic Sound Therapy</li>\n        <li>Extensive studies in traditional healing practices from indigenous sound practitioners</li>\n    </ul>\n    \n    <h2>The Vitalisona Philosophy</h2>\n    \n    <p>At Vitalisona, we believe that sound is more than just auditory experience—it's a profound healing mechanism that can realign the body's energetic systems. Our approach integrates scientific research with time-honored healing traditions, creating a holistic pathway to wellness.</p>\n    \n    <p>Each sound healing session is meticulously crafted to address individual physical, emotional, and spiritual needs. We use carefully selected instruments and frequencies to create therapeutic soundscapes that promote deep relaxation, stress reduction, and energetic rebalancing.</p>\n    \n    <h2>Our Mission</h2>\n    \n    <p>Vitalisona is dedicated to empowering individuals to reconnect with their innate healing potential through the transformative power of sound vibrations. We're not just offering a service; we're providing a journey of self-discovery and holistic restoration.</p>\n    \n    <p>My personal healing journey taught me that true wellness emerges when we listen—not just with our ears, but with our entire being. Through Vitalisona, I'm honored to guide others toward their own path of healing and transformation.</p>\n</section>" }} />
  );
}