import React from 'react';

interface GeneratedGarmentCareViewProps {
  isContainer?: boolean;
}

export default function GeneratedGarmentCareView({ isContainer = false }: GeneratedGarmentCareViewProps){
  const useCard = false;
  return (
      <div className="rtext-content" dangerouslySetInnerHTML={{__html: "<section style=\"width: 100%;\">\n    <div style=\"width: 100%; margin: 48px 0; padding: 40px;\">\n        <h1 style=\"font-size: 2.5rem; margin-bottom: 32px;\">Victorian Era Garment Care Guide</h1>\n        \n        <div style=\"background-color: #f4f1fc; padding: 48px; border-radius: 12px; margin-bottom: 48px;\">\n            <h2 style=\"margin-bottom: 24px;\">Preservation of Historical Costumes</h2>\n            <p style=\"line-height: 1.8; font-size: 18px;\">At Victorian Era, we understand the delicate nature of historical garments and offer comprehensive care instructions to help preserve these exquisite pieces of textile heritage.</p>\n        </div>\n\n        <div style=\"width: 100%; display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin-bottom: 48px;\">\n            <div style=\"background-color: #e6d9f5; padding: 40px; border-radius: 8px;\">\n                <h3 style=\"margin-bottom: 24px;\">Fabric Cleaning Techniques</h3>\n                <ul style=\"padding-left: 24px;\">\n                    <li style=\"padding: 16px 0; line-height: 1.6;\">Silk: Dry clean only, never machine wash</li>\n                    <li style=\"padding: 16px 0; line-height: 1.6;\">Wool: Gentle hand wash with specialized detergent</li>\n                    <li style=\"padding: 16px 0; line-height: 1.6;\">Cotton: Mild temperature, low agitation washing</li>\n                </ul>\n            </div>\n\n            <div style=\"background-color: #e6d9f5; padding: 40px; border-radius: 8px;\">\n                <h3 style=\"margin-bottom: 24px;\">Storage Recommendations</h3>\n                <ol style=\"padding-left: 24px;\">\n                    <li style=\"padding: 16px 0; line-height: 1.6;\">Use acid-free tissue paper</li>\n                    <li style=\"padding: 16px 0; line-height: 1.6;\">Store in climate-controlled environments</li>\n                    <li style=\"padding: 16px 0; line-height: 1.6;\">Avoid direct sunlight and humidity</li>\n                </ol>\n            </div>\n        </div>\n\n        <div style=\"background-color: #f4f1fc; padding: 48px; border-radius: 12px; margin-bottom: 48px;\">\n            <h2>Delicate Embellishment Care</h2>\n            <p style=\"line-height: 1.8; font-size: 18px;\">Victorian Era costumes often feature intricate trims and decorative elements requiring specialized handling. Use soft brushes and avoid direct contact with metal cleaning implements.</p>\n        </div>\n    </div>\n</section>" }} />
  );
}