import React from 'react';

interface GeneratedOurStoryViewProps {
  isContainer?: boolean;
}

export default function GeneratedOurStoryView({ isContainer = false }: GeneratedOurStoryViewProps){
  const useCard = false;
  return (
      <div className="rtext-content" dangerouslySetInnerHTML={{__html: "<section style=\"width: 100%;\">\n    <div style=\"width: 100%; margin: 48px 0; padding: 40px;\">\n        <h1 style=\"font-size: 2.5rem; margin-bottom: 32px;\">Victorian Era: Preserving Historical Fashion</h1>\n        \n        <div style=\"background-color: #fefbff; padding: 40px; border-radius: 12px; margin-bottom: 48px;\">\n            <h2 style=\"font-size: 1.8rem; margin-bottom: 24px;\">Our Authentic Commitment</h2>\n            <p style=\"font-size: 18px; line-height: 1.8; margin-bottom: 24px;\">Victorian Era represents the pinnacle of historical costume reproduction, meticulously crafting garments that honor the intricate details of 19th-century British fashion. Our dedicated team of researchers and artisans spend countless hours studying original textile archives, museum collections, and historical documents to ensure unparalleled authenticity in every stitch and seam.</p>\n        </div>\n\n        <div style=\"background-color: #fefbff; padding: 40px; border-radius: 12px; margin-bottom: 48px;\">\n            <h2 style=\"font-size: 1.8rem; margin-bottom: 24px;\">Craftsmanship Beyond Compare</h2>\n            <p style=\"font-size: 18px; line-height: 1.8; margin-bottom: 24px;\">At Victorian Era, we source only the finest materials: hand-woven cotton from traditional British mills, silk from renowned European producers, and intricate lace crafted using 19th-century techniques. Our master tailors and seamstresses employ traditional construction methods, including hand-stitching, boning, and elaborate embellishment techniques that were standard during Queen Victoria's reign.</p>\n        </div>\n\n        <div style=\"background-color: #fefbff; padding: 40px; border-radius: 12px;\">\n            <h2 style=\"font-size: 1.8rem; margin-bottom: 24px;\">Bringing History to Life</h2>\n            <p style=\"font-size: 18px; line-height: 1.8;\">More than a clothing store, Victorian Era is a portal to the past. We understand that each garment tells a story—from morning walking dresses to elaborate evening gowns. Our collection allows historians, performers, and fashion enthusiasts to experience the elegance and complexity of Victorian-era clothing with unprecedented accuracy and reverence.</p>\n        </div>\n    </div>\n</section>" }} />
  );
}