import React from 'react';

interface GeneratedServicesOverviewViewProps {
  isContainer?: boolean;
}

export default function GeneratedServicesOverviewView({ isContainer = false }: GeneratedServicesOverviewViewProps){
  const useCard = false;
  return (
      <div className="rtext-content" dangerouslySetInnerHTML={{__html: "<section style=\"width: 100%; margin: 48px 0; padding: 48px; background-color: #f0f8ff;\">\n    <h1 style=\"font-size: 36px; margin-bottom: 32px;\">My Video: Capturing Your Story Through Professional Videography</h1>\n    \n    <article style=\"width: 100%; padding: 40px; background-color: #2c3e50; color: #ffffff; border-radius: 12px; margin-bottom: 32px;\">\n        <h2 style=\"font-size: 28px; margin-bottom: 24px;\">Our Comprehensive Videography Services</h2>\n        \n        <p style=\"font-size: 18px; line-height: 1.6; margin-bottom: 24px;\">\n            At My Video, we transform moments into timeless visual narratives across multiple domains, bringing professional expertise and creative vision to every project.\n        </p>\n        \n        <div style=\"display: grid; grid-template-columns: repeat(2, 1fr); gap: 24px; width: 100%;\">\n            <div style=\"background-color: #3498db; padding: 32px; border-radius: 8px;\">\n                <h3 style=\"margin-bottom: 16px;\">Wedding Cinematography</h3>\n                <p>Elegant, cinematic coverage of your most precious day, preserving every emotional moment with artistic precision.</p>\n            </div>\n            \n            <div style=\"background-color: #1abc9c; padding: 32px; border-radius: 8px;\">\n                <h3 style=\"margin-bottom: 16px;\">Corporate Event Documentation</h3>\n                <p>Professional video production that captures the essence of corporate gatherings, conferences, and brand storytelling.</p>\n            </div>\n        </div>\n    </article>\n    \n    <div style=\"width: 100%; background-color: #34495e; color: #ffffff; padding: 40px; border-radius: 12px;\">\n        <h2 style=\"font-size: 28px; margin-bottom: 24px;\">Why Choose My Video?</h2>\n        \n        <ul style=\"list-style: none; padding: 0;\">\n            <li style=\"padding: 16px 0; border-bottom: 1px solid rgba(255,255,255,0.2);\">✦ Cutting-edge equipment and technical expertise</li>\n            <li style=\"padding: 16px 0; border-bottom: 1px solid rgba(255,255,255,0.2);\">✦ Personalized approach tailored to your unique vision</li>\n            <li style=\"padding: 16px 0;\">✦ Versatile experience across multiple videography domains</li>\n        </ul>\n    </div>\n</section>" }} />
  );
}