/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const specialization = searchParams.get('specialization');
    const availableParam = searchParams.get('available');
    const minExperienceParam = searchParams.get('min_experience');
    const pageParam = searchParams.get('page');
    const limitParam = searchParams.get('limit');

    // Parse and validate parameters
    const available = availableParam ? availableParam === 'true' : null;
    const minExperience = minExperienceParam ? parseInt(minExperienceParam) : null;
    const page = pageParam ? Math.max(1, parseInt(pageParam)) : 1;
    const limit = limitParam ? Math.max(1, Math.min(100, parseInt(limitParam))) : 10;
    const offset = (page - 1) * limit;

    // Build WHERE conditions with proper parameter tracking
    let paramIndex = 1;
    let queryParams = [];
    let whereConditions = [];

    // Filter by specialization (LIKE search in specializations field)
    if (specialization) {
      whereConditions.push("specializations LIKE ?");
      queryParams.push(`%${specialization}%`);
      paramIndex++;
    }

    // Filter by availability
    if (available !== null) {
      whereConditions.push("available = ?");
      queryParams.push(available);
      paramIndex++;
    }

    // Filter by minimum experience
    if (minExperience !== null) {
      whereConditions.push("experience_years >= ?");
      queryParams.push(minExperience);
      paramIndex++;
    }

    // Build WHERE clause
    const whereClause = whereConditions.length > 0 ? "WHERE " + whereConditions.join(" AND ") : "";

    // Get total count
    const countQuery = `SELECT COUNT(*) as total FROM practitioners ${whereClause}`;
    const countResult = await db_query(db, countQuery, queryParams);
    const total = countResult[0].total;

    // Calculate total pages
    const totalpages = Math.ceil(total / limit);

    // Get paginated data
    const dataQuery = `
      SELECT 
        id, 
        name, 
        bio, 
        specializations, 
        certifications, 
        experience_years, 
        profile_image, 
        email, 
        phone, 
        available, 
        display_order
      FROM practitioners 
      ${whereClause}
      ORDER BY display_order ASC, name ASC
      LIMIT ? OFFSET ?
    `;
    
    // Create final parameter array for data query
    const finalParams = [...queryParams, limit, offset];
    const practitioners = await db_query(db, dataQuery, finalParams);

    // Format the response data
    const data = practitioners.map(practitioner => ({
      id: practitioner.id,
      name: practitioner.name,
      bio: practitioner.bio,
      specializations: practitioner.specializations,
      certifications: practitioner.certifications,
      experience_years: practitioner.experience_years,
      profile_image: practitioner.profile_image,
      email: practitioner.email,
      phone: practitioner.phone,
      available: practitioner.available,
      display_order: practitioner.display_order
    }));

    const result = {
      data: data,
      total: total,
      page: page,
      limit: limit,
      totalpages: totalpages
    };

    return NextResponse.json(result);

  } catch (error) {
    console.error('Error fetching practitioners:', error);
    return NextResponse.json(
      { error: 'Failed to fetch practitioners' }, 
      { status: 500 }
    );
  }
}
