/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse and validate request parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required fields
    if (!id) {
      return NextResponse.json({ error: 'Entry ID is required for Vitalisona wellness journal retrieval' }, { status: 400 });
    }
    
    // Query the wellnessjournal table for the specific entry
    const query = `
      SELECT id, entry_date, mood_rating, energy_level, stress_level, sleep_quality, 
             notes, session_feedback, goals, created_at
      FROM wellnessjournal 
      WHERE id = ? AND userid = ?
    `;
    
    const entries = await db_query(db, query, [id, user_id]);
    
    // Check if entry exists and belongs to the user
    if (!entries || entries.length === 0) {
      return NextResponse.json({ error: 'Wellness journal entry not found or access denied' }, { status: 404 });
    }
    
    const entry = entries[0];
    
    // Format the response according to the output interface
    const result = {
      id: entry.id,
      entry_date: entry.entry_date,
      mood_rating: entry.mood_rating,
      energy_level: entry.energy_level,
      stress_level: entry.stress_level,
      sleep_quality: entry.sleep_quality,
      notes: entry.notes,
      session_feedback: entry.session_feedback,
      goals: entry.goals,
      created_at: entry.created_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona wellness journal retrieval error:', error);
    return NextResponse.json({ error: 'Failed to retrieve wellness journal entry from Vitalisona system' }, { status: 500 });
  }
}
