
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.id) {
      return NextResponse.json({ error: 'Address ID is required' }, { status: 400 });
    }
    
    // First, check if the address exists and belongs to the user
    const existingAddress = await db_query(db, 
      "SELECT * FROM addresses WHERE id = ? AND userid = ?", 
      [body.id, user_id]
    );
    
    if (!existingAddress || existingAddress.length === 0) {
      return NextResponse.json({ error: 'Address not found or access denied' }, { status: 404 });
    }
    
    // If setting this address as default, first unset all other defaults for this user
    if (body.is_default === true) {
      await db_query(db, 
        "UPDATE addresses SET is_default = ? WHERE userid = ? AND id != ?", 
        [false, user_id, body.id]
      );
    }
    
    // Build update query for provided fields
    const updateFields = [];
    const updateParams = [];
    
    if (body.type !== undefined) {
      updateFields.push("type = ?");
      updateParams.push(body.type);
    }
    if (body.first_name !== undefined) {
      updateFields.push("first_name = ?");
      updateParams.push(body.first_name);
    }
    if (body.last_name !== undefined) {
      updateFields.push("last_name = ?");
      updateParams.push(body.last_name);
    }
    if (body.company !== undefined) {
      updateFields.push("company = ?");
      updateParams.push(body.company);
    }
    if (body.address_line_1 !== undefined) {
      updateFields.push("address_line_1 = ?");
      updateParams.push(body.address_line_1);
    }
    if (body.address_line_2 !== undefined) {
      updateFields.push("address_line_2 = ?");
      updateParams.push(body.address_line_2);
    }
    if (body.city !== undefined) {
      updateFields.push("city = ?");
      updateParams.push(body.city);
    }
    if (body.state_province !== undefined) {
      updateFields.push("state_province = ?");
      updateParams.push(body.state_province);
    }
    if (body.postal_code !== undefined) {
      updateFields.push("postal_code = ?");
      updateParams.push(body.postal_code);
    }
    if (body.country !== undefined) {
      updateFields.push("country = ?");
      updateParams.push(body.country);
    }
    if (body.phone !== undefined) {
      updateFields.push("phone = ?");
      updateParams.push(body.phone);
    }
    if (body.is_default !== undefined) {
      updateFields.push("is_default = ?");
      updateParams.push(body.is_default);
    }
    
    // Always update the updated_at timestamp
    updateFields.push("updated_at = CURRENT_TIMESTAMP");
    
    // Perform update if there are fields to update
    if (updateFields.length > 0) {
      const updateQuery = `UPDATE addresses SET ${updateFields.join(', ')} WHERE id = ? AND userid = ?`;
      updateParams.push(body.id, user_id);
      
      await db_query(db, updateQuery, updateParams);
    }
    
    // Fetch and return the updated address
    const updatedAddress = await db_query(db, 
      "SELECT * FROM addresses WHERE id = ? AND userid = ?", 
      [body.id, user_id]
    );
    
    if (!updatedAddress || updatedAddress.length === 0) {
      return NextResponse.json({ error: 'Failed to retrieve updated address' }, { status: 500 });
    }
    
    const address = updatedAddress[0];
    
    const result = {
      id: address.id,
      type: address.type,
      first_name: address.first_name,
      last_name: address.last_name,
      company: address.company,
      address_line_1: address.address_line_1,
      address_line_2: address.address_line_2,
      city: address.city,
      state_province: address.state_province,
      postal_code: address.postal_code,
      country: address.country,
      phone: address.phone,
      is_default: address.is_default,
      created_at: address.created_at,
      updated_at: address.updated_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

