
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import TermsOfService from '@/custom/Terms_of_Service';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Terms of  Service',
    description: 'Legal terms and conditions for using the application',
    openGraph: {
        title: 'Terms of  Service',
        description: 'Legal terms and conditions for using the application',
        url: '/terms_of_service',
        siteName: 'TechCorp'
    },
};

export default  function terms_of_service() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Terms of  Service","link":"/terms_of_service"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col"><TermsOfService />
                        </div>
                    </div>
            </main>
        </div>
    );
}