
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse dress ID from URL or query parameters
    const url = new URL(request.url);
    const dressId = url.searchParams.get('id');
    
    // Validate required input
    if (!dressId) {
      return NextResponse.json({ 
        success: false, 
        message: 'Dress ID is required' 
      }, { status: 400 });
    }
    
    // Check if dress exists
    const dressCheck = await db_query(db, 
      "SELECT id FROM dresses WHERE id = ?", 
      [dressId]
    );
    
    if (dressCheck.length === 0) {
      return NextResponse.json({ 
        success: false, 
        message: 'Dress not found' 
      }, { status: 404 });
    }
    
    // Check for active orders containing this dress
    // Active orders are those not in 'cancelled', 'refunded', or 'returned' status
    const activeOrdersCheck = await db_query(db,
      `SELECT COUNT(*) as count 
       FROM orderitems oi 
       JOIN orders o ON oi.ordersid = o.id 
       WHERE oi.dressesid = ? 
       AND o.status NOT IN ('cancelled', 'refunded', 'returned')`,
      [dressId]
    );
    
    if (activeOrdersCheck[0].count > 0) {
      return NextResponse.json({ 
        success: false, 
        message: 'Cannot delete dress - it is referenced in active orders' 
      }, { status: 400 });
    }
    
    // Delete associated dress images first (foreign key constraint)
    await db_query(db, 
      "DELETE FROM dressimages WHERE dressesid = ?", 
      [dressId]
    );
    
    // Delete the dress
    const deleteResult = await db_query(db, 
      "DELETE FROM dresses WHERE id = ?", 
      [dressId]
    );
    
    if (deleteResult.changes === 0) {
      return NextResponse.json({ 
        success: false, 
        message: 'Failed to delete dress' 
      }, { status: 500 });
    }
    
    const result = {
      success: true,
      message: 'Dress and associated images deleted successfully'
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error deleting dress:', error);
    const result = {
      success: false,
      message: 'Internal server error occurred while deleting dress'
    };
    return NextResponse.json(result, { status: 500 });
  }
}

