
/*
SysArchitect v1.0.0
WARNING: This file is automatically generated and should not be modified.
*/ 

import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

// COMPANYNAME 
const companyName = "TechCorp";
// ENDCOMPANYNAME

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="classFontSize classFontType">
        <Header companyName={companyName} />
        {children}
        <Footer companyName={companyName} />
      </body>
    </html>
  );
}