
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import HeroBanner from '@/custom/Hero_Banner';
import WelcomeMessage from '@/custom/Welcome_Message';
import List from '@/components/list';
import MarketingBlurb from '@/custom/Marketing_Blurb';


export const metadata: Metadata = {
    title: 'Home',
    description: 'Home Page',
    openGraph: {
        title: 'Home',
        description: 'Home Page',
        url: '/home',
        siteName: 'TechCorp'
    },
};

export default  function home() {
    
    return (
        <div className="page">
            <main>
                
                
                    <div className="row">
                        <div className="col"><HeroBanner />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col"><WelcomeMessage />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col">    
                            <List 
                                modelName="Category"
                                showAdminFeatures={false}
                                nameField="category_name"
                                
                            />
                        </div>
                        <div className="col">    
                            <List 
                                modelName="CompanyProfile"
                                showAdminFeatures={false}
                                nameField="company_name"
                                
                            />
                        </div>
                        <div className="col">    
                            <List 
                                modelName="JobListing"
                                showAdminFeatures={false}
                                nameField="job_title"
                                
                            />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col"><MarketingBlurb />
                        </div>
                    </div>
            </main>
        </div>
    );
}