/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  // Parse and validate request body
  const body = await request.json();
  
  // Validate required fields
  const { ordersid, productsid, product_name, quantity, unit_price, total_price } = body;
  
  if (!ordersid || !productsid || !product_name || !quantity || !unit_price || !total_price) {
    return NextResponse.json({ error: 'Missing required fields for Victorian Era order item' }, { status: 400 });
  }
  
  // Validate numeric fields
  if (typeof quantity !== 'number' || quantity <= 0) {
    return NextResponse.json({ error: 'Invalid quantity for Victorian Era order item' }, { status: 400 });
  }
  
  if (typeof unit_price !== 'number' || unit_price < 0) {
    return NextResponse.json({ error: 'Invalid unit price for Victorian Era order item' }, { status: 400 });
  }
  
  if (typeof total_price !== 'number' || total_price < 0) {
    return NextResponse.json({ error: 'Invalid total price for Victorian Era order item' }, { status: 400 });
  }
  
  try {
    // Validate order exists, belongs to user, and has pending status
    const orderQuery = await db_query(
      db,
      "SELECT id, status, subtotal, total FROM orders WHERE id = $1 AND userid = $2",
      [ordersid, user_id]
    );
    
    if (orderQuery.length === 0) {
      return NextResponse.json({ error: 'Order not found or access denied for Victorian Era order' }, { status: 404 });
    }
    
    const order = orderQuery[0];
    
    if (order.status !== 'pending') {
      return NextResponse.json({ error: 'Victorian Era order cannot be modified. Only pending orders can be updated.' }, { status: 400 });
    }
    
    // Validate product exists and is available
    const productQuery = await db_query(
      db,
      "SELECT id, available FROM products WHERE id = $1",
      [productsid]
    );
    
    if (productQuery.length === 0) {
      return NextResponse.json({ error: 'Product not found in Victorian Era catalog' }, { status: 404 });
    }
    
    const product = productQuery[0];
    
    if (!product.available) {
      return NextResponse.json({ error: 'Product is not available for Victorian Era orders' }, { status: 400 });
    }
    
    // Generate UUID for new order item
    const newItemId = crypto.randomUUID();
    
    // Get optional fields
    const size = body.size || null;
    const color = body.color || null;
    
    // Insert new order item
    await db_query(
      db,
      "INSERT INTO orderitems (id, ordersid, productsid, product_name, quantity, unit_price, total_price, size, color) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)",
      [newItemId, ordersid, productsid, product_name, quantity, unit_price, total_price, size, color]
    );
    
    // Calculate new order totals
    const newSubtotal = parseFloat(order.subtotal) + parseFloat(total_price);
    const newTotal = parseFloat(order.total) + parseFloat(total_price);
    
    // Update order totals
    await db_query(
      db,
      "UPDATE orders SET subtotal = $1, total = $2 WHERE id = $3",
      [newSubtotal, newTotal, ordersid]
    );
    
    // Prepare result
    const result = {
      id: newItemId,
      ordersid: ordersid,
      productsid: productsid,
      product_name: product_name,
      quantity: quantity,
      unit_price: unit_price,
      total_price: total_price,
      size: size,
      color: color
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Victorian Era order item creation error:', error);
    return NextResponse.json({ error: 'Failed to add item to Victorian Era order' }, { status: 500 });
  }
}
