/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  // Parse request body
  const body = await request.json();
  
  // Validate required fields
  if (!body.categoriesid || !body.name || !body.description || body.price === undefined || body.price === null || body.stock_quantity === undefined || body.stock_quantity === null) {
    return NextResponse.json({ error: 'Missing required fields: categoriesid, name, description, price, and stock_quantity are required' }, { status: 400 });
  }
  
  // Validate that categoriesid references an existing category
  const categoryCheck = await db_query(db, "SELECT id FROM categories WHERE id = $1", [body.categoriesid]);
  
  if (!categoryCheck || categoryCheck.length === 0) {
    return NextResponse.json({ error: 'Invalid categoriesid: category does not exist' }, { status: 400 });
  }
  
  // Generate UUID for new product
  const productId = crypto.randomUUID();
  
  // Set default values
  const available = body.available !== undefined ? body.available : true;
  const featured = body.featured !== undefined ? body.featured : false;
  
  // Prepare insert query
  const insertQuery = `
    INSERT INTO products (
      id, categoriesid, name, description, price, sku, stock_quantity, 
      size, color, material, era_period, care_instructions, available, featured
    ) VALUES (
      $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
    )
  `;
  
  const insertParams = [
    productId,
    body.categoriesid,
    body.name,
    body.description,
    body.price,
    body.sku || null,
    body.stock_quantity,
    body.size || null,
    body.color || null,
    body.material || null,
    body.era_period || null,
    body.care_instructions || null,
    available,
    featured
  ];
  
  try {
    await db_query(db, insertQuery, insertParams);
    
    // Retrieve the newly created product
    const newProduct = await db_query(db, "SELECT * FROM products WHERE id = $1", [productId]);
    
    if (!newProduct || newProduct.length === 0) {
      return NextResponse.json({ error: 'Failed to retrieve newly created product' }, { status: 500 });
    }
    
    const product = newProduct[0];
    
    // Format response according to output interface
    const result = {
      id: product.id,
      categoriesid: product.categoriesid,
      name: product.name,
      description: product.description,
      price: product.price,
      sku: product.sku,
      stock_quantity: product.stock_quantity,
      size: product.size,
      color: product.color,
      material: product.material,
      era_period: product.era_period,
      care_instructions: product.care_instructions,
      available: product.available,
      featured: product.featured
    };
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create product: ' + error.message }, { status: 500 });
  }
}
