
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse and validate request parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required fields
    if (!id) {
      return NextResponse.json({ error: 'Address ID is required' }, { status: 400 });
    }
    
    // Query the address with user restriction
    const addressQuery = `
      SELECT id, type, first_name, last_name, company, address_line_1, address_line_2, 
             city, state_province, postal_code, country, phone, is_default, 
             created_at, updated_at
      FROM addresses 
      WHERE id = ? AND userid = ?
    `;
    
    const addressResults = await db_query(db, addressQuery, [id, user_id]);
    
    if (!addressResults || addressResults.length === 0) {
      return NextResponse.json({ error: 'Address not found' }, { status: 404 });
    }
    
    const address = addressResults[0];
    
    // Format response according to output interface
    const result = {
      id: address.id,
      type: address.type,
      first_name: address.first_name,
      last_name: address.last_name,
      company: address.company,
      address_line_1: address.address_line_1,
      address_line_2: address.address_line_2,
      city: address.city,
      state_province: address.state_province,
      postal_code: address.postal_code,
      country: address.country,
      phone: address.phone,
      is_default: Boolean(address.is_default),
      created_at: address.created_at,
      updated_at: address.updated_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error retrieving address:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

