/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    const body = await request.json();
    
    if (!body.name || !body.email || !body.subject || !body.message) {
      return NextResponse.json(
        { error: 'Victorian Era: Name, email, subject, and message are required' },
        { status: 400 }
      );
    }
    
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(body.email)) {
      return NextResponse.json(
        { error: 'Victorian Era: Invalid email format' },
        { status: 400 }
      );
    }
    
    const messageId = crypto.randomUUID();
    const submittedDate = new Date().toISOString();
    
    const insertQuery = `
      INSERT INTO contactmessages (
        id, name, email, phone, subject, message, submitted_date, responded, response_notes
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      RETURNING *
    `;
    
    const insertParams = [
      messageId,
      body.name,
      body.email,
      body.phone || null,
      body.subject,
      body.message,
      submittedDate,
      false,
      null
    ];
    
    const insertResult = await db_query(db, insertQuery, insertParams);
    
    if (!insertResult || insertResult.length === 0) {
      return NextResponse.json(
        { error: 'Victorian Era: Failed to create contact message' },
        { status: 500 }
      );
    }
    
    const createdMessage = insertResult[0];
    
    try {
      const emailApiKey = process.env.SENDGRID_API_KEY;
      const adminEmail = process.env.ADMIN_EMAIL;
      
      if (emailApiKey && adminEmail) {
        const emailResponse = await fetch('https://api.sendgrid.com/v3/mail/send', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${emailApiKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            personalizations: [{
              to: [{ email: adminEmail }]
            }],
            from: { 
              email: 'noreply@victorianera.com',
              name: 'Victorian Era Contact Form'
            },
            subject: `Victorian Era: New Contact Message - ${body.subject}`,
            content: [{
              type: 'text/html',
              value: `
                <h2>New Contact Message Received</h2>
                <p><strong>Name:</strong> ${body.name}</p>
                <p><strong>Email:</strong> ${body.email}</p>
                <p><strong>Phone:</strong> ${body.phone || 'Not provided'}</p>
                <p><strong>Subject:</strong> ${body.subject}</p>
                <p><strong>Message:</strong></p>
                <p>${body.message.replace(/\n/g, '<br>')}</p>
                <p><strong>Submitted:</strong> ${submittedDate}</p>
              `
            }]
          })
        });
        
        if (!emailResponse.ok) {
          console.error('Victorian Era: Failed to send notification email to admin');
        }
      }
    } catch (emailError) {
      console.error('Victorian Era: Error sending notification email:', emailError);
    }
    
    const result = {
      id: createdMessage.id,
      name: createdMessage.name,
      email: createdMessage.email,
      subject: createdMessage.subject,
      message: createdMessage.message,
      submitted_date: createdMessage.submitted_date,
      responded: createdMessage.responded
    };
    
    if (createdMessage.phone) {
      result.phone = createdMessage.phone;
    }
    
    if (createdMessage.response_notes) {
      result.response_notes = createdMessage.response_notes;
    }
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Victorian Era: Error creating contact message:', error);
    return NextResponse.json(
      { error: 'Victorian Era: Failed to process contact message' },
      { status: 500 }
    );
  }
}
