
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { db_add, db_update, db_select, db_delete, db_init } from '../../../database/supabase';


function validate(data: Record<string, any>): string[] {
    const errors: string[] = [];


    if (typeof data.job_title !== 'string') {
        errors.push("job_title must be a string");
    }
    if (data.job_title.length === 0) {
        errors.push("job_title is required");
    }
                    
    if (data.job_title.length > 255) {
        errors.push("job_title exceeds maximum length of 255");
    }



    if (typeof data.job_description !== 'string') {
        errors.push("job_description must be a string")
    }



    if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(data.ID)) {
        errors.push("ID must be a valid UUID");
    }



    if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(data.EmployerProfileID)) {
        errors.push("EmployerProfileID must be a valid UUID");
    }



    if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(data.CategoryID)) {
        errors.push("CategoryID must be a valid UUID");
    }


    return errors; 
}
        
export async function GET(request: NextRequest): Promise<NextResponse> {
    const db = await db_init();
    // Get request data from query string
    const url = new URL(request.url);
    const fields = Object.fromEntries(url.searchParams);

     let whereClause = null;   
    if (fields.subname && fields.subvalue) {
        if (whereClause) {
            whereClause = [...whereClause, { field: fields.subname, op: 'eq', value: fields.subvalue }];
        }
        else {
            whereClause = [{ field: fields.subname, op: 'eq', value: fields.subvalue }];
        }
    }
    let result = await db_select(db, 'JobListing', ['*'], fields.uuids.split(','), whereClause, fields.limit ? parseInt(fields.limit) : undefined, fields.skip ? parseInt(fields.skip) : undefined);
                    
    return NextResponse.json(result);
}
            
export async function DELETE(request: NextRequest): Promise<NextResponse> {
    const db = await db_init();
    // Get request data from JSON body
    let fields: Record<string, any>;
    try {
        fields = await request.json();
    } catch (err) {
        return NextResponse.json({ errors: ['Invalid JSON data '+err] }, { status: 400 });
    }

    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    
    if (UserInfo.UserLevel < -1) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    
    let whereClause = null
    let resultd = await db_select(db, 'JobListing', ['ID'], [fields.uuids], whereClause, undefined, undefined);
    if (resultd.length === 0) {
        return NextResponse.json({ error: "Record not found" }, { status: 404 });
    }
    const uuids = fields.uuids;
    let result = await db_delete(db, 'JobListing', uuids);
                    
    return NextResponse.json(result);
}
            
export async function POST(request: NextRequest): Promise<NextResponse> {
    const db = await db_init();
    // Get request data from JSON body
    let fields: Record<string, any>;
    try {
        fields = await request.json();
    } catch (err) {
        return NextResponse.json({ errors: ['Invalid JSON data '+err] }, { status: 400 });
    }

    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    
    if (UserInfo.UserLevel < -1) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    
    const errors = validate(fields);
    if (errors.length > 0) {
        return NextResponse.json({ errors }, { status: 400 });
    }
    let result = await db_add(db, 'JobListing', fields);
                    
    return NextResponse.json(result);
}
            
export async function PUT(request: NextRequest): Promise<NextResponse> {
    const db = await db_init();
    // Get request data from JSON body
    let fields: Record<string, any>;
    try {
        fields = await request.json();
    } catch (err) {
        return NextResponse.json({ errors: ['Invalid JSON data '+err] }, { status: 400 });
    }

    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    
    if (UserInfo.UserLevel < -1) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    
    const errors = validate(fields);
    if (errors.length > 0) {
        return NextResponse.json({ errors }, { status: 400 });
    }
    let whereClause = null
    let resultd = await db_select(db, 'JobListing', ['ID'], [fields.ID], whereClause, undefined, undefined);
    if (resultd.length === 0) {
        return NextResponse.json({ error: "Record not found" }, { status: 404 });
    }
    let result = await db_update(db, 'JobListing', fields, [fields.ID]);
                    
    return NextResponse.json(result);
}
            