
/* 
This file is generated by Sitepaige. 
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import HeaderLoggedIn2View from '@/views/Header__Logged_In__2';
import AppointmentBookingView from '@/views/Appointment_Booking';
import CalendarIntegrationView from '@/views/Calendar_Integration';
import FooterMenuView from '@/views/Footer_Menu';
import CopyrightView from '@/views/Copyright';

export const metadata: Metadata = {
    title: 'Book  Session',
    description: 'Session booking and appointment scheduling',
    openGraph: {
        title: 'Book  Session',
        description: 'Session booking and appointment scheduling',
        url: '/book_session',
        siteName: 'Vitalisona'
    },
};

export default  function book_session() {
    
    return (
        <div className="page" style={{ minHeight: '75vh' }}>
            <main>
                
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ paddingLeft: '5px', paddingRight: '10px', paddingTop: '2px', display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <HeaderLoggedIn2View />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-8" style={{ paddingLeft: '8px', paddingRight: '8px', paddingTop: '8px', paddingBottom: '8px', display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <AppointmentBookingView />
                            </ErrorBoundary>      </div>
                        </div>
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-4" style={{ paddingLeft: '8px', paddingRight: '8px', paddingTop: '8px', paddingBottom: '8px', display: 'grid', placeItems: 'center center' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <CalendarIntegrationView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ paddingLeft: '5px', paddingRight: '10px', paddingTop: '25px', paddingBottom: '10px', display: 'grid', placeItems: 'start start', textAlign: 'left', justifyContent: 'start' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <FooterMenuView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
                    <div className="h-full gap-4 grid grid-cols-12 relative">
                        <div className="h-full w-full col-span-12 md:col-span-12 lg:col-span-12" style={{ paddingLeft: '5px', paddingRight: '10px', paddingBottom: '25px', display: 'grid', placeItems: 'center center', textAlign: 'left', justifyContent: 'start' }}>
                          <div className="w-full">
                            <ErrorBoundary fallback={<Error />}>
                                <CopyrightView />
                            </ErrorBoundary>      </div>
                        </div>
                    </div>
            </main>
        </div>
    );
}