
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.title) {
      return NextResponse.json({ error: 'Title is required for Vitalisona wellness resource creation' }, { status: 400 });
    }
    
    if (!body.content) {
      return NextResponse.json({ error: 'Content is required for Vitalisona wellness resource creation' }, { status: 400 });
    }
    
    if (!body.category) {
      return NextResponse.json({ error: 'Category is required for Vitalisona wellness resource creation' }, { status: 400 });
    }
    
    if (!body.published_date) {
      return NextResponse.json({ error: 'Published date is required for Vitalisona wellness resource creation' }, { status: 400 });
    }
    
    if (typeof body.published !== 'boolean') {
      return NextResponse.json({ error: 'Published status is required for Vitalisona wellness resource creation' }, { status: 400 });
    }
    
    if (typeof body.featured !== 'boolean') {
      return NextResponse.json({ error: 'Featured status is required for Vitalisona wellness resource creation' }, { status: 400 });
    }
    
    // Generate new UUID for the resource
    const resourceId = crypto.randomUUID();
    
    // Handle featured image if provided
    let featuredImageRef = null;
    if (body.featured_image) {
      try {
        featuredImageRef = await store_file(`wellness-resource-${resourceId}.jpg`, body.featured_image, true);
      } catch (error) {
        return NextResponse.json({ error: 'Failed to store featured image for Vitalisona wellness resource' }, { status: 500 });
      }
    }
    
    // Insert the new wellness resource into the database
    const insertQuery = `
      INSERT INTO wellnessresources (
        id, title, content, category, author, published_date, tags, 
        featured_image, published, featured, display_order
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `;
    
    const insertParams = [
      resourceId,
      body.title,
      body.content,
      body.category,
      body.author || null,
      body.published_date,
      body.tags || null,
      featuredImageRef,
      body.published,
      body.featured,
      body.display_order || null
    ];
    
    await db_query(db, insertQuery, insertParams);
    
    // Retrieve the created resource to return
    const selectQuery = 'SELECT * FROM wellnessresources WHERE id = ?';
    const createdResource = await db_query(db, selectQuery, [resourceId]);
    
    if (!createdResource || createdResource.length === 0) {
      return NextResponse.json({ error: 'Failed to create Vitalisona wellness resource' }, { status: 500 });
    }
    
    const resource = createdResource[0];
    
    const result = {
      id: resource.id,
      title: resource.title,
      content: resource.content,
      category: resource.category,
      author: resource.author,
      published_date: resource.published_date,
      tags: resource.tags,
      featured_image: resource.featured_image,
      published: resource.published,
      featured: resource.featured,
      display_order: resource.display_order
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona wellness resource creation error:', error);
    return NextResponse.json({ error: 'Internal server error while creating Vitalisona wellness resource' }, { status: 500 });
  }
}

