/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  let is_admin = false;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  // Parse query parameters
  const { searchParams } = new URL(request.url);
  const orderId = searchParams.get('id');
  
  // Validate required fields
  if (!orderId) {
    return NextResponse.json({ error: 'Order ID is required' }, { status: 400 });
  }
  
  try {
    // Query the order
    const orderQuery = "SELECT * FROM orders WHERE id = $1";
    const orderResult = await db_query(db, orderQuery, [orderId]);
    
    if (orderResult.length === 0) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }
    
    const order = orderResult[0];
    
    // Verify access: admins can view any order, regular users only their own
    if (!is_admin && user_id && order.userid !== user_id) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }
    
    // Query order items for this order
    const itemsQuery = "SELECT * FROM orderitems WHERE ordersid = $1 ORDER BY id";
    const itemsResult = await db_query(db, itemsQuery, [orderId]);
    
    // For each item, get the primary product image
    const items = [];
    for (const item of itemsResult) {
      // Get primary product image
      const imageQuery = "SELECT image_url FROM productimages WHERE productsid = $1 AND is_primary = $2 ORDER BY id LIMIT 1";
      const imageResult = await db_query(db, imageQuery, [item.productsid, true]);
      
      const productImageUrl = imageResult.length > 0 ? imageResult[0].image_url : null;
      
      items.push({
        id: item.id,
        productsid: item.productsid,
        product_name: item.product_name,
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.total_price,
        size: item.size || null,
        color: item.color || null,
        product_image_url: productImageUrl
      });
    }
    
    // Format the result according to output interface
    const result = {
      id: order.id,
      order_number: order.order_number,
      order_date: order.order_date,
      status: order.status,
      subtotal: order.subtotal,
      tax: order.tax,
      shipping_cost: order.shipping_cost,
      total: order.total,
      payment_method: order.payment_method || null,
      payment_status: order.payment_status,
      transaction_id: order.transaction_id || null,
      shipping_name: order.shipping_name,
      shipping_address_line1: order.shipping_address_line1,
      shipping_address_line2: order.shipping_address_line2 || null,
      shipping_city: order.shipping_city,
      shipping_state: order.shipping_state,
      shipping_postal_code: order.shipping_postal_code,
      shipping_country: order.shipping_country,
      tracking_number: order.tracking_number || null,
      notes: order.notes || null,
      items: items
    };
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to retrieve order' }, { status: 500 });
  }
}
