
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required fields
    if (!id) {
      return NextResponse.json({ error: 'Order ID is required' }, { status: 400 });
    }
    
    // Get order details - only for the authenticated user
    const orderQuery = `
      SELECT * FROM orders 
      WHERE id = ? AND userid = ?
    `;
    const orderResults = await db_query(db, orderQuery, [id, user_id]);
    
    if (!orderResults || orderResults.length === 0) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }
    
    const order = orderResults[0];
    
    // Get order items with dress details
    const orderItemsQuery = `
      SELECT 
        oi.*,
        d.name as dress_name,
        di.image_url as dress_image
      FROM orderitems oi
      JOIN dresses d ON oi.dressesid = d.id
      LEFT JOIN dressimages di ON d.id = di.dressesid AND di.is_primary = true
      WHERE oi.ordersid = ?
      ORDER BY oi.created_at ASC
    `;
    const orderItemsResults = await db_query(db, orderItemsQuery, [id]);
    
    // Format order items according to output interface
    const order_items = orderItemsResults.map(item => ({
      id: item.id,
      ordersid: item.ordersid,
      dressesid: item.dressesid,
      quantity: item.quantity,
      size: item.size,
      color: item.color,
      price_at_time: item.price_at_time,
      line_total: item.line_total,
      dress_name: item.dress_name || null,
      dress_image: item.dress_image || null,
      created_at: item.created_at
    }));
    
    // Parse JSON fields safely
    let shipping_address = {};
    let billing_address = {};
    
    try {
      shipping_address = order.shipping_address ? JSON.parse(order.shipping_address) : {};
    } catch (e) {
      shipping_address = {};
    }
    
    try {
      billing_address = order.billing_address ? JSON.parse(order.billing_address) : {};
    } catch (e) {
      billing_address = {};
    }
    
    // Format response according to output interface
    const result = {
      id: order.id,
      order_number: order.order_number,
      status: order.status,
      subtotal: order.subtotal,
      tax_amount: order.tax_amount,
      shipping_amount: order.shipping_amount,
      total_amount: order.total_amount,
      currency: order.currency,
      payment_status: order.payment_status,
      payment_method: order.payment_method || null,
      shipping_address: shipping_address,
      billing_address: billing_address,
      notes: order.notes || null,
      tracking_number: order.tracking_number || null,
      shipped_at: order.shipped_at || null,
      delivered_at: order.delivered_at || null,
      order_items: order_items,
      created_at: order.created_at,
      updated_at: order.updated_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error retrieving order:', error);
    return NextResponse.json({ error: 'Failed to retrieve order' }, { status: 500 });
  }
}

