
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import List from '@/components/list';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Categorys',
    description: 'List of Category',
    openGraph: {
        title: 'Categorys',
        description: 'List of Category',
        url: '/category_list',
        siteName: 'TechCorp'
    },
};

export default  function category_list() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Categorys","link":"/category_list"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <List
                                modelName="Category"
                                showAdminFeatures={true}
                                nameField="category_name"
                                 
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}