
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required parameters
    if (!id) {
      return NextResponse.json({ error: 'ID parameter is required' }, { status: 400 });
    }
    
    // Query for the dress
    const dressQuery = "SELECT * FROM dresses WHERE id = ?";
    const dressResult = await db_query(db, dressQuery, [id]);
    
    if (!dressResult || dressResult.length === 0) {
      return NextResponse.json({ error: 'Dress not found' }, { status: 404 });
    }
    
    const dress = dressResult[0];
    
    // Query for related images
    const imagesQuery = "SELECT * FROM dressimages WHERE dressesid = ? ORDER BY display_order ASC";
    const imagesResult = await db_query(db, imagesQuery, [id]);
    
    // Format the response according to output interface
    const result = {
      id: dress.id,
      categoriesid: dress.categoriesid,
      name: dress.name,
      slug: dress.slug,
      description: dress.description || null,
      price: dress.price,
      compare_at_price: dress.compare_at_price || null,
      sku: dress.sku,
      stock_quantity: dress.stock_quantity,
      available_sizes: JSON.parse(dress.available_sizes || '[]'),
      available_colors: JSON.parse(dress.available_colors || '[]'),
      material: dress.material || null,
      care_instructions: dress.care_instructions || null,
      featured: dress.featured,
      published: dress.published,
      images: imagesResult ? imagesResult.map(image => ({
        id: image.id,
        dressesid: image.dressesid,
        image_url: image.image_url,
        alt_text: image.alt_text || null,
        display_order: image.display_order,
        is_primary: image.is_primary,
        created_at: image.created_at
      })) : [],
      created_at: dress.created_at,
      updated_at: dress.updated_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error retrieving dress:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

