/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  // Parse request parameters
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');
  
  // Validate required fields
  if (!id) {
    return NextResponse.json({ 
      success: false, 
      message: 'Order ID is required for Victorian Era order deletion' 
    }, { status: 400 });
  }
  
  try {
    // Check if order exists and get its status
    const orderQuery = await db_query(db, 
      "SELECT id, status FROM orders WHERE id = $1", 
      [id]
    );
    
    if (!orderQuery || orderQuery.length === 0) {
      return NextResponse.json({ 
        success: false, 
        message: 'Victorian Era order not found' 
      }, { status: 404 });
    }
    
    const order = orderQuery[0];
    
    // Check if order status allows deletion
    if (order.status !== 'pending' && order.status !== 'cancelled') {
      return NextResponse.json({ 
        success: false, 
        message: `Victorian Era order cannot be deleted. Only orders with 'pending' or 'cancelled' status can be deleted. Current status: ${order.status}` 
      }, { status: 400 });
    }
    
    // Delete associated order items first (foreign key constraint)
    await db_query(db, 
      "DELETE FROM orderitems WHERE ordersid = $1", 
      [id]
    );
    
    // Delete the order
    await db_query(db, 
      "DELETE FROM orders WHERE id = $1", 
      [id]
    );
    
    const result = {
      success: true,
      message: 'Victorian Era order and associated items successfully deleted'
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json({ 
      success: false, 
      message: `Failed to delete Victorian Era order: ${error.message}` 
    }, { status: 500 });
  }
}
