
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse request to get order ID
    const url = new URL(request.url);
    const orderId = url.searchParams.get('id');
    
    // Validate required fields
    if (!orderId) {
      return NextResponse.json({
        success: false,
        message: 'Order ID is required'
      }, { status: 400 });
    }
    
    // Check if the order exists
    const orderResult = await db_query(db, "SELECT * FROM orders WHERE id = ?", [orderId]);
    
    if (!orderResult || orderResult.length === 0) {
      return NextResponse.json({
        success: false,
        message: 'Order not found'
      }, { status: 404 });
    }
    
    // Get all order items for this order to restore inventory
    const orderItems = await db_query(db, "SELECT * FROM orderitems WHERE ordersid = ?", [orderId]);
    
    // Restore inventory for each order item
    if (orderItems && orderItems.length > 0) {
      for (const item of orderItems) {
        // Update the dress stock quantity by adding back the ordered quantity
        await db_query(db, 
          "UPDATE dresses SET stock_quantity = stock_quantity + ? WHERE id = ?", 
          [item.quantity, item.dressesid]
        );
      }
      
      // Delete all order items
      await db_query(db, "DELETE FROM orderitems WHERE ordersid = ?", [orderId]);
    }
    
    // Delete the order
    await db_query(db, "DELETE FROM orders WHERE id = ?", [orderId]);
    
    const result = {
      success: true,
      message: 'Order deleted successfully and inventory restored'
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error deleting order:', error);
    return NextResponse.json({
      success: false,
      message: 'Failed to delete order. Please try again.'
    }, { status: 500 });
  }
}

