/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.name || body.name.trim() === '') {
      return NextResponse.json(
        { error: 'Victorian Era: Category name is required' },
        { status: 400 }
      );
    }
    
    // Check if category name already exists (case-insensitive)
    const existingCategory = await db_query(
      db,
      'SELECT id FROM categories WHERE LOWER(name) = LOWER($1)',
      [body.name.trim()]
    );
    
    if (existingCategory && existingCategory.length > 0) {
      return NextResponse.json(
        { error: 'Victorian Era: A category with this name already exists' },
        { status: 400 }
      );
    }
    
    // Generate new UUID for category
    const categoryId = crypto.randomUUID();
    
    // Handle image_url if it's base64 encoded data
    let imageUrl = body.image_url || null;
    if (imageUrl && imageUrl.startsWith('data:')) {
      const base64Data = imageUrl.split(',')[1];
      imageUrl = await store_file('category-image.jpg', base64Data, true);
    }
    
    // Set default values
    const visible = body.visible !== undefined ? body.visible : true;
    const displayOrder = body.display_order !== undefined ? body.display_order : null;
    const description = body.description || null;
    
    // Insert new category into database
    await db_query(
      db,
      'INSERT INTO categories (id, name, description, image_url, display_order, visible) VALUES ($1, $2, $3, $4, $5, $6)',
      [categoryId, body.name.trim(), description, imageUrl, displayOrder, visible]
    );
    
    // Fetch the newly created category
    const newCategory = await db_query(
      db,
      'SELECT id, name, description, image_url, display_order, visible FROM categories WHERE id = $1',
      [categoryId]
    );
    
    if (!newCategory || newCategory.length === 0) {
      return NextResponse.json(
        { error: 'Victorian Era: Failed to retrieve newly created category' },
        { status: 500 }
      );
    }
    
    // Format result according to output interface specification
    const result = {
      id: newCategory[0].id,
      name: newCategory[0].name,
      description: newCategory[0].description,
      image_url: newCategory[0].image_url,
      display_order: newCategory[0].display_order,
      visible: newCategory[0].visible
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Victorian Era: Failed to create category - ' + error.message },
      { status: 500 }
    );
  }
}
