
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.name || !body.slug || body.display_order === undefined || body.published === undefined) {
      return NextResponse.json({ error: 'Missing required fields: name, slug, display_order, and published are required' }, { status: 400 });
    }
    
    // Validate data types
    if (typeof body.name !== 'string' || typeof body.slug !== 'string' || typeof body.display_order !== 'number' || typeof body.published !== 'boolean') {
      return NextResponse.json({ error: 'Invalid data types for required fields' }, { status: 400 });
    }
    
    if (body.description !== undefined && body.description !== null && typeof body.description !== 'string') {
      return NextResponse.json({ error: 'Description must be a string' }, { status: 400 });
    }
    
    if (body.image_url !== undefined && body.image_url !== null && typeof body.image_url !== 'string') {
      return NextResponse.json({ error: 'Image URL must be a string' }, { status: 400 });
    }
    
    // Validate name and slug are not empty
    if (body.name.trim() === '' || body.slug.trim() === '') {
      return NextResponse.json({ error: 'Name and slug cannot be empty' }, { status: 400 });
    }
    
    // Validate slug uniqueness
    const existingCategory = await db_query(db, "SELECT id FROM categories WHERE slug = ?", [body.slug.trim()]);
    if (existingCategory.length > 0) {
      return NextResponse.json({ error: 'A category with this slug already exists' }, { status: 400 });
    }
    
    // Handle image_url if it's base64 data
    let imageUrl = body.image_url || null;
    if (imageUrl && imageUrl.startsWith('data:image/')) {
      try {
        // Extract base64 data
        const base64Data = imageUrl.split(',')[1];
        if (!base64Data) {
          return NextResponse.json({ error: 'Invalid base64 image data' }, { status: 400 });
        }
        const filename = `category-${Date.now()}.jpg`;
        imageUrl = await store_file(filename, base64Data, true);
      } catch (fileError) {
        console.error('Error storing image file:', fileError);
        return NextResponse.json({ error: 'Failed to process image upload' }, { status: 500 });
      }
    }
    
    // Clean up optional fields
    const description = body.description && body.description.trim() !== '' ? body.description.trim() : null;
    
    // Generate UUID and timestamps
    const categoryId = crypto.randomUUID();
    const now = new Date().toISOString();
    
    // Insert new category
    await db_query(db, 
      "INSERT INTO categories (id, name, slug, description, image_url, display_order, published, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", 
      [categoryId, body.name.trim(), body.slug.trim(), description, imageUrl, body.display_order, body.published, now, now]
    );
    
    // Return the created category
    const result = {
      id: categoryId,
      name: body.name.trim(),
      slug: body.slug.trim(),
      description: description,
      image_url: imageUrl,
      display_order: body.display_order,
      published: body.published,
      created_at: now,
      updated_at: now
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error creating category:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

