
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { db_add, db_update, db_select, db_delete, db_init } from '../../../database/supabase';
export async function GET(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const ids = searchParams.get('ids')?.split(',') || [];
  
  const db = await db_init();
  let user_id = null;
  
  
  
  let result;
  try {
    if (ids.length > 0) {
      result = await db_select(db, 'Events', ['ID', 'title', 'description', 'start_date', 'end_date', 'location', 'event_type', 'event_image'], ids);
    } else {
      result = await db_select(db, 'Events', ['ID', 'title', 'description', 'start_date', 'end_date', 'location', 'event_type', 'event_image']);
    }
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch events' }, { status: 500 });
  }
  
  return NextResponse.json(result);
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const db = await db_init();
  let user_id = null;
  
  
  
  let result;
  try {
    const body = await request.json();
    
    // Validate required fields
    const requiredFields = ['ID', 'title', 'description', 'start_date', 'end_date', 'location', 'event_type'];
    for (const field of requiredFields) {
      if (!body[field]) {
        return NextResponse.json({ error: `Missing required field: ${field}` }, { status: 400 });
      }
    }
    
    result = await db_add(db, 'Events', {
      ID: body.ID,
      title: body.title,
      description: body.description,
      start_date: body.start_date,
      end_date: body.end_date,
      location: body.location,
      event_type: body.event_type,
      event_image: body.event_image || null
    });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create event' }, { status: 500 });
  }
  
  return NextResponse.json(result);
}

export async function PUT(request: NextRequest): Promise<NextResponse> {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

  
  let result;
  try {
    const body = await request.json();
    
    // Validate required fields
    const requiredFields = ['ID', 'title', 'description', 'start_date', 'end_date', 'location', 'event_type'];
    for (const field of requiredFields) {
      if (!body[field]) {
        return NextResponse.json({ error: `Missing required field: ${field}` }, { status: 400 });
      }
    }
    
    result = await db_update(db, 'Events', {
      title: body.title,
      description: body.description,
      start_date: body.start_date,
      end_date: body.end_date,
      location: body.location,
      event_type: body.event_type,
      event_image: body.event_image || null
    }, [body.ID]);
    
    if (!result || result.length === 0) {
      return NextResponse.json({ error: 'Event not found' }, { status: 404 });
    }
  } catch (error) {
    return NextResponse.json({ error: 'Failed to update event' }, { status: 500 });
  }
  
  return NextResponse.json(result);
}

export async function DELETE(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');
  
  if (!id) {
    return NextResponse.json({ error: 'Event ID is required' }, { status: 400 });
  }
  
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  let result;
  try {
    result = await db_delete(db, 'Events', [id]);
    
    if (!result || result.length === 0) {
      return NextResponse.json({ error: 'Event not found' }, { status: 404 });
    }
  } catch (error) {
    return NextResponse.json({ error: 'Failed to delete event' }, { status: 500 });
  }
  
  return NextResponse.json(result);
}

