/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    const body = await request.json();
    
    if (!body.id) {
      return NextResponse.json(
        { error: 'Victorian Era: Address ID is required' },
        { status: 400 }
      );
    }
    
    const checkQuery = 'SELECT * FROM shippingaddresses WHERE id = $1 AND userid = $2';
    const existingAddress = await db_query(db, checkQuery, [body.id, user_id]);
    
    if (!existingAddress || existingAddress.length === 0) {
      return NextResponse.json(
        { error: 'Victorian Era: Shipping address not found or you do not have permission to update it' },
        { status: 404 }
      );
    }
    
    if (body.is_default === true) {
      const resetDefaultQuery = 'UPDATE shippingaddresses SET is_default = false WHERE userid = $1 AND id != $2';
      await db_query(db, resetDefaultQuery, [user_id, body.id]);
    }
    
    const updateFields = [];
    const updateParams = [];
    let paramIndex = 1;
    
    if (body.address_name !== undefined) {
      updateFields.push('address_name = $' + paramIndex);
      updateParams.push(body.address_name);
      paramIndex++;
    }
    
    if (body.recipient_name !== undefined) {
      updateFields.push('recipient_name = $' + paramIndex);
      updateParams.push(body.recipient_name);
      paramIndex++;
    }
    
    if (body.address_line1 !== undefined) {
      updateFields.push('address_line1 = $' + paramIndex);
      updateParams.push(body.address_line1);
      paramIndex++;
    }
    
    if (body.address_line2 !== undefined) {
      updateFields.push('address_line2 = $' + paramIndex);
      updateParams.push(body.address_line2);
      paramIndex++;
    }
    
    if (body.city !== undefined) {
      updateFields.push('city = $' + paramIndex);
      updateParams.push(body.city);
      paramIndex++;
    }
    
    if (body.state !== undefined) {
      updateFields.push('state = $' + paramIndex);
      updateParams.push(body.state);
      paramIndex++;
    }
    
    if (body.postal_code !== undefined) {
      updateFields.push('postal_code = $' + paramIndex);
      updateParams.push(body.postal_code);
      paramIndex++;
    }
    
    if (body.country !== undefined) {
      updateFields.push('country = $' + paramIndex);
      updateParams.push(body.country);
      paramIndex++;
    }
    
    if (body.phone !== undefined) {
      updateFields.push('phone = $' + paramIndex);
      updateParams.push(body.phone);
      paramIndex++;
    }
    
    if (body.is_default !== undefined) {
      updateFields.push('is_default = $' + paramIndex);
      updateParams.push(body.is_default);
      paramIndex++;
    }
    
    if (updateFields.length > 0) {
      const updateQuery = 'UPDATE shippingaddresses SET ' + updateFields.join(', ') + ' WHERE id = $' + paramIndex + ' AND userid = $' + (paramIndex + 1);
      updateParams.push(body.id);
      updateParams.push(user_id);
      await db_query(db, updateQuery, updateParams);
    }
    
    const selectQuery = 'SELECT * FROM shippingaddresses WHERE id = $1 AND userid = $2';
    const updatedAddress = await db_query(db, selectQuery, [body.id, user_id]);
    
    if (!updatedAddress || updatedAddress.length === 0) {
      return NextResponse.json(
        { error: 'Victorian Era: Failed to retrieve updated address' },
        { status: 500 }
      );
    }
    
    const address = updatedAddress[0];
    
    const result = {
      id: address.id,
      address_name: address.address_name,
      recipient_name: address.recipient_name,
      address_line1: address.address_line1,
      address_line2: address.address_line2,
      city: address.city,
      state: address.state,
      postal_code: address.postal_code,
      country: address.country,
      phone: address.phone,
      is_default: address.is_default
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Victorian Era: Failed to update shipping address - ' + error.message },
      { status: 500 }
    );
  }
}
