
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Job Application  Add',
    description: 'Add a new JobApplication',
    openGraph: {
        title: 'Job Application  Add',
        description: 'Add a new JobApplication',
        url: '/jobapplication_add',
        siteName: 'Job Board'
    },
};

export default  function jobapplication_add() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Candidate Profile","link":"/candidateprofile_list"},{"title":"Candidate Profile  Details","link":"/candidateprofile_details/[id]"},{"title":"Job Application  Add","link":"/jobapplication_add"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="JobApplication"
                                fields={[{"name":"application_status","datatype":"VARCHAR","datatypesize":"50","key":null,"is_name":"false","is_searchable":"true","required":"true","untouchable":"false","default":"pending","children":[]},{"name":"cover_letter","datatype":"TEXT","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"false","untouchable":"false","default":null,"children":[]},{"name":"date_applied","datatype":"DATETIME","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"},{"name":"CandidateProfileID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"},{"name":"JobPostingID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"}]}
                                mode="add"
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}