
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.id) {
      return NextResponse.json({ error: 'Order item ID is required' }, { status: 400 });
    }

    // Get the current order item
    const existingItem = await db_query(db, 
      "SELECT * FROM orderitems WHERE id = ?", 
      [body.id]
    );

    if (!existingItem || existingItem.length === 0) {
      return NextResponse.json({ error: 'Order item not found' }, { status: 404 });
    }

    const currentItem = existingItem[0];

    // Prepare update fields
    const updateFields = [];
    const updateParams = [];

    if (body.quantity !== undefined) {
      updateFields.push("quantity = ?");
      updateParams.push(body.quantity);
    }

    if (body.size !== undefined) {
      updateFields.push("size = ?");
      updateParams.push(body.size);
    }

    if (body.color !== undefined) {
      updateFields.push("color = ?");
      updateParams.push(body.color);
    }

    // Recalculate line_total if quantity changed
    if (body.quantity !== undefined) {
      const newLineTotal = body.quantity * currentItem.price_at_time;
      updateFields.push("line_total = ?");
      updateParams.push(newLineTotal);
    }

    // If no fields to update, return current item
    if (updateFields.length === 0) {
      const result = {
        id: currentItem.id,
        ordersid: currentItem.ordersid,
        dressesid: currentItem.dressesid,
        quantity: currentItem.quantity,
        size: currentItem.size,
        color: currentItem.color,
        price_at_time: currentItem.price_at_time,
        line_total: currentItem.line_total,
        created_at: currentItem.created_at
      };
      return NextResponse.json(result);
    }

    // Build and execute update query
    const updateQuery = `UPDATE orderitems SET ${updateFields.join(', ')} WHERE id = ?`;
    updateParams.push(body.id);

    await db_query(db, updateQuery, updateParams);

    // Get updated item
    const updatedItem = await db_query(db, 
      "SELECT * FROM orderitems WHERE id = ?", 
      [body.id]
    );

    const updated = updatedItem[0];
    const result = {
      id: updated.id,
      ordersid: updated.ordersid,
      dressesid: updated.dressesid,
      quantity: updated.quantity,
      size: updated.size,
      color: updated.color,
      price_at_time: updated.price_at_time,
      line_total: updated.line_total,
      created_at: updated.created_at
    };

    return NextResponse.json(result);

  } catch (error) {
    console.error('Error updating order item:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

