
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.dressesid) {
      return NextResponse.json({ error: 'Dress ID is required' }, { status: 400 });
    }
    
    if (!body.image_url) {
      return NextResponse.json({ error: 'Image data is required' }, { status: 400 });
    }
    
    if (body.display_order === undefined || body.display_order === null) {
      return NextResponse.json({ error: 'Display order is required' }, { status: 400 });
    }
    
    if (body.is_primary === undefined || body.is_primary === null) {
      return NextResponse.json({ error: 'Primary status is required' }, { status: 400 });
    }
    
    // Check if dress exists
    const dressCheck = await db_query(db, "SELECT id FROM dresses WHERE id = ?", [body.dressesid]);
    if (!dressCheck || dressCheck.length === 0) {
      return NextResponse.json({ error: 'Dress not found' }, { status: 404 });
    }
    
    // If setting as primary, unset other primary images for this dress
    if (body.is_primary) {
      await db_query(db, "UPDATE dressimages SET is_primary = ? WHERE dressesid = ?", [false, body.dressesid]);
    }
    
    // Store the image file
    const imageRef = await store_file(`dress-image-${Date.now()}.jpg`, body.image_url, true);
    
    // Generate new ID and current timestamp
    const newId = crypto.randomUUID();
    const createdAt = new Date().toISOString();
    
    // Insert new dress image record
    await db_query(db, 
      "INSERT INTO dressimages (id, dressesid, image_url, alt_text, display_order, is_primary, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
      [newId, body.dressesid, imageRef, body.alt_text || null, body.display_order, body.is_primary, createdAt]
    );
    
    // Prepare result
    const result = {
      id: newId,
      dressesid: body.dressesid,
      image_url: imageRef,
      alt_text: body.alt_text || null,
      display_order: body.display_order,
      is_primary: body.is_primary,
      created_at: createdAt
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error creating dress image:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

