
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import LoginCallback from '@/components/logincallback';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Login Callback',
    description: 'OAuth callback handler page',
    openGraph: {
        title: 'Login Callback',
        description: 'OAuth callback handler page',
        url: '/logincallback',
        siteName: 'TechCorp'
    },
};

export default  function logincallback({
    searchParams,
}: {
    searchParams: { [key: string]: string | string[] | undefined };
} & { searchParams: Promise<any> }) {
    const code = searchParams.code as string;
    const state = searchParams.state as string;
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Login Callback","link":"/logincallback"}]} />
                        </div>
                    </div>
                
                
                <div className="row">
                    <div className="col">    
                        <LoginCallback code={code} state={state} />
                    </div>
                </div>
            </main>
        </div>
    );
}