
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Employer Profile  Add',
    description: 'Add a new EmployerProfile',
    openGraph: {
        title: 'Employer Profile  Add',
        description: 'Add a new EmployerProfile',
        url: '/employerprofile_add',
        siteName: 'Job Board'
    },
};

export default  function employerprofile_add() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Employer Profile","link":"/employerprofile_list"},{"title":"Employer Profile  Add","link":"/employerprofile_add"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="EmployerProfile"
                                fields={[{"name":"company_name","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"contact_email","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"false","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"company_description","datatype":"TEXT","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"false","untouchable":"false","default":null,"children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"}]}
                                mode="add"
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}