
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.entry_date) {
      return NextResponse.json(
        { error: 'Vitalisona wellness journal requires an entry date to create your wellness entry' },
        { status: 400 }
      );
    }
    
    // Generate unique ID and timestamp
    const journalId = crypto.randomUUID();
    const createdAt = new Date().toISOString();
    
    // Insert wellness journal entry into database
    await db_query(db, `
      INSERT INTO wellnessjournal (
        id, 
        userid, 
        entry_date, 
        mood_rating, 
        energy_level, 
        stress_level, 
        sleep_quality, 
        notes, 
        session_feedback, 
        goals, 
        created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [
      journalId,
      user_id,
      body.entry_date,
      body.mood_rating || null,
      body.energy_level || null,
      body.stress_level || null,
      body.sleep_quality || null,
      body.notes || null,
      body.session_feedback || null,
      body.goals || null,
      createdAt
    ]);
    
    // Prepare result with the exact output interface specification
    const result = {
      id: journalId,
      entry_date: body.entry_date,
      mood_rating: body.mood_rating || null,
      energy_level: body.energy_level || null,
      stress_level: body.stress_level || null,
      sleep_quality: body.sleep_quality || null,
      notes: body.notes || null,
      session_feedback: body.session_feedback || null,
      goals: body.goals || null,
      created_at: createdAt
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona wellness journal creation error:', error);
    return NextResponse.json(
      { error: 'Failed to create wellness journal entry in Vitalisona system. Please try again.' },
      { status: 500 }
    );
  }
}

