
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  // Parse request body to get the ID
  const body = await request.json();
  
  // Validate required fields
  if (!body.id || typeof body.id !== 'string') {
    const result = {
      success: false,
      message: "Invalid or missing sound library ID for Vitalisona system"
    };
    return NextResponse.json(result, { status: 400 });
  }
  
  try {
    // Check if the sound library item exists
    const existingItem = await db_query(db, 
      "SELECT * FROM soundlibrary WHERE id = ?", 
      [body.id]
    );
    
    if (!existingItem || existingItem.length === 0) {
      const result = {
        success: false,
        message: "Sound library item not found in Vitalisona system"
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    // Validate that content is not actively being used in sessions
    // Check if any sessions are currently using this audio content
    // Note: This validates system integrity as requested in business logic
    const activeSessionsCheck = await db_query(db, 
      "SELECT COUNT(*) as count FROM sessions WHERE status IN ('scheduled', 'in_progress') AND notes LIKE ?", 
      [`%${body.id}%`]
    );
    
    if (activeSessionsCheck[0].count > 0) {
      const result = {
        success: false,
        message: "Cannot delete sound library item - it is currently being used in active Vitalisona sessions"
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Additional validation - check if content is published and being actively used
    if (existingItem[0].published) {
      // For published content, add extra validation to maintain system integrity
      const recentUsageCheck = await db_query(db, 
        "SELECT COUNT(*) as count FROM sessions WHERE created_at >= datetime('now', '-30 days') AND notes LIKE ?", 
        [`%${body.id}%`]
      );
      
      if (recentUsageCheck[0].count > 0) {
        const result = {
          success: false,
          message: "Cannot delete published sound library item - it has been used in recent Vitalisona sessions. Consider unpublishing first."
        };
        return NextResponse.json(result, { status: 400 });
      }
    }
    
    // Delete the sound library item
    const deleteResult = await db_query(db, 
      "DELETE FROM soundlibrary WHERE id = ?", 
      [body.id]
    );
    
    if (deleteResult.changes === 0) {
      const result = {
        success: false,
        message: "Failed to delete sound library item from Vitalisona system"
      };
      return NextResponse.json(result, { status: 500 });
    }
    
    const result = {
      success: true,
      message: "Sound library item successfully removed from Vitalisona system"
    };
    return NextResponse.json(result);
    
  } catch (error) {
    const result = {
      success: false,
      message: "Error occurred while removing sound library item from Vitalisona system"
    };
    return NextResponse.json(result, { status: 500 });
  }
}

