
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required field
    if (!id) {
      const result = { error: 'ID parameter is required' };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Query the database for the dress image
    const imageQuery = "SELECT id, dressesid, image_url, alt_text, display_order, is_primary, created_at FROM dressimages WHERE id = ?";
    const images = await db_query(db, imageQuery, [id]);
    
    // Check if image exists
    if (!images || images.length === 0) {
      const result = { error: 'Dress image not found' };
      return NextResponse.json(result, { status: 404 });
    }
    
    const image = images[0];
    
    // Format the result according to the output interface
    const result = {
      id: image.id,
      dressesid: image.dressesid,
      image_url: image.image_url,
      alt_text: image.alt_text,
      display_order: image.display_order,
      is_primary: image.is_primary,
      created_at: image.created_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    const result = { error: 'Internal server error' };
    return NextResponse.json(result, { status: 500 });
  }
}

