/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse request body
    const body = await request.json();
    
    // Validate required id
    if (!body.id) {
      return NextResponse.json(
        { error: 'Product ID is required' },
        { status: 400 }
      );
    }
    
    // Validate numeric fields if provided
    if (body.price !== undefined && (isNaN(body.price) || body.price < 0)) {
      return NextResponse.json(
        { error: 'Price must be a valid non-negative number' },
        { status: 400 }
      );
    }
    
    if (body.stock_quantity !== undefined && (isNaN(body.stock_quantity) || body.stock_quantity < 0 || !Number.isInteger(body.stock_quantity))) {
      return NextResponse.json(
        { error: 'Stock quantity must be a valid non-negative integer' },
        { status: 400 }
      );
    }
    
    // Check if product exists
    const existingProduct = await db_query(
      db,
      'SELECT * FROM products WHERE id = $1',
      [body.id]
    );
    
    if (!existingProduct || existingProduct.length === 0) {
      return NextResponse.json(
        { error: 'Product not found' },
        { status: 404 }
      );
    }
    
    // If categoriesid is being changed, validate it exists
    if (body.categoriesid) {
      const categoryExists = await db_query(
        db,
        'SELECT id FROM categories WHERE id = $1',
        [body.categoriesid]
      );
      
      if (!categoryExists || categoryExists.length === 0) {
        return NextResponse.json(
          { error: 'Invalid category ID - category does not exist' },
          { status: 400 }
        );
      }
    }
    
    // Build dynamic UPDATE query
    const updateFields = [];
    const queryParams = [];
    let paramIndex = 1;
    
    if (body.categoriesid !== undefined) {
      updateFields.push('categoriesid = $' + paramIndex);
      queryParams.push(body.categoriesid);
      paramIndex++;
    }
    
    if (body.name !== undefined) {
      updateFields.push('name = $' + paramIndex);
      queryParams.push(body.name);
      paramIndex++;
    }
    
    if (body.description !== undefined) {
      updateFields.push('description = $' + paramIndex);
      queryParams.push(body.description);
      paramIndex++;
    }
    
    if (body.price !== undefined) {
      updateFields.push('price = $' + paramIndex);
      queryParams.push(body.price);
      paramIndex++;
    }
    
    if (body.sku !== undefined) {
      updateFields.push('sku = $' + paramIndex);
      queryParams.push(body.sku);
      paramIndex++;
    }
    
    if (body.stock_quantity !== undefined) {
      updateFields.push('stock_quantity = $' + paramIndex);
      queryParams.push(body.stock_quantity);
      paramIndex++;
    }
    
    if (body.size !== undefined) {
      updateFields.push('size = $' + paramIndex);
      queryParams.push(body.size);
      paramIndex++;
    }
    
    if (body.color !== undefined) {
      updateFields.push('color = $' + paramIndex);
      queryParams.push(body.color);
      paramIndex++;
    }
    
    if (body.material !== undefined) {
      updateFields.push('material = $' + paramIndex);
      queryParams.push(body.material);
      paramIndex++;
    }
    
    if (body.era_period !== undefined) {
      updateFields.push('era_period = $' + paramIndex);
      queryParams.push(body.era_period);
      paramIndex++;
    }
    
    if (body.care_instructions !== undefined) {
      updateFields.push('care_instructions = $' + paramIndex);
      queryParams.push(body.care_instructions);
      paramIndex++;
    }
    
    if (body.available !== undefined) {
      updateFields.push('available = $' + paramIndex);
      queryParams.push(body.available);
      paramIndex++;
    }
    
    if (body.featured !== undefined) {
      updateFields.push('featured = $' + paramIndex);
      queryParams.push(body.featured);
      paramIndex++;
    }
    
    // If no fields to update, return current product
    if (updateFields.length === 0) {
      const result = {
        id: existingProduct[0].id,
        categoriesid: existingProduct[0].categoriesid,
        name: existingProduct[0].name,
        description: existingProduct[0].description,
        price: parseFloat(existingProduct[0].price),
        sku: existingProduct[0].sku,
        stock_quantity: existingProduct[0].stock_quantity,
        size: existingProduct[0].size,
        color: existingProduct[0].color,
        material: existingProduct[0].material,
        era_period: existingProduct[0].era_period,
        care_instructions: existingProduct[0].care_instructions,
        available: existingProduct[0].available,
        featured: existingProduct[0].featured
      };
      return NextResponse.json(result);
    }
    
    // Add product id to params for WHERE clause
    queryParams.push(body.id);
    
    // Execute update
    const updateQuery = 'UPDATE products SET ' + updateFields.join(', ') + ' WHERE id = $' + paramIndex;
    await db_query(db, updateQuery, queryParams);
    
    // Fetch updated product
    const updatedProduct = await db_query(
      db,
      'SELECT * FROM products WHERE id = $1',
      [body.id]
    );
    
    const result = {
      id: updatedProduct[0].id,
      categoriesid: updatedProduct[0].categoriesid,
      name: updatedProduct[0].name,
      description: updatedProduct[0].description,
      price: parseFloat(updatedProduct[0].price),
      sku: updatedProduct[0].sku,
      stock_quantity: updatedProduct[0].stock_quantity,
      size: updatedProduct[0].size,
      color: updatedProduct[0].color,
      material: updatedProduct[0].material,
      era_period: updatedProduct[0].era_period,
      care_instructions: updatedProduct[0].care_instructions,
      available: updatedProduct[0].available,
      featured: updatedProduct[0].featured
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to update product: ' + error.message },
      { status: 500 }
    );
  }
}
