
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import PrivacyPolicy from '@/custom/Privacy_Policy';

export const metadata: Metadata = {
    title: 'Privacy  Policy',
    description: 'Details about how user data is collected and handled',
    openGraph: {
        title: 'Privacy  Policy',
        description: 'Details about how user data is collected and handled',
        url: '/privacy_policy',
        siteName: 'Maryland Christmas'
    },
};

export default  function privacy_policy() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><PrivacyPolicy />
                        </div>
                    </div>
            </main>
        </div>
    );
}