
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import PrivacyPolicy from '@/custom/Privacy_Policy';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Privacy  Policy',
    description: 'Details about how user data is collected and handled',
    openGraph: {
        title: 'Privacy  Policy',
        description: 'Details about how user data is collected and handled',
        url: '/privacy_policy',
        siteName: 'TechCorp'
    },
};

export default  function privacy_policy() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Privacy  Policy","link":"/privacy_policy"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col"><PrivacyPolicy />
                        </div>
                    </div>
            </main>
        </div>
    );
}