
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Details from '@/components/details';
import ListDetails from '@/components/listdetails';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Job Listing  Details',
    description: 'Details of JobListing',
    openGraph: {
        title: 'Job Listing  Details',
        description: 'Details of JobListing',
        url: '/joblisting_details',
        siteName: 'TechCorp'
    },
};

export default async function joblisting_details({ params }:  { params: Promise<{ id: string }>}) {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Category","link":"/category_list"},{"title":"Category  Details","link":"/category_details/[id]"},{"title":"Job Listing  Details","link":"/joblisting_details/[id]"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Details
                                modelName="JobListing"
                                id={(await params).id}
                            />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col">    
                            <ListDetails 
                                modelName="JobApplication"
                                showAdminFeatures={true}
                                fields={[{"name":"applicant_name","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":"null","children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"},{"name":"JobListingID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"},{"name":"ResumeDatabaseID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"}]}
                                subFieldName="ResumeDatabaseID" subFieldValue={(await params).id}
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}