
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Profile from '@/components/profile';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Profile',
    description: 'User profile page',
    openGraph: {
        title: 'Profile',
        description: 'User profile page',
        url: '/profile',
        siteName: 'TechCorp'
    },
};

export default  function profile() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Profile","link":"/profile"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                        <Profile />
                        </div>
                    </div>
            </main>
        </div>
    );
}