
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import Profile from '@/components/profile';

export const metadata: Metadata = {
    title: 'Profile',
    description: 'User profile page',
    openGraph: {
        title: 'Profile',
        description: 'User profile page',
        url: '/profile',
        siteName: 'Maryland Christmas'
    },
};

export default  function profile() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><Profile />
                        </div>
                    </div>
            </main>
        </div>
    );
}