
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function POST(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    const body = await request.json();
    
    // Validate required fields
    if (!body.order_items || !Array.isArray(body.order_items) || body.order_items.length === 0) {
      return NextResponse.json({ error: 'Order items are required' }, { status: 400 });
    }
    
    if (!body.shipping_address) {
      return NextResponse.json({ error: 'Shipping address is required' }, { status: 400 });
    }
    
    if (!body.billing_address) {
      return NextResponse.json({ error: 'Billing address is required' }, { status: 400 });
    }
    
    // Validate each order item
    for (const item of body.order_items) {
      if (!item.dressesid || !item.quantity || !item.size || !item.color) {
        return NextResponse.json({ error: 'Each order item must have dressesid, quantity, size, and color' }, { status: 400 });
      }
      
      if (typeof item.quantity !== 'number' || item.quantity <= 0) {
        return NextResponse.json({ error: 'Quantity must be a positive number' }, { status: 400 });
      }
    }
    
    // Calculate order totals
    let subtotal = 0;
    const orderItemsData = [];
    
    for (const item of body.order_items) {
      // Get dress price and details
      const dressResult = await db_query(db, 'SELECT price, name FROM dresses WHERE id = ?', [item.dressesid]);
      
      if (!dressResult || dressResult.length === 0) {
        return NextResponse.json({ error: `Dress with id ${item.dressesid} not found` }, { status: 400 });
      }
      
      const dress = dressResult[0];
      const lineTotal = dress.price * item.quantity;
      subtotal += lineTotal;
      
      orderItemsData.push({
        id: crypto.randomUUID(),
        dressesid: item.dressesid,
        quantity: item.quantity,
        size: item.size,
        color: item.color,
        price_at_time: dress.price,
        line_total: lineTotal,
        dress_name: dress.name
      });
    }
    
    // Calculate tax and shipping
    const taxRate = 0.08; // 8% tax rate
    const taxAmount = Math.round(subtotal * taxRate * 100) / 100;
    const shippingAmount = subtotal >= 50 ? 0 : 9.99; // Free shipping over $50
    const totalAmount = Math.round((subtotal + taxAmount + shippingAmount) * 100) / 100;
    
    // Generate unique order number
    const orderNumber = 'ORD-' + Date.now() + '-' + Math.random().toString(36).substr(2, 5).toUpperCase();
    
    // Create order
    const orderId = crypto.randomUUID();
    const now = new Date().toISOString();
    
    await db_query(db, `
      INSERT INTO orders (
        id, userid, order_number, status, subtotal, tax_amount, shipping_amount, 
        total_amount, currency, payment_status, payment_method, shipping_address, 
        billing_address, notes, created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [
      orderId,
      user_id,
      orderNumber,
      'pending',
      subtotal,
      taxAmount,
      shippingAmount,
      totalAmount,
      'USD',
      'pending',
      body.payment_method || null,
      JSON.stringify(body.shipping_address),
      JSON.stringify(body.billing_address),
      body.notes || null,
      now,
      now
    ]);
    
    // Create order items and prepare response data
    const createdOrderItems = [];
    for (const itemData of orderItemsData) {
      // Insert order item
      await db_query(db, `
        INSERT INTO orderitems (
          id, ordersid, dressesid, quantity, size, color, 
          price_at_time, line_total, created_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        itemData.id,
        orderId,
        itemData.dressesid,
        itemData.quantity,
        itemData.size,
        itemData.color,
        itemData.price_at_time,
        itemData.line_total,
        now
      ]);
      
      // Get dress primary image for response
      const imageResult = await db_query(db, 'SELECT image_url FROM dressimages WHERE dressesid = ? AND is_primary = true LIMIT 1', [itemData.dressesid]);
      const dressImage = imageResult && imageResult.length > 0 ? imageResult[0].image_url : null;
      
      createdOrderItems.push({
        id: itemData.id,
        ordersid: orderId,
        dressesid: itemData.dressesid,
        quantity: itemData.quantity,
        size: itemData.size,
        color: itemData.color,
        price_at_time: itemData.price_at_time,
        line_total: itemData.line_total,
        dress_name: itemData.dress_name,
        dress_image: dressImage,
        created_at: now
      });
    }
    
    const result = {
      id: orderId,
      order_number: orderNumber,
      status: 'pending',
      subtotal: subtotal,
      tax_amount: taxAmount,
      shipping_amount: shippingAmount,
      total_amount: totalAmount,
      currency: 'USD',
      payment_status: 'pending',
      payment_method: body.payment_method || null,
      shipping_address: body.shipping_address,
      billing_address: body.billing_address,
      notes: body.notes || null,
      tracking_number: null,
      shipped_at: null,
      delivered_at: null,
      order_items: createdOrderItems,
      created_at: now,
      updated_at: now
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error creating order:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

