
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Resume Database  Edit',
    description: 'Edit a ResumeDatabase',
    openGraph: {
        title: 'Resume Database  Edit',
        description: 'Edit a ResumeDatabase',
        url: '/resumedatabase_edit',
        siteName: 'TechCorp'
    },
};

export default async function resumedatabase_edit({ params }:  { params: Promise<{ id: string }>}) {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Resume Database","link":"/resumedatabase_list"},{"title":"Resume Database  Edit","link":"/resumedatabase_edit/[id]"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="ResumeDatabase"
                                fields={[{"name":"candidate_name","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":"null","children":[]},{"name":"resume_text","datatype":"TEXT","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"false","untouchable":"false","default":"null","children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"}]}
                                mode="edit"
                                id={(await params).id}
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}