
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Search from '@/components/search';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'User dashboard page',
    openGraph: {
        title: 'Dashboard',
        description: 'User dashboard page',
        url: '/dashboard',
        siteName: 'Job Board'
    },
};

export default  function dashboard() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Search
                                modelName="CandidateProfile"
                                nameField="full_name"
                            />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col">    
                            <Search
                                modelName="EmployerProfile"
                                nameField="company_name"
                            />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col">    
                            <Search
                                modelName="JobCategory"
                                nameField="category_name"
                            />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col">    
                            <Search
                                modelName="JobLocation"
                                nameField="location_name"
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}