
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import MemberProfile from '@/custom/Member_Profile';
import MyEventRegistrations from '@/custom/My_Event_Registrations';
import UpcomingEvents from '@/custom/Upcoming_Events';

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'User dashboard page',
    openGraph: {
        title: 'Dashboard',
        description: 'User dashboard page',
        url: '/dashboard',
        siteName: 'Maryland Christmas'
    },
};

export default  function dashboard() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><section className="card">
                            <ErrorBoundary fallback={<Error />}>
                                <MemberProfile />
                            </ErrorBoundary>
                        </section>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><section className="card">
                            <ErrorBoundary fallback={<Error />}>
                                <MyEventRegistrations />
                            </ErrorBoundary>
                        </section>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><section className="card">
                            <ErrorBoundary fallback={<Error />}>
                                <UpcomingEvents />
                            </ErrorBoundary>
                        </section>
                        </div>
                    </div>
            </main>
        </div>
    );
}