
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { db_add, db_update, db_select, db_delete, db_init } from '../../../database/supabase';
export async function GET(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const ids = searchParams.get('ids')?.split(',') || [];
  
  const db = await db_init();
  let user_id = null;
  
  
  
  let result;
  try {
    if (ids.length > 0) {
      result = await db_select(db, 'LocationCategories', ['ID', 'name', 'description'], ids);
    } else {
      result = await db_select(db, 'LocationCategories', ['ID', 'name', 'description']);
    }
  } catch (error) {
    return NextResponse.json({ error: 'Failed to fetch location categories' }, { status: 500 });
  }
  
  return NextResponse.json(result);
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const db = await db_init();
  let user_id = null;
  
  
  
  let data;
  try {
    data = await request.json();
  } catch (error) {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }
  
  // Validate required fields
  if (!data.name || !data.description) {
    return NextResponse.json({ error: 'Missing required fields: name and description are required' }, { status: 400 });
  }
  
  // Generate UUID for new record
  const newId = crypto.randomUUID();
  
  try {
    const result = await db_add(db, 'LocationCategories', {
      ID: newId,
      name: data.name,
      description: data.description
    });
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to create location category' }, { status: 500 });
  }
}

export async function PUT(request: NextRequest): Promise<NextResponse> {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

  
  let data;
  try {
    data = await request.json();
  } catch (error) {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }
  
  // Validate required fields
  if (!data.ID || !data.name || !data.description) {
    return NextResponse.json({ error: 'Missing required fields: ID, name, and description are required' }, { status: 400 });
  }
  
  try {
    const result = await db_update(db, 'LocationCategories', {
      name: data.name,
      description: data.description
    }, [data.ID]);
    
    if (!result || result.length === 0) {
      return NextResponse.json({ error: 'Location category not found' }, { status: 404 });
    }
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to update location category' }, { status: 500 });
  }
}

export async function DELETE(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');
  
  if (!id) {
    return NextResponse.json({ error: 'Missing required parameter: id' }, { status: 400 });
  }
  
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_select);
    if (UserInfo.UserID.length===0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id=UserInfo.UserID;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    const result = await db_delete(db, 'LocationCategories', [id]);
    
    if (!result || result.length === 0) {
      return NextResponse.json({ error: 'Location category not found' }, { status: 404 });
    }
    
    return NextResponse.json(result);
  } catch (error) {
    return NextResponse.json({ error: 'Failed to delete location category' }, { status: 500 });
  }
}

