
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse request body to get session id
    const body = await request.json();
    const { id } = body;
    
    // Validate required input
    if (!id) {
      const result = {
        success: false,
        message: "Session ID is required for cancellation"
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Get the session from database, ensuring it belongs to the user
    const sessions = await db_query(db, 
      "SELECT * FROM sessions WHERE id = ? AND userid = ?", 
      [id, user_id]
    );
    
    if (!sessions || sessions.length === 0) {
      const result = {
        success: false,
        message: "Session not found or you do not have permission to cancel this session"
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    const session = sessions[0];
    
    // Check if session is already completed or cancelled
    if (session.status === 'completed' || session.status === 'cancelled') {
      const result = {
        success: false,
        message: "Cannot cancel a session that is already " + session.status
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Validate timing constraints - sessions cannot be cancelled within 24 hours
    const sessionDateTime = new Date(session.session_date + 'T' + session.session_time);
    const now = new Date();
    const timeDifferenceHours = (sessionDateTime - now) / (1000 * 60 * 60);
    
    if (timeDifferenceHours < 24) {
      const result = {
        success: false,
        message: "Vitalisona cancellation policy: Sessions must be cancelled at least 24 hours in advance"
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    // Delete the session
    await db_query(db, 
      "DELETE FROM sessions WHERE id = ? AND userid = ?", 
      [id, user_id]
    );
    
    const result = {
      success: true,
      message: "Your Vitalisona session has been successfully cancelled"
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error cancelling Vitalisona session:', error);
    const result = {
      success: false,
      message: "An error occurred while cancelling your session. Please try again or contact Vitalisona support."
    };
    return NextResponse.json(result, { status: 500 });
  }
}

