
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.id) {
      return NextResponse.json(
        { error: 'Vitalisona: Session ID is required for update' }, 
        { status: 400 }
      );
    }
    
    // Check if session exists and belongs to user
    const existingSession = await db_query(
      db, 
      "SELECT * FROM sessions WHERE id = ? AND userid = ?", 
      [body.id, user_id]
    );
    
    if (!existingSession || existingSession.length === 0) {
      return NextResponse.json(
        { error: 'Vitalisona: Session not found or access denied' }, 
        { status: 404 }
      );
    }
    
    // Build update query dynamically based on provided fields
    const updateFields = [];
    const updateParams = [];
    
    if (body.session_date !== undefined) {
      updateFields.push("session_date = ?");
      updateParams.push(body.session_date);
    }
    
    if (body.session_time !== undefined) {
      updateFields.push("session_time = ?");
      updateParams.push(body.session_time);
    }
    
    if (body.duration !== undefined) {
      updateFields.push("duration = ?");
      updateParams.push(body.duration);
    }
    
    if (body.status !== undefined) {
      updateFields.push("status = ?");
      updateParams.push(body.status);
    }
    
    if (body.notes !== undefined) {
      updateFields.push("notes = ?");
      updateParams.push(body.notes);
    }
    
    if (body.completed_at !== undefined) {
      updateFields.push("completed_at = ?");
      updateParams.push(body.completed_at);
    }
    
    // If no fields to update, return error
    if (updateFields.length === 0) {
      return NextResponse.json(
        { error: 'Vitalisona: No valid fields provided for update' }, 
        { status: 400 }
      );
    }
    
    // Add where clause parameters
    updateParams.push(body.id);
    updateParams.push(user_id);
    
    // Execute update query
    const updateQuery = `UPDATE sessions SET ${updateFields.join(', ')} WHERE id = ? AND userid = ?`;
    await db_query(db, updateQuery, updateParams);
    
    // Fetch updated session data
    const updatedSession = await db_query(
      db, 
      "SELECT * FROM sessions WHERE id = ? AND userid = ?", 
      [body.id, user_id]
    );
    
    if (!updatedSession || updatedSession.length === 0) {
      return NextResponse.json(
        { error: 'Vitalisona: Failed to retrieve updated session' }, 
        { status: 500 }
      );
    }
    
    const session = updatedSession[0];
    
    // Format result according to output interface
    const result = {
      id: session.id,
      servicesid: session.servicesid,
      practitionersid: session.practitionersid,
      session_date: session.session_date,
      session_time: session.session_time,
      duration: session.duration,
      status: session.status,
      notes: session.notes,
      price: session.price,
      created_at: session.created_at,
      completed_at: session.completed_at
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona SessionsUpdate error:', error);
    return NextResponse.json(
      { error: 'Vitalisona: Internal server error during session update' }, 
      { status: 500 }
    );
  }
}

