
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required parameters
    if (!id) {
      return NextResponse.json({ error: 'Service ID is required for Vitalisona service lookup' }, { status: 400 });
    }
    
    // Query the services table for the specific service
    const serviceResult = await db_query(db, "SELECT * FROM services WHERE id = ?", [id]);
    
    if (!serviceResult || serviceResult.length === 0) {
      return NextResponse.json({ error: 'Vitalisona service not found' }, { status: 404 });
    }
    
    const service = serviceResult[0];
    
    // Format the response according to the output interface
    const result = {
      id: service.id,
      name: service.name,
      description: service.description,
      duration: service.duration,
      price: service.price,
      category: service.category,
      benefits: service.benefits || null,
      service_image: service.service_image || null,
      available: service.available,
      display_order: service.display_order || null
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona ServicesGet API error:', error);
    return NextResponse.json({ error: 'Failed to retrieve Vitalisona service details' }, { status: 500 });
  }
}

