
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Job Listing  Add',
    description: 'Add a new JobListing',
    openGraph: {
        title: 'Job Listing  Add',
        description: 'Add a new JobListing',
        url: '/joblisting_add',
        siteName: 'TechCorp'
    },
};

export default  function joblisting_add() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Category","link":"/category_list"},{"title":"Category  Details","link":"/category_details/[id]"},{"title":"Job Listing  Add","link":"/joblisting_add"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="JobListing"
                                fields={[{"name":"job_title","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":"null","children":[]},{"name":"job_description","datatype":"TEXT","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"false","untouchable":"false","default":"null","children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"},{"name":"EmployerProfileID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"},{"name":"CategoryID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"}]}
                                mode="add"
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}