/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const categoryid = searchParams.get('categoryid');
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '20');
    const available = searchParams.get('available') ? searchParams.get('available') === 'true' : null;
    const minprice = searchParams.get('minprice') ? parseFloat(searchParams.get('minprice')) : null;
    const maxprice = searchParams.get('maxprice') ? parseFloat(searchParams.get('maxprice')) : null;
    const size = searchParams.get('size');
    const color = searchParams.get('color');
    const material = searchParams.get('material');
    const era_period = searchParams.get('era_period');
    const sortby = searchParams.get('sortby') || 'newest';
    const sortorder = searchParams.get('sortorder') || 'desc';
    
    // Validate required parameter
    if (!categoryid) {
      return NextResponse.json(
        { error: 'Victorian Era requires categoryid parameter to display products' },
        { status: 400 }
      );
    }
    
    // Get category details
    const categoryResult = await db_query(
      db,
      'SELECT id, name, description, image_url, display_order, visible FROM categories WHERE id = $1',
      [categoryid]
    );
    
    if (categoryResult.length === 0) {
      return NextResponse.json(
        { error: 'Victorian Era category not found' },
        { status: 404 }
      );
    }
    
    const category = categoryResult[0];
    
    // Build products query with filters
    let queryParams = [];
    let paramIndex = 1;
    let whereConditions = ['p.categoriesid = $' + paramIndex];
    queryParams.push(categoryid);
    paramIndex++;
    
    // Filter by availability
    if (available !== null) {
      whereConditions.push('p.available = $' + paramIndex);
      queryParams.push(available);
      paramIndex++;
    }
    
    // Filter by minimum price
    if (minprice !== null) {
      whereConditions.push('p.price >= $' + paramIndex);
      queryParams.push(minprice);
      paramIndex++;
    }
    
    // Filter by maximum price
    if (maxprice !== null) {
      whereConditions.push('p.price <= $' + paramIndex);
      queryParams.push(maxprice);
      paramIndex++;
    }
    
    // Filter by size
    if (size) {
      whereConditions.push('p.size = $' + paramIndex);
      queryParams.push(size);
      paramIndex++;
    }
    
    // Filter by color
    if (color) {
      whereConditions.push('p.color = $' + paramIndex);
      queryParams.push(color);
      paramIndex++;
    }
    
    // Filter by material
    if (material) {
      whereConditions.push('p.material = $' + paramIndex);
      queryParams.push(material);
      paramIndex++;
    }
    
    // Filter by era period
    if (era_period) {
      whereConditions.push('p.era_period = $' + paramIndex);
      queryParams.push(era_period);
      paramIndex++;
    }
    
    const whereClause = whereConditions.join(' AND ');
    
    // Count total products
    const countQuery = `SELECT COUNT(*) as total FROM products p WHERE ${whereClause}`;
    const countResult = await db_query(db, countQuery, queryParams);
    const total = parseInt(countResult[0].total);
    const totalpages = Math.ceil(total / limit);
    
    // Build sort clause
    let orderByClause = 'ORDER BY ';
    if (sortby === 'price') {
      orderByClause += 'p.price ' + (sortorder === 'asc' ? 'ASC' : 'DESC');
    } else if (sortby === 'name') {
      orderByClause += 'p.name ' + (sortorder === 'asc' ? 'ASC' : 'DESC');
    } else {
      // Default to newest (by id)
      orderByClause += 'p.id DESC';
    }
    
    // Calculate offset
    const offset = (page - 1) * limit;
    
    // Get products with primary image
    const productsQuery = `
      SELECT 
        p.id,
        p.categoriesid,
        p.name,
        p.description,
        p.price,
        p.sku,
        p.stock_quantity,
        p.size,
        p.color,
        p.material,
        p.era_period,
        p.available,
        p.featured,
        pi.image_url as primary_image_url
      FROM products p
      LEFT JOIN productimages pi ON p.id = pi.productsid AND pi.is_primary = true
      WHERE ${whereClause}
      ${orderByClause}
      LIMIT $${paramIndex} OFFSET $${paramIndex + 1}
    `;
    
    const finalParams = [...queryParams, limit, offset];
    const productsResult = await db_query(db, productsQuery, finalParams);
    
    // Format products data
    const productsData = productsResult.map(product => ({
      id: product.id,
      categoriesid: product.categoriesid,
      name: product.name,
      description: product.description,
      price: parseFloat(product.price),
      sku: product.sku,
      stock_quantity: product.stock_quantity,
      size: product.size,
      color: product.color,
      material: product.material,
      era_period: product.era_period,
      available: product.available,
      featured: product.featured,
      primary_image_url: product.primary_image_url
    }));
    
    // Build result
    const result = {
      category: {
        id: category.id,
        name: category.name,
        description: category.description,
        image_url: category.image_url,
        display_order: category.display_order,
        visible: category.visible
      },
      products: {
        data: productsData,
        total: total,
        page: page,
        limit: limit,
        totalpages: totalpages
      }
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Victorian Era products by category error:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve Victorian Era products for this category' },
      { status: 500 }
    );
  }
}
