
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Candidate Profile  Add',
    description: 'Add a new CandidateProfile',
    openGraph: {
        title: 'Candidate Profile  Add',
        description: 'Add a new CandidateProfile',
        url: '/candidateprofile_add',
        siteName: 'Job Board'
    },
};

export default  function candidateprofile_add() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Candidate Profile","link":"/candidateprofile_list"},{"title":"Candidate Profile  Add","link":"/candidateprofile_add"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="CandidateProfile"
                                fields={[{"name":"full_name","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"email","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"false","is_searchable":"true","required":"true","untouchable":"false","default":null,"children":[]},{"name":"profile_summary","datatype":"TEXT","datatypesize":"null","key":null,"is_name":"false","is_searchable":"true","required":"false","untouchable":"false","default":null,"children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"}]}
                                mode="add"
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}