
/* 
This file is generated by Sitepaige. 
Do not modify this file unless you have checked "Exclude from Build" in the Sitepaige tool.
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const search = searchParams.get('search');
    const publishedParam = searchParams.get('published');
    const sort = searchParams.get('sort') || 'display_order';
    const page = parseInt(searchParams.get('page')) || 1;
    const limit = parseInt(searchParams.get('limit')) || 20;
    
    // Validate page and limit
    if (page < 1) {
      return NextResponse.json({ error: 'Page must be greater than 0' }, { status: 400 });
    }
    if (limit < 1 || limit > 100) {
      return NextResponse.json({ error: 'Limit must be between 1 and 100' }, { status: 400 });
    }
    
    // Calculate offset
    const offset = (page - 1) * limit;
    
    // Build WHERE conditions
    let whereConditions = [];
    let queryParams = [];
    let paramIndex = 1;
    
    // Handle search
    if (search && search.trim() !== '') {
      whereConditions.push("(name LIKE ? OR description LIKE ?)");
      queryParams.push(`%${search.trim()}%`);
      queryParams.push(`%${search.trim()}%`);
      paramIndex += 2;
    }
    
    // Handle published filter
    if (publishedParam !== null) {
      const published = publishedParam === 'true';
      whereConditions.push("published = ?");
      queryParams.push(published);
      paramIndex += 1;
    }
    
    // Build WHERE clause
    const whereClause = whereConditions.length > 0 ? `WHERE ${whereConditions.join(' AND ')}` : '';
    
    // Handle sorting
    let orderBy = 'ORDER BY display_order ASC';
    if (sort === 'name') {
      orderBy = 'ORDER BY name ASC';
    } else if (sort === 'created_at') {
      orderBy = 'ORDER BY created_at DESC';
    } else if (sort === 'display_order') {
      orderBy = 'ORDER BY display_order ASC';
    }
    
    // Get total count
    const countQuery = `SELECT COUNT(*) as total FROM categories ${whereClause}`;
    const countResult = await db_query(db, countQuery, queryParams);
    const total = countResult[0].total;
    
    // Get paginated data
    const dataQuery = `SELECT * FROM categories ${whereClause} ${orderBy} LIMIT ? OFFSET ?`;
    const finalParams = [...queryParams, limit, offset];
    const categories = await db_query(db, dataQuery, finalParams);
    
    // Calculate total pages
    const totalpages = Math.ceil(total / limit);
    
    // Format response
    const result = {
      data: categories.map(category => ({
        id: category.id,
        name: category.name,
        slug: category.slug,
        description: category.description,
        image_url: category.image_url,
        display_order: category.display_order,
        published: category.published,
        created_at: category.created_at,
        updated_at: category.updated_at
      })),
      total: total,
      page: page,
      limit: limit,
      totalpages: totalpages
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Error fetching categories:', error);
    return NextResponse.json({ error: 'Failed to fetch categories' }, { status: 500 });
  }
}

