/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required id field
    if (!body.id) {
      return NextResponse.json({ error: 'Vitalisona: Resource ID is required for updating wellness resource' }, { status: 400 });
    }
    
    // Check if the wellness resource exists
    const existingResource = await db_query(db, "SELECT * FROM wellnessresources WHERE id = ?", [body.id]);
    
    if (!existingResource || existingResource.length === 0) {
      return NextResponse.json({ error: 'Vitalisona: Wellness resource not found' }, { status: 404 });
    }
    
    // Build dynamic UPDATE query for provided fields
    const updateFields = [];
    const updateParams = [];
    
    if (body.title !== undefined) {
      updateFields.push('title = ?');
      updateParams.push(body.title);
    }
    
    if (body.content !== undefined) {
      updateFields.push('content = ?');
      updateParams.push(body.content);
    }
    
    if (body.category !== undefined) {
      updateFields.push('category = ?');
      updateParams.push(body.category);
    }
    
    if (body.author !== undefined) {
      updateFields.push('author = ?');
      updateParams.push(body.author);
    }
    
    if (body.published_date !== undefined) {
      updateFields.push('published_date = ?');
      updateParams.push(body.published_date);
    }
    
    if (body.tags !== undefined) {
      updateFields.push('tags = ?');
      updateParams.push(body.tags);
    }
    
    // Handle featured image upload if provided
    if (body.featured_image !== undefined) {
      if (body.featured_image) {
        const imageRef = await store_file('wellness_resource_image.jpg', body.featured_image, true);
        updateFields.push('featured_image = ?');
        updateParams.push(imageRef);
      } else {
        updateFields.push('featured_image = ?');
        updateParams.push(null);
      }
    }
    
    if (body.published !== undefined) {
      updateFields.push('published = ?');
      updateParams.push(body.published);
    }
    
    if (body.featured !== undefined) {
      updateFields.push('featured = ?');
      updateParams.push(body.featured);
    }
    
    if (body.display_order !== undefined) {
      updateFields.push('display_order = ?');
      updateParams.push(body.display_order);
    }
    
    // If no fields to update, return current resource
    if (updateFields.length === 0) {
      const result = {
        id: existingResource[0].id,
        title: existingResource[0].title,
        content: existingResource[0].content,
        category: existingResource[0].category,
        author: existingResource[0].author,
        published_date: existingResource[0].published_date,
        tags: existingResource[0].tags,
        featured_image: existingResource[0].featured_image,
        published: existingResource[0].published,
        featured: existingResource[0].featured,
        display_order: existingResource[0].display_order
      };
      return NextResponse.json(result);
    }
    
    // Add the ID parameter for the WHERE clause
    updateParams.push(body.id);
    
    // Execute the update
    const updateQuery = `UPDATE wellnessresources SET ${updateFields.join(', ')} WHERE id = ?`;
    await db_query(db, updateQuery, updateParams);
    
    // Fetch and return the updated resource
    const updatedResource = await db_query(db, "SELECT * FROM wellnessresources WHERE id = ?", [body.id]);
    
    if (!updatedResource || updatedResource.length === 0) {
      return NextResponse.json({ error: 'Vitalisona: Failed to retrieve updated wellness resource' }, { status: 500 });
    }
    
    const result = {
      id: updatedResource[0].id,
      title: updatedResource[0].title,
      content: updatedResource[0].content,
      category: updatedResource[0].category,
      author: updatedResource[0].author,
      published_date: updatedResource[0].published_date,
      tags: updatedResource[0].tags,
      featured_image: updatedResource[0].featured_image,
      published: updatedResource[0].published,
      featured: updatedResource[0].featured,
      display_order: updatedResource[0].display_order
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona: Error updating wellness resource:', error);
    return NextResponse.json({ error: 'Vitalisona: Internal server error while updating wellness resource' }, { status: 500 });
  }
}
