/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

    if (UserInfo.IsAdmin !== true) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }

  
  try {
    // Get total products count
    const totalResult = await db_query(db, "SELECT COUNT(*) as count FROM products");
    const total_products = parseInt(totalResult[0].count);
    
    // Get low stock count (quantity < 10 but > 0)
    const lowStockResult = await db_query(db, "SELECT COUNT(*) as count FROM products WHERE stock_quantity < 10 AND stock_quantity > 0");
    const low_stock_count = parseInt(lowStockResult[0].count);
    
    // Get out of stock count (quantity = 0)
    const outOfStockResult = await db_query(db, "SELECT COUNT(*) as count FROM products WHERE stock_quantity = 0");
    const out_of_stock_count = parseInt(outOfStockResult[0].count);
    
    // Get available products count
    const availableResult = await db_query(db, "SELECT COUNT(*) as count FROM products WHERE available = true");
    const available_products = parseInt(availableResult[0].count);
    
    // Get unavailable products count
    const unavailableResult = await db_query(db, "SELECT COUNT(*) as count FROM products WHERE available = false");
    const unavailable_products = parseInt(unavailableResult[0].count);
    
    // Get products by category breakdown
    const categoryBreakdown = await db_query(db, 
      "SELECT c.id, c.name, COUNT(p.id) as product_count FROM categories c LEFT JOIN products p ON c.id = p.categoriesid GROUP BY c.id, c.name ORDER BY c.name ASC"
    );
    
    const products_by_category = categoryBreakdown.map(cat => ({
      category_id: cat.id,
      category_name: cat.name,
      product_count: parseInt(cat.product_count)
    }));
    
    const result = {
      total_products,
      low_stock_count,
      out_of_stock_count,
      available_products,
      unavailable_products,
      products_by_category
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    return NextResponse.json({ error: 'Failed to retrieve inventory status' }, { status: 500 });
  }
}
