
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Details from '@/components/details';
import List from '@/components/list';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Job Location  Details',
    description: 'Details of JobLocation',
    openGraph: {
        title: 'Job Location  Details',
        description: 'Details of JobLocation',
        url: '/joblocation_details',
        siteName: 'Job Board'
    },
};

export default async function joblocation_details({ params }:  { params: Promise<{ id: string }>}) {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Job Location","link":"/joblocation_list"},{"title":"Job Location  Details","link":"/joblocation_details/[id]"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Details
                                modelName="JobLocation"
                                id={(await params).id}
                            />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col">    
                            <List
                                modelName="JobPosting"
                                showAdminFeatures={true}
                                nameField="job_title"
                                 subFieldName="JobLocationID" subFieldValue={(await params).id}
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}