
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import { ErrorBoundary } from 'react-error-boundary';
import { Error } from '@/components/error';
import MembersList from '@/custom/Members_List';

export const metadata: Metadata = {
    title: 'Members',
    description: 'Page for Members',
    openGraph: {
        title: 'Members',
        description: 'Page for Members',
        url: '/members',
        siteName: 'Maryland Christmas'
    },
};

export default  function members() {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col" style={{ gridColumn: `span 12 / span 12` }}><section className="card">
                            <ErrorBoundary fallback={<Error />}>
                                <MembersList />
                            </ErrorBoundary>
                        </section>
                        </div>
                    </div>
            </main>
        </div>
    );
}