/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function PUT(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.id) {
      return NextResponse.json(
        { error: 'Vitalisona wellness journal entry ID is required' }, 
        { status: 400 }
      );
    }

    // Check if the wellness journal entry exists and belongs to the user
    const existingEntry = await db_query(
      db, 
      'SELECT * FROM wellnessjournal WHERE id = ? AND userid = ?', 
      [body.id, user_id]
    );

    if (!existingEntry || existingEntry.length === 0) {
      return NextResponse.json(
        { error: 'Vitalisona wellness journal entry not found or access denied' }, 
        { status: 404 }
      );
    }

    // Build update query dynamically based on provided fields
    const updateFields = [];
    const queryParams = [];
    
    if (body.mood_rating !== undefined) {
      updateFields.push('mood_rating = ?');
      queryParams.push(body.mood_rating);
    }
    
    if (body.energy_level !== undefined) {
      updateFields.push('energy_level = ?');
      queryParams.push(body.energy_level);
    }
    
    if (body.stress_level !== undefined) {
      updateFields.push('stress_level = ?');
      queryParams.push(body.stress_level);
    }
    
    if (body.sleep_quality !== undefined) {
      updateFields.push('sleep_quality = ?');
      queryParams.push(body.sleep_quality);
    }
    
    if (body.notes !== undefined) {
      updateFields.push('notes = ?');
      queryParams.push(body.notes);
    }
    
    if (body.session_feedback !== undefined) {
      updateFields.push('session_feedback = ?');
      queryParams.push(body.session_feedback);
    }
    
    if (body.goals !== undefined) {
      updateFields.push('goals = ?');
      queryParams.push(body.goals);
    }

    // If no fields to update, return current entry
    if (updateFields.length === 0) {
      const result = {
        id: existingEntry[0].id,
        entry_date: existingEntry[0].entry_date,
        mood_rating: existingEntry[0].mood_rating,
        energy_level: existingEntry[0].energy_level,
        stress_level: existingEntry[0].stress_level,
        sleep_quality: existingEntry[0].sleep_quality,
        notes: existingEntry[0].notes,
        session_feedback: existingEntry[0].session_feedback,
        goals: existingEntry[0].goals,
        created_at: existingEntry[0].created_at
      };
      return NextResponse.json(result);
    }

    // Add id and userid to params for WHERE clause
    queryParams.push(body.id, user_id);

    // Perform the update
    const updateQuery = `UPDATE wellnessjournal SET ${updateFields.join(', ')} WHERE id = ? AND userid = ?`;
    await db_query(db, updateQuery, queryParams);

    // Fetch and return the updated entry
    const updatedEntry = await db_query(
      db, 
      'SELECT * FROM wellnessjournal WHERE id = ? AND userid = ?', 
      [body.id, user_id]
    );

    if (!updatedEntry || updatedEntry.length === 0) {
      return NextResponse.json(
        { error: 'Failed to retrieve updated Vitalisona wellness journal entry' }, 
        { status: 500 }
      );
    }

    const result = {
      id: updatedEntry[0].id,
      entry_date: updatedEntry[0].entry_date,
      mood_rating: updatedEntry[0].mood_rating,
      energy_level: updatedEntry[0].energy_level,
      stress_level: updatedEntry[0].stress_level,
      sleep_quality: updatedEntry[0].sleep_quality,
      notes: updatedEntry[0].notes,
      session_feedback: updatedEntry[0].session_feedback,
      goals: updatedEntry[0].goals,
      created_at: updatedEntry[0].created_at
    };

    return NextResponse.json(result);

  } catch (error) {
    console.error('Vitalisona wellness journal update error:', error);
    return NextResponse.json(
      { error: 'Failed to update Vitalisona wellness journal entry' }, 
      { status: 500 }
    );
  }
}
