
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function POST(request) {
  // Initialize database connection
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse and validate request body
    const body = await request.json();
    
    // Validate required fields
    if (!body.name) {
      return NextResponse.json({ error: 'Service name is required for Vitalisona services' }, { status: 400 });
    }
    if (!body.description) {
      return NextResponse.json({ error: 'Service description is required for Vitalisona services' }, { status: 400 });
    }
    if (!body.duration || typeof body.duration !== 'number') {
      return NextResponse.json({ error: 'Valid service duration is required for Vitalisona services' }, { status: 400 });
    }
    if (!body.price || typeof body.price !== 'number') {
      return NextResponse.json({ error: 'Valid service price is required for Vitalisona services' }, { status: 400 });
    }
    if (!body.category) {
      return NextResponse.json({ error: 'Service category is required for Vitalisona services' }, { status: 400 });
    }
    if (typeof body.available !== 'boolean') {
      return NextResponse.json({ error: 'Service availability status is required for Vitalisona services' }, { status: 400 });
    }

    // Generate unique ID for the service
    const serviceId = crypto.randomUUID();
    
    // Handle service image if provided
    let serviceImageRef = null;
    if (body.service_image) {
      try {
        serviceImageRef = await store_file(`vitalisona_service_${serviceId}.jpg`, body.service_image, true);
      } catch (error) {
        console.error('Vitalisona service image storage error:', error);
        return NextResponse.json({ error: 'Failed to store service image for Vitalisona service' }, { status: 500 });
      }
    }

    // Insert the new service into database
    await db_query(db, `
      INSERT INTO services (id, name, description, duration, price, category, benefits, service_image, available, display_order)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `, [
      serviceId,
      body.name,
      body.description,
      body.duration,
      body.price,
      body.category,
      body.benefits || null,
      serviceImageRef,
      body.available,
      body.display_order || null
    ]);

    // Prepare result object matching output interface specification
    const result = {
      id: serviceId,
      name: body.name,
      description: body.description,
      duration: body.duration,
      price: body.price,
      category: body.category,
      benefits: body.benefits || null,
      service_image: serviceImageRef,
      available: body.available,
      display_order: body.display_order || null
    };

  } catch (error) {
    console.error('Vitalisona ServicesCreate API error:', error);
    return NextResponse.json({ error: 'Failed to create Vitalisona sound healing service' }, { status: 500 });
  }

  return NextResponse.json(result);
}

