/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../auth/auth';
import { store_file } from '../../storage/files';
import { db_init, db_query } from '../../db';

export async function GET(request) {
  const db = await db_init();
  let user_id = null;
  
  
  
  try {
    // Parse and validate request parameters
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');
    
    // Validate required fields
    if (!id) {
      return NextResponse.json(
        { error: 'Vitalisona practitioner ID is required' }, 
        { status: 400 }
      );
    }
    
    // Query the practitioners table for the specific practitioner
    const query = "SELECT * FROM practitioners WHERE id = ?";
    const practitioners = await db_query(db, query, [id]);
    
    // Check if practitioner exists
    if (!practitioners || practitioners.length === 0) {
      return NextResponse.json(
        { error: 'Vitalisona practitioner not found' }, 
        { status: 404 }
      );
    }
    
    const practitioner = practitioners[0];
    
    // Format the response according to the output interface
    const result = {
      id: practitioner.id,
      name: practitioner.name,
      bio: practitioner.bio,
      specializations: practitioner.specializations,
      certifications: practitioner.certifications,
      experience_years: practitioner.experience_years,
      profile_image: practitioner.profile_image,
      email: practitioner.email,
      phone: practitioner.phone,
      available: practitioner.available,
      display_order: practitioner.display_order
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    console.error('Vitalisona PractitionersGet API error:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve Vitalisona practitioner details' }, 
      { status: 500 }
    );
  }
}
