
/* 
This file is generated by SysArchitect. 
Do not modify this file unless you have checked "Exclude from Build" in the SysArchitect tool.
*/
import { Metadata } from 'next';
import Form from '@/components/form';
import Breadcrumb from '@/components/breadcrumb';

export const metadata: Metadata = {
    title: 'Job Application  Edit',
    description: 'Edit a JobApplication',
    openGraph: {
        title: 'Job Application  Edit',
        description: 'Edit a JobApplication',
        url: '/jobapplication_edit',
        siteName: 'TechCorp'
    },
};

export default async function jobapplication_edit({ params }:  { params: Promise<{ id: string }>}) {
    
    return (
        <div className="page">
            <main>
                
                    <div className="row">
                        <div className="col">    
                            <Breadcrumb breadcrumbs={[{"title":"Home","link":"/"},{"title":"Dashboard","link":"/dashboard"},{"title":"Category","link":"/category_list"},{"title":"Category  Details","link":"/category_details/[id]"},{"title":"Job Listing  Details","link":"/joblisting_details/[id]"},{"title":"Job Application  Edit","link":"/jobapplication_edit/[id]"}]} />
                        </div>
                    </div>
                
                
                    <div className="row">
                        <div className="col">    
                            <Form
                                modelName="JobApplication"
                                fields={[{"name":"applicant_name","datatype":"VARCHAR","datatypesize":"255","key":null,"is_name":"true","is_searchable":"true","required":"true","untouchable":"false","default":"null","children":[]},{"name":"ID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"primary","untouchable":"true"},{"name":"JobListingID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"},{"name":"ResumeDatabaseID","datatype":"UUID","datatypesize":"","children":[],"default":null,"required":"true","is_name":"false","is_searchable":"true","key":"foreign","untouchable":"true"}]}
                                mode="edit"
                                id={(await params).id}
                            />
                        </div>
                    </div>
            </main>
        </div>
    );
}