
/* 
This file is generated by Sitepaige. 
*/
import { NextRequest, NextResponse } from 'next/server';
import { check_auth } from '../../../auth/auth';
import { store_file } from '../../../storage/files';
import { db_init, db_query } from '../../../database/sqlite';

export async function DELETE(request) {
  const db = await db_init();
  let user_id = null;
  
  
    const UserInfo = await check_auth(db, db_query);
    if (UserInfo.userid.length === 0) { return NextResponse.json({ error: "Forbidden" }, { status: 403 }); }
    user_id = UserInfo.userid;

  
  try {
    // Parse request parameters - check both query params and body
    const url = new URL(request.url);
    const idFromQuery = url.searchParams.get('id');
    
    let id = idFromQuery;
    
    // If not in query params, try request body
    if (!id) {
      try {
        const body = await request.json();
        id = body.id;
      } catch (e) {
        // Body might be empty for DELETE, that's ok if we got id from query
      }
    }
    
    // Validate required fields
    if (!id) {
      const result = {
        success: false,
        message: "Journal entry ID is required for Vitalisona wellness journal deletion"
      };
      return NextResponse.json(result, { status: 400 });
    }
    
    if (!user_id) {
      const result = {
        success: false,
        message: "Authentication required to delete Vitalisona wellness journal entries"
      };
      return NextResponse.json(result, { status: 401 });
    }
    
    // Check if the journal entry exists and belongs to the user
    const existingEntry = await db_query(db, 
      "SELECT id FROM wellnessjournal WHERE id = ? AND userid = ?", 
      [id, user_id]
    );
    
    if (!existingEntry || existingEntry.length === 0) {
      const result = {
        success: false,
        message: "Wellness journal entry not found or access denied for Vitalisona user"
      };
      return NextResponse.json(result, { status: 404 });
    }
    
    // Delete the journal entry
    await db_query(db, 
      "DELETE FROM wellnessjournal WHERE id = ? AND userid = ?", 
      [id, user_id]
    );
    
    const result = {
      success: true,
      message: "Wellness journal entry successfully deleted from Vitalisona personal journal"
    };
    
    return NextResponse.json(result);
    
  } catch (error) {
    const result = {
      success: false,
      message: "Failed to delete Vitalisona wellness journal entry due to server error"
    };
    return NextResponse.json(result, { status: 500 });
  }
}

